### ISSUE TITLE
Online documentation typo?

### ISSUE THREAD

**Issue by Rgconner** [openlegend/core-rules#101]
Character creation shows Fortitude related to Armor under Step1: Choose Attributes, PHYSICAL ATTRIBUTES AT A GLANCE

http://www.openlegendrpg.com/core-rules/01-character-creation

Physical Attributes at a Glance
Agility	Dodge attacks, move with stealth, perform acrobatics, shoot a bow, pick a pocket
Fortitude	Wear heavy armor, resist poison, shrug off pain, exert yourself physically
Might	Swing a maul, jump over a chasm, break down a door, wrestle a foe to submission

**Comment by raihje** [comment]
They recently changed it to Might requirements instead of Fortitude, I'll fix and issue a PR.

**Comment by brianfeister** [comment]
Thanks, fixed. https://github.com/openlegend/core-rules/pull/102
