### ISSUE TITLE
Exception success

### ISSUE THREAD

**Issue by llothos** [openlegend/core-rules#104]
Exceptional Success
If your attack roll exceeds the target’s defense by 10 or more, you may apply one bane of a Power Level less than or equal to the attribute you used for the attack. In order to apply a bane, your attack roll must equal or exceed the appropriate defense for that bane. If your attack targeted multiple foes, you may apply the bane to each qualifying target.

Proposed changes in CAPS.

Exceptional Success
If your attack roll exceeds the target’s defense by 10 or more, you may apply one bane of a Power Level less than or equal to the attribute you used for the attack. BUT In order to apply THE bane, your attack roll must equal or exceed the appropriate defense for that bane. If your attack targeted multiple foes, you may apply the bane to each qualifying target.

**Comment by brianfeister** [comment]
Hmmm... not sure if I agree with this change. I'll leave it to @istabosz, but I don't feel like this is an obvious improvement.

**Comment by brianfeister** [comment]
Hmmm... not sure I agree with this change, it doesn't seem like a clearly better way of saying it. I'll leave it to @istabosz

**Comment by llothos** [comment]
I just thought a clarification might be needed on that. Anything proposed could work,  I just gave a example.

**Comment by istabosz** [comment]
Thanks, @llothos 

I think it is clear enough as is, but I'll keep this one in mind in case anyone else flags it.
