### ISSUE TITLE
Mismatch between equipment and attribute descriptions

### ISSUE THREAD

**Issue by vehemot** [openlegend/core-rules#109]
Agility:	Dodge attacks, move with stealth, perform acrobatics, shoot a bow, pick a pocket
Fortitude:	**Wear heavy armor**, resist poison, shrug off pain, exert yourself physically
Might:	Swing a maul, jump over a chasm, break down a door, wrestle a foe to submission

Armor	Wealth Level	**Required Might**	Heavy	Defense Bonus	Speed Penalty

simple fix, but I figure you'd prefer designated individuals make the change.

**Comment by raihje** [comment]
Actually, anyone can fork this, make the changes and then issue a pull request. I fixed this already though, at least for the attributes since that was another issue. I think I ended up closing the pull request though, I'll redo this and it'll update the pull request I have outstanding.

**Comment by brianfeister** [comment]
When I last rebuilt the site I forgot to rebuild the rules docs. Fixed and deployed now.
