### ISSUE TITLE
Clarification about Scrying bane

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#11]
https://github.com/openlegend/core-rules/blob/master/banes/banes.yml#L560

Scrying provides two sets of rules depending on whether you are scrying a creature or a place. This makes sense. What I don't get is why you can scry a place on another plane of existence, but when it comes to a creature, they have to be on the same plane.

**Comment by istabosz** [comment]
Actually, scratch that. What do you think of this instead? I think it provides some more interesting story possibilities.

The CR to scry is determined by the distance between you and the area you are scrying, as follows:
[insert table here]
If there are any sentient creatures in the area being scryed and your Divination roll fails to equal or exceed their Resolve score, then those creatures become aware that they are being scryed upon.

**Comment by brianfeister** [comment]
You're a genius. The latter suggestion is a PERFECT fix for something I struggled with for a long time!

**Comment by istabosz** [comment]
Cool! I've revised it. Let me know what you think.

**Comment by DMsShadow** [comment]
I like it, much more streamlined, though the target would have to have a pretty high resolve to notice you on a successful roll. Does give nice options for still being able to scry them on a failure though. You see them, but the feel you watching.

**Comment by brianfeister** [comment]
He raises a good point, I kind of wonder if we shouldn't specify the "fail effect" in this particular bane. Maybe just say 

> Regardless of your success at invoking the bane, if your roll is lower than the Resolve defense of anyone in the area, they become aware of your attempt.

Without that, as @DMsShadow pointed out, you'll often have a CR 24 roll, which means that only those with a Resolve of 25 or better will notice. This way there's  a direct risk for attempting it and the GM can of course make ad-hoc rulings on top of that to make things even worse if the roll is exceptionally low. I guess advising on the failure isn't something we've done, but I feel like adding that in this circumstance helps to be more clear about the relationship between successful invocation and the partial success / risk of failure that we're hardcoding into the effect.

**Comment by istabosz** [comment]
Makes sense. I think that's what I intended in the first place, but I've added some text to clarify.
