### ISSUE TITLE
Mismatch in power between Forced Move Bane and Telekinesis Boon for Movement Attribute

### ISSUE THREAD

**Issue by hmack312** [openlegend/core-rules#110]
As it is, a telekinetic character can move other characters with a minimum Movement score of 2, however, the Telekinesis Boon does not allow said character to even lift a fist sized rock until he/she has a Movement score of 5. Is this supposed to reflect fine tuned telekinesis vs general applied force? Even if this is the case a character with a 5 Movement score could potentially send a creature _of any size_ (so long as they can beat the toughness score, ignoring weight)  flying up to 12ish feet or 2.5 squares. So the same character who can send a creatures twice the weight of a human flying 12 feet struggles to lift a fist sized rock? Am I missing something?

**Comment by brianfeister** [comment]
We could modify this a bit for telekinesis. But the goal is game balance here, despite some trade off in realism.

**Comment by raihje** [comment]
This kind of makes sense. A character can apply enougn general force to make a person stagger 5' (which isn't much in most instances) Or they can  presicely control something the size of a fist (which means encompassing it in a field of force, not just blasting something from a direction)

**Comment by brianfeister** [comment]
Fixed @ https://github.com/openlegend/core-rules/commit/0b83dfa476653e83a4fe7aac67f7f5d04458982e
