### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#111]

**Comment by brianfeister** [comment]
@raihje any chance I could convince you to tackle this as an ongoing responsibility for me? People are losing their minds when things disappear. I would just do it as Markdown bullets in the. Base README

**Comment by brianfeister** [comment]
You've already earned a mention in the core Rulebook if that's any consolation

**Comment by raihje** [comment]
Lol, alright so bullets in the README.md I can get to work on that.

**Comment by brianfeister** [comment]
@raihje thanks for doing this! We will see what happens with the changelog, I'm just trying to maximize visibility now, but we probably will change it in a bit.

Thanks for the generous support! I'll be adding your name for proofreading / editing type stuff, so you'll appear twice :)
