### ISSUE TITLE
Barrier Boon

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#115]
Per discussion in Issue #100 here is a proposed generalized boon to simulate walls, barriers, clouds, etc. This would replace the current retributive barrier boon.

# **Barrier**

**Duration:** Sustain Persists

**Invocation Time:** 1 Major Action

**Power Level:** 3 / 4 / 5 / 6 / 7 / 8

**Attributes:** Creation, Energy, Entropy, Protection

**Description:** You summon forth a wall of thorns, ring of fire, entropic fog, or similar barrier to hurt or hinder your foes.

**Effect:** When you invoke this boon, choose one of the following shapes for your barrier. You may choose a smaller size than listed:

- A Wall 10' in length per Power Level. The wall is 5' wide and 20' high.
- A Ring 5' in diameter per Power Level. The ring is 5' wide and 20' high.
- A Cube with sides equal to 5' per Power Level.

Next, choose one or more of the following effects for your barrier. Each effect has a cost listed. The total cost of effects can not exceed the power level at which you invoke this boon.

**Damage (cost varies).** Creatures who enter the area of your barrier immediately take damage. They may not suffer this damage more than once per round.
- Cost 3: d8 damage
- Cost 4: d10 damage
- Cost 5: 2d6 damage
- Cost 6: 2d8 damage
- Cost 7: 2d10 damage
- Cost 8: 3d8 damage

**Difficult Terrain (cost 3).** Creatures move at half speed when travelling within the barrier.

**Obscuring (cost 3).** Creatures cannot see through more than 10' of the barrier.

**Mobile (cost 2).** You may move the barrier 15' as a minor action. It may not be moved on the round in which it was created.

**Baneful (cost varies).** Choose a bane which you can inflict. When a creature enters the area of your barrier, you may immediately make a bane attack against them to inflict the chosen bane. A creature cannot be subject to such a bane attack from this barrier more than once per round. The cost of this effect is equal to the power level of the associated bane.

**Special:** 

- This boon is not subject to normal multi-targeting rules. 

- Any creatures who fall within the area of your barrier at the time it is invoked have a chance to avoid the barrier. The GM should choose an appropriate defense (Toughness, Evasion, or Resolve) according to the nature of your barrier. Any creature whose defense exceeds your action roll to invoke this boon may choose to move their full speed for free (though opportunity attacks and other movement restrictions still apply).

**Comment by raihje** [comment]
Excellent so far. However many references to not being able to see 10' into the barrier, etc. For the wall/ring is that more than 10' "through" the barrier so they can't see something on the other side?

**Comment by DukeAnax** [comment]
Still not a fan of the special multi-targetting rule. Open Legend's generally aims to be simple. It reduces the effect certain advantage feats have on the possible size of the Boon and removes the nuance of "Do I make it bigger and risk making it weaker?"

However the Barrier Effects are spot on, well done!

@raihje They way I see it, it is like milky or broken glass, when it is standing directly on the other side, you can see it to some degree, when it is further away it disappears.

**Comment by raihje** [comment]
I'd suggest having it diffuse from 5' instead of 10 (ie your standing 10' or further in and you're diffused. That way fog clouds and other similar effects are nerfed by requiring a particularly large radius just to hide say 1 or 2 people.

**Comment by DukeAnax** [comment]
I do agree that optainable base sizes might be an issue with regular area targetting.

But if it is, I'd rather see various power levels of the Barrier boon give advantage to area targetting, than have it define it's own special targetting.

**Comment by DukeAnax** [comment]
If base size is a problem with regular area targetting I'd rather have the Barrier boon reduce disadvantage than define it's own targetting.

**Comment by raihje** [comment]
I like the above, leave the targeting as the regular multi-targeting (hopefully with expanded areas implemented)

**Comment by brianfeister** [comment]
I'll add my recent comment from #100 here for consideration, I think I agree with @raihje that we just need to cover all of these as targeting options.

---

I think I would call `Circle` radius, personally and make it only target squares adjacent to a creature that you choose. Also I think `Line` should be clear that it doesn't have to extend or connect with the invoker so it could be a fissure of necromantic hell energy that springs opens from a crack in the earth. 

My only real problem is how to calculate the disadvantage for the `Radius` shape I'm describing. I suppose it's OK from a balance perspective to just make it `Disadvantage 3` (I think 2 would be too easy for targeting 8 squares in most situations). Being able to shapeshift / alternate form into a larger size to get extra `Radius` effect squares I think would be rare enough / expensive enough that `Disadvantage 3` might cover it.

**Comment by raihje** [comment]
How would you model expanding effects / large radii? +2D for each increment of radius?

**Comment by istabosz** [comment]
I'm cool with scaling back the damage, and just sticking to the standard targeting options.

As far as the mobile option is concerned, I think we need this somehow, because it is common to a lot of iconic effects that would fall under this boon, like summoning a swarm. I think if we just make it a major action to move the barrier, then it becomes balanced. We could also change the text for triggering damage/effects to be something like "If you end your turn in the area or if you willingly enter it". That way, targets who get the barrier dropped on them have a chance to escape or stay and suffer the consequences - which I kind of like because it forces hard decisions.

I realize we also need to add some sort of impassable option to simulate wall of ice/force/steel. And, we shouldn't consider damage as a default because plenty of barrier effects wouldn't cause damage, like a cloud of fog or entangling vines.

So how about this:

PL 3: Pick one - 1d4 damage, obscuring, difficult terrain
PL 5: Pick two - 1d8 damage, obscuring, difficult terrain, baneful, mobile
PL 7: Pick three - 1d10 damage, obscuring, difficult terrain, baneful, mobile, impassable
PL 9: Pick four - 2d6 damage, obscuring, difficult terrain, baneful, mobile, impassable

**Comment by DukeAnax** [comment]
Considering it is attached to a target and thus has a mobile aspect if persistent, Disadvantage 3 per 5' increment seems reasonable.

However, considering that we agreed that Effect and targetting Shape should be seperate, that discussion kinda belongs in the other Issue as this one is for Effects.

**Comment by brianfeister** [comment]
@istabosz that all sounds reasonable to me and I do think (reluctantly) that we'll add this as a global change for multi-targeting. `Radius` would have the special property (unlike other shapes) of having the invoker choose either a target creature or a square as the origin.

**Comment by istabosz** [comment]
I've added the Barrier boon as a new commit.
