### ISSUE TITLE
Questions about Darkness, Blindsight, and Truesight

### ISSUE THREAD

**Issue by hmack312** [openlegend/core-rules#116]
Question 1:
Blindsight and Truesight PL5 seem to be the same. Truesight specifically mentions that it can be used to see in magical darkness, but the Darkness Boon specifically mentions that Blindsight can counter it. The only real difference mentioned is that Blindsight also gives immunity to the blinded condition and isn't limited to 30 feet. What was the intended difference between these two?

Question 2:
Is the caster of the Darkness Boon capable of seeing in the affected area without the need of Blindsight/Truesight? The only thing mentioned pertaining to this is the area-targeting rules that say the caster is unaffected by his/her own area attacks, but that specifically mentions attacks.

**Comment by raihje** [comment]
Blindsight is a hard counter to magical darkness and blinded bane. Truesight is a hard counter to illusions and the like, and as such is a wee bit better than blindsight in some circumstances.
If you make an area dark, I'd say you need a means of seeing through it, as even if the 5' square you're on isn't affected (as per area rules) it's still dark all around you.

**Comment by brianfeister** [comment]
Q1: @raihje explains it well :)

Q2: Being the invoker of `Darkness` grants no special ability to see in it. It's omitted because the effect is no different for you than for others.
