### ISSUE TITLE
Is the stunned bane meant to prevent sustaining boons?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#12]
https://github.com/openlegend/core-rules/blob/master/banes/banes.yml#L651

The current text indicates that in addition to being limited to a single action, a stunned target also cannot sustain boons.

Is this correct? I'm asking because I thought that in a previous discussion you mentioned that the stunned bane can force casters to make hard choices about whether to sustain a boon or take an action.

**Comment by brianfeister** [comment]
Good catch, the thing is that I previously didn't have a clear way to define what methods there are of breaking "concentration" / "sustain" so I think I rolled it into here. I think you're right, there's an epic quality to holding onto this vital effect in the face of being stunned, so I'm good with removing the concentration-breaker side effect. 

I think what we should do is just be clear that a minor action (including sustain) is possible, but it precludes any other actions.

**Comment by istabosz** [comment]
Sounds good! Updated.
