### ISSUE TITLE
Weapons VS Supernatural

### ISSUE THREAD

**Issue by Dugahst** [openlegend/core-rules#124]
Unless I'm missing something, players utilizing weapons will always have an advantage over those attacking with supernatural powers (such as say a wizard casting a fireball).

This is due to the fact that weapons have additional properties associated with them for free (reach, free range that is not based on an attribute, etc) and they also get boosts to banes as well.

This to me seems grossly unfair.
One possible counter would be to have things like staves, wands, orbs, etc that could be used and each type would have its own properties that benefit supernatural skills- but even with this it wouldn't cover everything a person could come up with.

it just seems like more than any other sections, weapons will require the most house ruling.

**Comment by istabosz** [comment]
Supernatural attacks have the benefit of utilizing area attacks, and we are in the process of adding additional shapes, such as walls, cones, and lines. They also have the benefit of being able to target Toughness or Evasion (and I suppose Resolve in some cases), whereas weapon attacks always target Evasion.

And, supernatural attributes provide far more utility than Might or Agility, both in or outside of combat. So, I think as a whole, the attributes are pretty well-balanced.

**Comment by brianfeister** [comment]
@Dugahst thanks for the feedback and thanks to @istabosz for his response, which is correct. But Github is not the place for general rules discussions. Only for specific actionable proposals of fixes.

**Comment by brianfeister** [comment]
If you'd like to have a discussion about this, please take it to the community site: https://openlegend.mightybell.com

**Comment by Dugahst** [comment]
If that's the case on your website the "propose a change" button should link there instead of github

-Rob

**Comment by brianfeister** [comment]
@Dugahst the link is correct, the problem is that you didn't propose a change, you voiced an opinion. My apologies for the confusion.

**Comment by Dugahst** [comment]
Also iso said that supernatural attacks can utilize area attacks- I was under the impression that weapons could do the same (a barbarian making a cleave or a ranger launching a volley of arrows down upon an area)?

-Rob

**Comment by brianfeister** [comment]
Thanks so much for the feedback, I disagree about area attacks being appropriate for non-supernatural attacks. A ranger can launch a hail of arrows right now by just using the `Ranged` multi-target option. So 5 targets would be Disadvantage 5, which is a more accurate representation of the difficulty of shooting 5 targets than it is to attack with the Area attack rules.

Of course, if you're playing a very non-realistic perhaps anime-esque game and want to do away with realism intentionally then that would be a great house rule for your group.
