### ISSUE TITLE
Multi-attack specialist incorrect wording 

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#126]
Should say "disadvantage equal to 3x number of ADDITIONAL attacks"

**Comment by jcte02** [comment]
I have changed the wording in my fork branch. 
I don't know if what I've done is what you intended, so I won't open a pull request for now.

**Comment by brianfeister** [comment]
@jcte02 what was the status on this? Can you open your PR for me to review. The numbers should all be changed so that one Additional attack is Disadvantage 3 (with the feat offsetting this by 1 down to 2), and all the other bits that follow from this.

**Comment by brianfeister** [comment]
Closed re:  #147
