### ISSUE TITLE
No link for Hallucination (Mass) feat

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#132]
The site doesn't have a link for the `Hallucination (Mass)` feat. 
In the [Feat](http://www.openlegendrpg.com/feats) page the link listed in the 'View this Feat' button is [http://www.openlegendrpg.com/feats/hallucination](http://www.openlegendrpg.com/feats/hallucination).
My personal guess is that the problem stems from the site logic of generating the link removing the parentheses in the name and replacing spaces with underscores as we can see for the `Alternate Form (I - II)` feat which has the link [http://www.openlegendrpg.com/feats/alternate_form](http://www.openlegendrpg.com/feats/alternate_form).
A simple fix would be to rename the feat to `Mass Hallucination`, which also restores the consistency of only have parentheses in the name to list the tier range for feats with multiple tiers (e.g. `Alternate Form (I - II)`).
Otherwise I think there are no short answers than to update the logic of the site.

**Comment by brianfeister** [comment]
Thanks @jcte02 - pretty sure this is #57
