### ISSUE TITLE
Inconsistency with 'Special' note in banes.yml file

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#134]
In the banes.yml file, the 'Special' note is separated from the effect in it's own key.
However, this style is only local to the file and inconsistent whithin it (see `Demoralized`, `Fatigued`, `Immobile` and `Stunned`  bane).
Should this style be applied consistently throughout the file or should the style in the banes.yml file be updated to the one followed by boons.yml and feats.yml (having the special note embedded as html in the effect)?
I have some spare time so I should be able to do the conversion and open a pull request.

**Comment by brianfeister** [comment]
I'm good with moving it to it's own key. Thanks for helping :)

**Comment by jcte02** [comment]
Should I also move it to it's separate key in the boon.yml and feats.yml files?
No problem for helping :) I really like Open Legend and I want it to be great.

**Comment by brianfeister** [comment]
Yeah I guess so... **nervously biting fingernails** hope I don't forget to update all 3 places in my application code 😬

**Comment by jcte02** [comment]
See pull request #137

**Comment by brianfeister** [comment]
Closed by https://github.com/openlegend/core-rules/pull/142
