### ISSUE TITLE
Mini campaign reflects old mechanics. 

### ISSUE THREAD

**Issue by Rgconner** [openlegend/core-rules#135]
"A Star Once Fallen" has old mechanics, like fortitude for wearing armor and calculating defenses, etc. 

Yeah, I know, a little vague, but there is a lot more than I could get in one post. =)

**Comment by Odog4ever** [comment]
@Rgconner 

This is a known issue. 

It's possible a large errata section could be added in the future (along) with a big warning that the rules are evolving/work in process.

**Comment by brianfeister** [comment]
Thanks guys. LOTS of work on my plate, appreciate the patience and the bug report.

**Comment by istabosz** [comment]
@brianfeister Thinking we can mark this sucker done now?

**Comment by brianfeister** [comment]
Yup
