### ISSUE TITLE
Light boon only has 5 power levels, while darkness has 9.

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#14]
Was this intentional or an oversight? Kinda seems like they would be mirror images of one another.

**Comment by DMsShadow** [comment]
That would make sense to me too, if they both had the same levels.

**Comment by brianfeister** [comment]
LOL! This is one of those "yeah, I definitely added these at different times and forgot to make them match" things. That or I was falling asleep at my keyboard.
