### ISSUE TITLE
Craft Beneficial or Baleful Item, Sustain Persist boons.

### ISSUE THREAD

**Issue by Elvenoob** [openlegend/core-rules#143]
http://www.openlegendrpg.com/feats/craft_beneficial_or_baleful_item

I was reading this whilst planning my new Witch character, and I hit a small snag, which is namely, the 1/Hour invocation of permanent items, which I found a little odd, particularly since there's no way to reduce it except make more items and rotate uses...

Although, whether or not that gets in the way of this specific character depended on "Sustain Persists".

A creation 5 witch pouring all level 1 feat points into Craft Beneficial or Baleful item can make herself a broomstick, however... When one activates said broomstick... Who's doing the sustaining of this "Sustain Persists" boon? 

I think this'd need clarification, and possibly even something you could distinguish between the tiers of the feat (For example, Tier 1, you need to sustain it yourself, and tier 2, the item is the one sustaining the boon itself)

**Comment by raihje** [comment]
Considering the cost (attribute + feat + extended period of time) I'd say the object sustains the boon at whatever PL it's capable of with the attribute imbued into it.. Although that might seem a bit strong splitting it into tiers seems.. excessive.

**Comment by Elvenoob** [comment]
I would agree with that, just offering suggestions.

**Comment by brianfeister** [comment]
Sounds good. I think we are on the same page, but I would say that (and this will come into play when I write the expanded rules for extraordinary items and also mounts / vehicles) that you spend your sustain action, but use it's attribute. So most items still require a wielder to function (being exempt would be a special / rare property of sentient items), but the item is treated as the invoker, while the wielder is the one expending their Sustain minor action.

**Comment by Elvenoob** [comment]
I don't think that would be the best idea, combined with the hour time limit on recharges, though.

Using the Witch character as an example, under this ruling combined with the existing 1-hour rule, the Witch would simply cart around a couple of brooms, or "one broom" which is actually made from three intertwined brooms, to get around the hassle of the 1-hour recharge timer, but still allow her to stop flying and use other buffs on allies.

Sure, I understand the origin of that one-hour rule, the need to prevent the spam of basically free heals/regens/buffs, but... I dunno... If that's limited by the user's sustain minor action, is the hour really necessary alongside that?

(For example, I know Creation > Craft Magic Item II is a **lot** more versatile, but boon focus (Heal) II characters (Same feat point total, 6), heal twice as much in one round, using both a major and a minor to cast Heal, possibly on different targets.)

**Comment by Elvenoob** [comment]
(Oh, and congratulations on that 110, 630 on the kickstarter, I could only throw $5 in for... IRL reasons, but it's awesome to see a result like that...)

**Comment by brianfeister** [comment]
Thanks for the kind words @Elvenoob ;)
