### ISSUE TITLE
Supernatural Action Rolls with Attribute Zero

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#146]
@istabosz I'm **certain** that we've resolved this elsewhere, but can't remember where it is in the text. If it is indeed not there, we definitely need to address this, it's been asked quite a bit:

https://openlegend.mightybell.com/posts/957901

**Comment by DukeAnax** [comment]
Well I double checked all the likely places. Couldn't find it either.

It's not in chapter 1 when picking the attributes for the Character. Not in chapter 2 when making an action and not in chapter 6, neither when describing which attributes are suitable for attack, nor when actually making an attack.

**Comment by brianfeister** [comment]
As I suspected. I'm leaving it to @istabosz to make the change.

**Comment by jcte02** [comment]
@istabosz Opened #149 as suggestion for where to insert the note.

**Comment by istabosz** [comment]
I've added notes to the two most logical places. Chapter 1 when the attributes are introduced and chapter 6 when discussing damaging attacks. Once I finish the big addition to chapter 2, I'll probably mention it there as well.

**Comment by brianfeister** [comment]
@istabosz re-opening because we need to add this to the SRD as well. Also, I think my caveat below should also be there -- "You can't reduce your Disadvantage below 1 by things like multi-targeting if you have a 0 attribute" ... feel free to rephrase or object.

```
If you have an attribute score of zero, you cannot have Advantage or Disadvantage greater than 1. If another ability allows you to trade disadvantage for some benefit (like multi-target attacking), then you can only perform the action if your total Disadvantage would be 1 or less.
```

**Comment by istabosz** [comment]
@brianfeister Are we getting our streams crossed here? This issue is related to supernatural attributes of zero. You're referring to adv/dis. with ANY attribute of zero.

**Comment by brianfeister** [comment]
Yeah sorry, don't worry about me, I'm just losing my mind.

**Comment by brianfeister** [comment]
Fixed in https://github.com/openlegend/core-rules/commit/7e8d477c9cd4041c26139c1812db71c14035410b. Leaving open due to `SRD Update`

**Comment by ucffool** [comment]
@brianfeister Close (also there are a bunch of _SRD-Update_ tagged issues that can now be closed thanks to @jcte02 's awesome work)

**Comment by brianfeister** [comment]
👌
