### ISSUE TITLE
Website not updating?

### ISSUE THREAD

**Issue by DukeAnax** [openlegend/core-rules#150]
I thought I read before that the website updates itself regularly. However the Barrier boon: [#115](https://github.com/openlegend/core-rules/issues/115) stil hasn't made it there.

Obviouskly not sure how the system works, but I thought I point it out in case something got stuck.

**Comment by brianfeister** [comment]
Nope, the website doesn't update automatically, which is for the best for many technical reasons.

I am drowning in work on my to-do list and have my full-time day job to attend to. I'll update it as soon as things are in order and the various code changes I need to make are in place.
