### ISSUE TITLE
Well Rounded feat wording

### ISSUE THREAD

**Issue by Th3Way** [openlegend/core-rules#155]
The wording for well rounding doesn't state that it grants advantage. It reads as though it adds an extra d20 to the roll.

**Comment by Elvenoob** [comment]
> roll an additional d20 and keep the highest of the two d20s.

I think that wording is fairly clear as-is, and needs to be there to distinguish it from normal advantage where you re-roll attribute dice...

**Comment by Th3Way** [comment]
That isn't the intention. Brian said it is to be advantage. Rolling an extra d20 makes it very powerful. To the point that a 1 stat with an 2d20 drop the low out performs a 4 stat on average.

**Comment by Elvenoob** [comment]
I haven't seen any mention of changing it to regular advantage, although, I guess it would make sense, since the 2d20, keep the highest, was originally from when the feat only applied to zero stats.

**Comment by Elvenoob** [comment]
Yeah, just a little bit broken

It's going to be an interesting comparison with Skill Specialization, but I guess that always has multiple tiers and you can apply it to higher attributes, so they each have their own place in character builds, although I could also see them working together really well.

**Comment by Th3Way** [comment]
I would be curious about the interaction. Also well rounded keeps you out of a lot banes and boons. Also because the plentifulness of attribute points it scales off as levels are gained.
Advantage 1 for 0,1, and 2 seems just fine

**Comment by istabosz** [comment]
While we're at it, we should also probably clear up the wording so that "non-attack" is "non-combat" or otherwise makes it clear that this feat doesn't apply to bane or boon invocations.

**Comment by Th3Way** [comment]
Good catch on that one

**Comment by istabosz** [comment]
@brianfeister Just waiting for you to chime in on this one to confirm that this is a change you had discussed elsewhere and want implemented, as I missed out on that conversation.

**Comment by brianfeister** [comment]
Oh I didn't realize. Yes, this happened because the feat was created in the prehistoric times of "before we knew what to do with Advantage1 and Attribute 0". So now that it's been decided, it should just be Advantage 1.

**Comment by istabosz** [comment]
@brianfeister Revised. Leaving issue open until it's reflected in the SRD.

**Comment by brianfeister** [comment]
props @jcte02
