### ISSUE TITLE
Roll First, Describe Second

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#156]
I think we should talk about this in the Core Rules text somewhere. Some people are used to describing their action and then rolling, I think with the Open Legend mechanics, the general gist should be declared just mechanically and then the effect described afterwards since it could range from a catastrophe all the way through a one-shot kill.

**Comment by brianfeister** [comment]
@istabosz - is this too micro-manage-y? I think we need to start get slightly more hand-hold-ish as we broaden our audience and begin to see players that some things aren't obvious to people.

**Comment by DukeAnax** [comment]
I think this is general roleplay advice that doesn't necessarily belong in the Core _Rules_ of a System.

Also I think most of the time it is rather Describe, Roll Describe anyway.

For example:
"Durak rushes forward and swings his sword at the orc in front of him" Roll result is 11 "The orc tries to block his attack but Durak manages to cut his hand, which causes the orc to drop his axe"

**Comment by istabosz** [comment]
It's not exactly micro-managey, but I think it's unnecessary. The way it plays out varies depending on the situation, but I think that @DukeAnax makes a good point that the general order is Describe, Roll, Describe most of the time, which is pretty common in RPGs.

I don't think OL is really Roll first, describe second. It would be that if you didn't have to state before the roll what boon, bane, or attack you were making.

**Comment by brianfeister** [comment]
Fair enough. I'll close it in that case. I was getting a bunch of thoughts out when I had them, I thought some of them were less awesome than others.
