### ISSUE TITLE
Massive Audit of Example Flavor text

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#157]
A recurring theme is people saying that the system appears to accommodate only fantasy. We need to do a massive audit of all the genre-implicit flavor text and put a bunch of it on the chopping block to designate for replacement by other genres.

**Comment by istabosz** [comment]
Makes sense. This is something I've been actively doing sense we made the decision to be more explicit about open genre, but you're right there is a ton of old stuff that needs updating.

I'll get on it.

**Comment by istabosz** [comment]
Update: I've added variety to the intro and chapter 1.

Chapter 1 will also look a lot better once we add example characters from other genres. @brianfeister Do you think it would be cool to use builds from the character creation contest? Just a thought.

**Comment by OneEyeRob** [comment]
https://trello.com/b/ov5eMU0c/ol-multi-genre-support is available for a full Boon/Bane/Feat+ Audit of genre support + keyword identification

**Comment by brianfeister** [comment]
@OneEyeRob - I think those checklists on your Trello board need to be labels instead (I forget what the limit is on number of labels in Trello) if we're going to make use of that Trello board -- it needs to allow me to filter on genre and see all of the items that apply. Otherwise, the spreadsheet would be better for this purpose

**Comment by OneEyeRob** [comment]
I distilled the "genres" to a mechanical 3 types High magic/High tech, Low magic/Future tech, and No Magic/<= Modern tech.  I think that every genre fits fairly into on of those categories.  That way we aren't trying to get literally every genre. What dyu think?

**Comment by brianfeister** [comment]
Seems reasonable. That didn't show up on my phone. I'll follow up but yeah it'll be good to treat conversations modularly on a per item basis. Thanks!

**Comment by OneEyeRob** [comment]
This might actually be two separate issues btw.  the Mechanical Application to Multiple genres (1)  and the Flavour Text Multi-Genre Examples (2)

**Comment by brianfeister** [comment]
Fair point

**Comment by brianfeister** [comment]
The Trello board needs me to be added as a member to edit `Public. Anyone can see this board, but only members can edit`

**Comment by istabosz** [comment]
Update: I've just added more genre variety to ch. 2

**Comment by istabosz** [comment]
Update: Added variety to ch. 4

**Comment by istabosz** [comment]
Update: added variety to ch. 5

**Comment by istabosz** [comment]
Update: added variety to ch. 6 (didn't need much though)

**Comment by istabosz** [comment]
Update: Added variety to ch. 7
