### ISSUE TITLE
Haste boon is crazy OP

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#158]
**Current rules text:**

* Power Level 2 - The target's speed is increased by 5'.
* Power Level 4 - The target's speed is increased by 10'. Attacks against the target’s Evasion defense suffer disadvantage 1.
* Power Level 6 - The target's speed is increased by 15'. Attacks against the target's Evasion defense suffer disadvantage 2. The target gains an extra major action every round.
* Power Level 8 - The target's speed is increased by 25'. Attacks against the target's Evasion defense suffer disadvantage 3. The target gains an extra major action every round.

**Proposed fix:**

* Power Level 2 - The target's speed is increased by 10'.
* Power Level 4 - The target's speed is increased by 15'. The target gains +2 to their Evasion defense.
* Power Level 6 - The target's speed is increased by 20'. The target gains +4 to their Evasion defense. The target gains a total of one extra major action. If the chosen action requires a roll, it suffers disadvantage 2.
* Power Level 8 - The target's speed is increased by 30'. The target gains +6 to their Evasion defense. The target can take a total of one extra major action or two. If the target takes one extra major action, this action incurs disadvantage 2 if it requires a roll. If it takes two extra major actions, each of these actions incurs disadvantage 4 if it requires a roll.

**Comment by Elvenoob** [comment]
Definitely less broken, particularly when a character runs Boon Access/Focus on it to auto-invoke it at Power level 6 by the time they hit level 2.

(I mean, sure, it's basically that character's whole thing at that point, but it's a damn good "whole thing")

That Power Level 8 was surprising though, I was expecting that disadvantage from PL6 to go away, but instead... I think I kinda like what's here a bit more...

**Comment by DukeAnax** [comment]
@Elvenoob Exact same thought.

It's betetr because this is a Boon, if Power 8 would remove the disadvantage it'd become equal to the Multi Action Feat.

**Comment by istabosz** [comment]
I'm thinking the Evasion bonuses get a bit too high. Just because we don't have any bonus categorizing in the game to prevent stacking from multiple sources.

Also, we should compare these to the bonuses provided by Resistance boon:

What if we make the evasion bonuses +2, +3, +4?

**Comment by brianfeister** [comment]
Agreed @istabosz, let's make it +2, +3, +4

**Comment by istabosz** [comment]
Updated in the rules. Leaving open for SRD change.

**Comment by brianfeister** [comment]
props @jcte02
