### ISSUE TITLE
What happens when my attack is exactly the target's defense

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#160]
I've been telling people that it's GM's discretion what to do in that situation, and sometimes I treat it as the rare exception where I take a break from coming up with "twists" when I'm running, but we probably need a better official ruling.

**Comment by DMsShadow** [comment]
It actually hasn't come up yet in my games, but had been trying to work out how to rule it. Was leaning towards success with a twist.

**Comment by brianfeister** [comment]
That's probably the best thing, if we do that, we just need to to tweak some wording to specify something like 

> If your attack is equal to, or lower than the target's defense, it's a success with a twist

**Comment by Hassurunous** [comment]
This is how I have been playing it. At first I just counted it as a 0-damage attack, which could still apply a poison on a weapon or something like that, but it didn't make much sense to me, so I've just be playing it as a "success with a twist".

**Comment by istabosz** [comment]
I've added text to make damaging attacks that equal the defense to be interpreted as success with a twist. Updated in SRD as well.
