### ISSUE TITLE
Correction: Interrupt > Defend > Example

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#164]
core > combat > Interrupt > Defend > Example

**Reads as follows:**

> Vera is nearing death when the River Troll lunges at her. The troll rolls a 23 against Vera’s Toughness of 17, so she uses a defend action to catch the troll’s arms before he can rend her to death. Vera makes a Might roll and gets a 20, so her roll replaces her Toughness, causing her to suffer 3 points of damage instead of 6. Because defend is an interrupt action, when Vera’s turn in the initiative comes, she does not get a major action.

**Corrected version:**
> Vera is nearing death when the River Troll lunges at her. The troll rolls a 23 against Vera’s ~~Toughness~~ Evasion of 17, so she uses a defend action to catch the troll’s arms before he can rend her to death. Vera makes a Might roll and gets a 20, so her roll replaces her ~~Toughness~~ Evasion, causing her to suffer 3 points of damage instead of 6. Because defend is an interrupt action, when Vera’s turn in the initiative comes, she does not get a major action.

A similar edit goes to the second example as well.

**Comment by istabosz** [comment]
Good catch. I've fixed it. @brianfeister Leaving this issue open until it's reflected in the SRD.

**Comment by ucffool** [comment]
SRD doesn't contain any of the examples, so not sure this should still be open or flagged SRD update (unless there is a non-public SRD)?

**Comment by brianfeister** [comment]
Thanks @ucffool closing.
