### ISSUE TITLE
Clarify relationship between XP system and "GM decides when you level up"

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#165]
This should probably just say something like "The GM decides when to award XP, and every 3 XP you receive results in a new level."

> Open Legend uses a very simple method of determining when players level up: the GM...it also saves overhead time on tasks like calculating XP totals

**Comment by istabosz** [comment]
Clarified. Also cleaned up that section a bit in general.

**Comment by jcte02** [comment]
@brianfeister This issue can be closed.
