### ISSUE TITLE
[Clarification] Combat > Make a damaging attack > Determine Target(s)

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#166]
The point of contention is the use of the term *multi-**attacks*** rather than  *multi-**target***.

Due to the term multi-attack being part of a Feat, using it here leads to confusion.

Section:

> Melee Multi-Attacks
You may target any number of foes that are within your reach. When targeting more than one foe, you suffer disadvantage equal to the number of foes targeted (2 targets = disadvantage 2, 3 targets = disadvantage 3, etc.)

>Projectile Multi-Attacks
You may target up to five foes that fall within a 25’ square. When targeting more than one foe, you suffer disadvantage equal to the number of foes targeted, as with melee attacks.

**Comment by brianfeister** [comment]
Great catch, thanks!

**Comment by istabosz** [comment]
Fixed. Leaving open for SRD revision.

**Comment by jcte02** [comment]
@brianfeister This issue can be closed.
