### ISSUE TITLE
[Consistency] Rename Feat: Hallucination (Mass)

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#167]
[Hallucination (Mass)](http://www.openlegendrpg.com/feats/hallucination) breaks the naming convention by being the only feat using parenthesis for a *variation on a theme*. The standard variation should be **Hallucination - Mass**, to match with *Battlefield Punisher* variation styling.

Parenthesis are used in every other feat to identify multiple levels.

New title: **Hallucination - Mass**

**Comment by brianfeister** [comment]
Good catch. Thanks!

**Comment by brianfeister** [comment]
Props to @jcte02 for fixing.
