### ISSUE TITLE
Ageless Feat

### ISSUE THREAD

**Issue by Th3Way** [openlegend/core-rules#169]
The current requirements are way too steep compared to the return. This feat will more often than not be a fluff feat than see actual usage. I recommend removing the requirements completely.

**Comment by Elvenoob** [comment]
I definitely agree with this as a minimum, or even porting it over to the Perks section. It's just not on the same level as even some of the feats with no pre-requisite.

**Comment by Odog4ever** [comment]
@Elvenoob  Ageless definitely fits in better with the Perks due to it's niche nature and lack of mechanical "oompf"

**Comment by brianfeister** [comment]
I agree that we should move it to perks

**Comment by istabosz** [comment]
Just removed it as a feat and added as a perk. Leaving open until edited in SRD.

**Comment by brianfeister** [comment]
props @jcte02
