### ISSUE TITLE
Craft Beneficial or Baleful Item: Learning Pre-Requisite

### ISSUE THREAD

**Issue by Elvenoob** [openlegend/core-rules#170]
Re-reading this feat, the limiting of Learning to only physical attributes didn't really make sense to me, in a sci-fi setting, Learning would easily be able to create any of the... (Extraordinary, are we calling them now?) effects, and that's justifiable in a fantasy setting too, in that, a person with no innate magical ability can still create magical effects through use of the proper rituals, reagents, alchemical processes and such.

Again, my example goes to the Bartimaeus series, in which, the humans summoning the spirits from their home realm of existence have no magical power of themselves, but yet the ritual circles they draw, along with the true names of the spirits, and other incantations to tie the two together, still have the ability to summon, trap, and force the spirit inside them to obey the instructions given to them by their summoner.

**Comment by brianfeister** [comment]
Lol, you drive a hard bargain, but I suppose we can do that.

**Comment by Elvenoob** [comment]
Umm?

**Comment by Elvenoob** [comment]
I drive a hard bargain? Umm..?

**Comment by Rgconner** [comment]
So this would be like ritual magic?

**Comment by Elvenoob** [comment]
Nope? 

I'm talking about opening up Learning's effect on the magic item crafting feat to allow it to access all the attributes to allow for the use of "Extraordinary" attributes, because it makes sense flavour wise.

(And, gives a boost to an attribute which others might overlook.)

@brianfeister While we're here, with the 20 items per character thing, how would stacks of, say, enchanted arrows or healing potions work, would each item take up a slot, or would it be, 1 quiver with 4 flaming arrows/one pouch with 3 healing potions, etc?

**Comment by brianfeister** [comment]
I would treat the quiver as the enchanted item that gives a bonus to it's ammunition since Open Legend doesn't track ammunition. Still thinking about how ammunition will interact with multi-genre weapons and stuff. It's not final yet.

**Comment by Rgconner** [comment]
Elvenoob. I must be dense here, because I am not getting it.

You want learning to allow you to make baneful/beneficial items? Sort of like Creation is now, where it can make them from any Supernatural aspect?

Not saying yes or no, just trying to understand.

**Comment by brianfeister** [comment]
That's right. The concept is that you can study and learn a ritual via intellect only (as magic is sometimes portrayed). Also (and more importantly, in my opinion), Sci-Fi / futuristic tech should be able to create lasers, for example (Energy attribute), but not require a supernatural Creation attribute in order to build one. 

I will say that I think Logic is the better to invent something new, where Learning would be crafting from Blueprints. I would probably handle Learning as a story-only thing where you have to acquire the blueprints first via the story, then just make a regular Learning roll to .... actually wait, no... that doesn't work either. A Learning roll would tell you of the existence of some invention, machine, etc., however assembling it would still require Logic I think, no matter how you slice it.

**Comment by Rgconner** [comment]
So would learning be able to unlock Ritual Magic feat?
Just thinking here, I think it could.

**Comment by Rgconner** [comment]
So here is a thought: Could you use Learning to do the reverse of Attribute Substitution and use your Logic score to link to a Supernatural attribute?

The idea being you learned it, not a natural ability.

**Comment by EliManthey** [comment]
@Rgconner that would be an interesting take on the traditional learned and practiced wizard as well as all magic in open legend currently is pretty "sorcerous".

**Comment by OneEyeRob** [comment]
@EliManthey I think it would allow for some more uses for Logic and Learning than they currently have as well.  Two thumbs up from me.  "Logic and Learning may be Attribute substituted for Extraordinary Attributes". could be added to the description.

**Comment by brianfeister** [comment]
I'm good with it. This is necessary to support futuristic settings where Creation won't be used. So yes definitely

**Comment by brianfeister** [comment]
Not sure about your caveat Richard, I think we just need Creation, Learning, Logic, and the others already there listed as optional prerequisites

**Comment by ucffool** [comment]
Need to address this in the new Feat structure; now is the time.

**Comment by brianfeister** [comment]
This is fixed.
