### ISSUE TITLE
[Website]Boons Description > References banes

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#172]
At the top of the Boons page is a reference guide for what each section of a Boon means. However, it's a rough copy/paste from Banes and thus still has references to:
* bane
* inflict / inflicted

These should be replaced with:
* boon
* invoke / invoked

for consistency.

**Comment by brianfeister** [comment]
I'm actually unclear on this one @ucffool, because I thought I remember that we use "invoke" for both banes and boons in order to prevent precisely this problem, LOL. Can you point to any text that confused you?

**Comment by ucffool** [comment]
http://www.openlegendrpg.com/boons 

Expand the explanation, then find on page the word bane and the word inflict. You'll notice they are both our of place as this is the boons page. Replace them with the words as noted in the first comment.

**Comment by brianfeister** [comment]
Gotcha, I misread your comment.

**Comment by ucffool** [comment]
FYI, I just double-checked and this is purely website. **SRD** and **01-chapter-five.md** are both correct.

**Comment by brianfeister** [comment]
Fixed. About to deploy.
