### ISSUE TITLE
[Correction] Feats > Marksman

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#175]
Current Effect text:

> Choose a ranged weapon. In your hands, the range of that weapon is increased by 5 squares.

Suggested change:

> Choose a ranged weapon. In your hands, the range of that weapon is increased by 25 **feet**.

Bring it inline with current use of feet rather than squares.

**Comment by brianfeister** [comment]
I think you're a developer right Mario? Just FYI these things would be even easier for me if they were submitted as pull requests

**Comment by DukeAnax** [comment]
Just note that 5 squares would be 25 feet.

**Comment by ucffool** [comment]
edited!

**Comment by ucffool** [comment]
Forked > fixed > pull request sent.
