### ISSUE TITLE
Add "Enhance" boon?

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#180]
### Enhance

**Duration**: Sustain Persists
**Invocation Time**: 1 Major Action
**Power Level**: 1 - 9
**Attributes**: Alteration, Creation

**Description**: You bolster and empower your target by making them more competent than they normally are, granting the sight of an eagle, the problem solving skills of an elite computer hacker, or the social grace of a trained courtier

**Effect**: Choose a physical, social, or mental attribute. You can voluntarily reduce the invoking attribute score for the duration that you sustain this boon to augment the target's chosen attribute by a number of attribute points you have sacrificed. The target's modified attribute score cannot exceed your invoking attribute score, unless they are equal before invoking this boon. If they are, you can reduce your invoking attribute to zero in order to increase the target attribute by 1. In this scenario, the raised attribute score is used only for the purpose of determining attribute dice, but remains unchanged for all other purposes.  **Example**: Phantom channels the power of a neural network of nano computers to enhance her Logic attribute when attempting to brute force her way into a datacenter she's been hired to breach. The nano computers typically give her a Creation score of 5 and her Logic is also 5. For this difficult task, she devotes all of the resources of these nano computers to enhancing her intellect, reducing her Creation attribute to 0, while her Logic attribute is raised from 5 to 6, but this effects only the attribute dice she rolls.

**Comment by brianfeister** [comment]
@istabosz let me know what you think. I was having a conversation with @EliManthey on another thread and realized that it would be too overloaded to add an "alternate mode" on top of Shapeshift, but it seems that this type of thing is needed. We had it with the previous "Alternate Form" but it probably should be available via Alteration / Creation directly without needing to take a feat for accessing it. We don't always do "downsides" to boons, but this seemed appropriate as a limiting factor since augmenting an attribute is so powerful.

**Comment by infernodemon2005** [comment]
when I first started with the system, the alternate form feet was exactly what I was looking for to symbolize the transformation ability of my custom race, but when the alternate form feet was changed, it no longer met what I was looking for. I thought about something similar to this but it was tied to a feet and allowed for some alternative atributes like will, presence, and energy to be used to do this, at the trade of levels of exhaustion. haven't finalized the homebrew feet yet, and if something like this gets introduced, I won't need to lol

**Comment by brianfeister** [comment]
Not quite @Rgconner, this increases your attribute score, which for many people creates a very different flavor / feel to the game. Also, to counterbalance the instantaneous vs. ongoing duration this boon lowers the invoking attribute for the duration, so it involves sacrifice.

**Comment by Rgconner** [comment]
@brianfeister Ok, I just look at it and I see adding a Boon that could be rolled into an existing boon, but if you think there is enough distinction to the difference, then add it.

**Comment by brianfeister** [comment]
It was a good question :) ... I almost made it much more similar to Aid and then realized I needed to make sure it was different and that the goal was different. With `Enhance` you can take a Perception score from 0 all the way to 5. That doesn't happen with Aid. It **kind of** happens with Shapeshift, but the problem is that I didn't want to add even more complexity with an "alternate mode" to Shapeshift because it's already too complex.

**Comment by infernodemon2005** [comment]
this would allow to take a feet per say that would allow you to enhance multiple attributes at once and perhaps have a drawback of exhaustion. the indomitable endurance feet currently has little use outside of the berserker line, sort of looking for ways to make it more viable as an option

**Comment by brianfeister** [comment]
@infernodemon2005 hmmmm.... that seems problematic because once your attribute score is zero it can't go any lower. I think it's good as is, since you can take **Superior Concentration** to invoke it multiple times, each time distributing only some of your total invoking attribute score.

**Comment by infernodemon2005** [comment]
perhaps a master of enhancement that lets you spend this total and split it up amoung the attributes instead of having to cast in multiple rounds, having a feet that would let you devide the spent score between two attributes and for each tier of the feet, adding an additional attribut up to 4-5 that you can devide these points between at one time instead of multiple invocations.

**Comment by brianfeister** [comment]
Yeah, maybe at Attribute 5 you can split among two, Attribute 6 among 3, etc.

**Comment by EliManthey** [comment]
So if I am reading this correctly you could enhance your fortitude at first level to 5 with your alteration. Would you per say gain hit points? What does this affect? Does it change bane or boon prerequisites if it is within the possibility of your level?

**Comment by brianfeister** [comment]
The goal is to keep it straight forward, so the change affects everything it would normally effect. I suppose we could add a caveat to feats that specifies that anytime you don't meet the feat prerequisite you cannot benefit from the feat

**Comment by EliManthey** [comment]
Sweet...I like it

**Comment by brianfeister** [comment]
This proposal doesn't cover something thematically important: taking my zero perception and raising it to 3 or 4. That's why I introduced the penalty. Because you aren't bestowing much competence with your proposal. I had in mind that this was the way to give a blind character the vision of an eagle. Going form 0 to 3 would be easy but 4 to 5 might be harder

**Comment by infernodemon2005** [comment]
I personally like this, however I feel we might be able to do this with energy as well, as in taking in the energy of a given element in order to temporarily enhance certain physical attributes at least.

**Comment by EliManthey** [comment]
I like that from a A:TLA campaign perspective.

**Comment by DukeAnax** [comment]
istaboz is right in that this breaks heavily from the regular boon structure. I wonder if this should be a feat instead? This reminds me heavily of Attribute Substitution.

**Comment by brianfeister** [comment]
@istabosz one of the motivating factors here is the unusual aspects of age that makes it instantaneous. When I think back to First writing the Aid boon, I think what happened was I Was preparing for it to be augmented with Boon focus 2 and the behavior of the boon got molded by an assumption that a bard type character would invoke it each round as a support. I think this is a Remnant from the time when there was still a push to have more specific and strongly thematic feats. There was a feat meant for Bard's that gave out bonus D4 or something like that.

Anyway, long story but the point is I suppose we should just merge the ask from this spoon with age and probably rename it. Aid could become Bolster, make it sustain persists to accommodate the ongoing non instantaneous effect, and then it can serve about more varied themes:

Bard song, partial shapeshifting, divine might, fortifying nanites, drugs that enhance your intellect temporarily, etc.

**Comment by DukeAnax** [comment]
@brianfeister are you using auto correct? because a lot of that makes no sense to me.

**Comment by DMsShadow** [comment]
I thought autocorrect gobbledygook was my thing. I think we can safely assume 'age' is aid, though we may need to clarify what merging the 'ask from the spoon' is. That's a new metaphor on me.

I think though @brianfeister is suggesting to merge the two together and make aid into 'bolster' making it a sustain persists instead of instantaneous and then it will cover the scenarios above. Is that right?

**Comment by EliManthey** [comment]
I gotta say I'm gonna start using the term "spoon with age" now.

**Comment by brianfeister** [comment]
LOL

> we should just merge this boon with Aid and probably rename it

**Comment by infernodemon2005** [comment]
what would the merged boons look like?

**Comment by brianfeister** [comment]
I think it would just be like this (replacing the current **Aid** boon)... this involves me recanting everything I said about raising attribute scores. That can done via the new Alternate Form, so I think @istabosz is right, adding another avenue to twist the min-max dials for modifying attributes is probably a slippery slope.

----

#### Bolster

**Duration**: Sustain Persists
**Invocation Time**: 1 Major Action
**Power Level**: 3/ 6/ 8
Attributes: Alteration, Creation, Prescience, Presence

**Description**:
Your bolster an ally's chances of success via inspiration, augmentation, divine blessing, or supernatural insight. Your target becomes more competent than they normally are. You might grant the sight of an eagle, the problem solving skills of an elite computer hacker, or the social grace of a trained courtier.

**Effect**:
Choose a physical, social, or mental attribute. The target gains advantage on their action rolls according to the Power Level of the boon. 

* **Power Level 3** - Advantage 1
* **Power Level 6** - Advantage 2
* **Power Level 8** - Advantage 3

**Comment by DukeAnax** [comment]
So basically just changing Aid from instaneous to sustain persist.

As for your original idea I don't think minmaxing was so much the issue, but more fundamentally, attributes would have stopped mattering entirely. You could just have one switching attribute and then get whatever attribute you need.

I think you just managed to break your own system harder than any of my ideas ever did (;

**Comment by brianfeister** [comment]
@DukeAnax - the `Bolster` boon above is a proposed merge of `Aid` and the idea of `Enhance` which began the thread. I'm proposing that as  single boon rather than two separate ones so it's pretty conservative in terms of mechanical impact, and of course boons don't stack.

**Comment by DukeAnax** [comment]
Well I'm just saying that aside from the sustain the mechanical impact of your merge is actually identical to the Aid boon. From the idea of Enhance isn't much left except the flavour text.

Also I don*'t think it adresses the reason you started the thread in the first place: Partial Transformation. The idea behind raising attribute is that they could do stuff they couldn't do before, while advantage just makes them better at the things they already do.

How about bringin in @istabosz more conservative version of enhance? Like this:

Bolster

Duration: Sustain Persists
Invocation Time: 1 Major Action
Power Level: 3/ 6/ 8
Attributes: Alteration, Creation, Prescience, Presence

Description:
You bolster and empower your target by making them more competent than they normally are via inspiration, augmentation, divine blessing, or supernatural insight. You might grant the sight of an eagle, the problem solving skills of an elite computer hacker, or the social grace of a trained courtier.

Effect:
Choose a physical, social, or mental attribute. The target gains an increase to the chosen attribute according to the Power Level of this boon. This boon can not raise the target's attribute beyond the value of your invoking attribute, or if it start out equal, youc an raise it by one. If you cannot raise the attribute any further, you can raise advantage instead.

    Power Level 3 - +1
    Power Level 6 - +2
    Power Level 8 - +3

**Comment by brianfeister** [comment]
@DukeAnax - just some crossed wires. I'm not proposing to add an `Enhance` boon at all. That's what I've been trying to explain.
