### ISSUE TITLE
Multi-Genre Mechanics Audit

### ISSUE THREAD

**Issue by OneEyeRob** [openlegend/core-rules#184]
Specifically Boons, banes, Feats.
Related to https://github.com/openlegend/core-rules/issues/157, but a separate issue.  Other one refers to flavour text, this relates to losing applicability of a significant percentage of Boons, Banes, and Feats when moving genres.

Boons, banes, and Feats broken out on the below trello, and/or google doc at brian's discretion.

https://trello.com/b/ov5eMU0c

https://docs.google.com/spreadsheets/d/16MN6W1BKvX-g-RvufpBQW-W4VX-Niaw1Wj_JEAyu_ug/edit#gid=0

**Comment by OneEyeRob** [comment]
How do we want to note the mechanical cahnges for this issue? One at a time? En masse?

**Comment by brianfeister** [comment]
You could just use a Github checklist  in this issue that we can copy into the code change Pull Request

* [ ] change 1
* [ ] change 2

**Comment by brianfeister** [comment]
@OneEyeRob what's the status on this? I'm still open to tweaks and rewording for any issues you find. Many of the issues you discovered have been addressed with Core Rules modifications. Can you give a summary of anything else you might have found that seemed problematic?

**Comment by OneEyeRob** [comment]
Many of the issues have been fixed,  I am going to try to go through and identify which have been fixed by those changes, and which might still have wording errors.

**Comment by OneEyeRob** [comment]
This appears to have been mostly fixed in the individual rules, and they are written to apply in a broad range of scenarios.  So this can be closed.

**Comment by OneEyeRob** [comment]
This puppy has been thrashed
