### ISSUE TITLE
Combat Momentum & Combat Follow Through/Defining a free action

### ISSUE THREAD

**Issue by EliManthey** [openlegend/core-rules#186]
https://openlegend.mightybell.com/posts/974912.

Basically it came up that free action should be defined in RAW even though it only applies to a few feats right now.

**Comment by BuildAndDie** [comment]
Purposed word changing:

Combat Follow-through

Effect

Any time you make a Forceful (Might) or Precise (Agility) attack that reduces a foe to zero hit points or less, you may immediately make an extra attack as a free action. This may be combined with Combat Momentum to move up to your normal speed.



Combat Momentum

Effect

Any time you make a Forceful (Might) or Precise (Agility) attack that reduces a foe to zero hit points or less, you may immediately move up to your normal speed as a free action.

**Comment by Rgconner** [comment]
Just a thought: why not combine them into  a single 3 point feat. There is little point in taking one without then taking the other.
