### ISSUE TITLE
Interrupt Action Clarification

### ISSUE THREAD

**Issue by DMsShadow** [openlegend/core-rules#19]
https://github.com/openlegend/core-rules/blame/master/core/src/06-combat/01-chapter-six.md#L361

The description here says "after an enemy has rolled a successful attack against yourself or an ally",

But the continuation here only mentions replacing an allies defense score, not that it can replace your own:
https://github.com/openlegend/core-rules/blame/master/core/src/06-combat/01-chapter-six.md#L362

Can you use it to defend yourself?

**Comment by brianfeister** [comment]
Great question. I would say "yes, you can". Not sure why the continued wording says otherwise... probably connected to some other mechanic I had an idea about at the time.

**Comment by DMsShadow** [comment]
Perhaps need to be changed too:
"If your attribute roll is higher than **the original** defense score, the **recipient** may use your roll in place of **this** defense score."
