### ISSUE TITLE
10 over defense and bane attack clerification

### ISSUE THREAD

**Issue by infernodemon2005** [openlegend/core-rules#194]
as the rules are currently written in the combat section, the effect of exceeding a target's defenses by 10 during a bane attack would still apply a second bane. this is because bane attacks are still considered attacks for the purposes of defend actions and attack specialization purposes. if this is not intentional, I think we should have a clerification added that the ruling does not apply to bane attacks, otherwise you will have a problem with people using a bane attack for forced move, rolling a rediculous number, and then getting to apply knockdown or fear on top of it without a feat.

**Comment by brianfeister** [comment]
Hey @infernodemon2005, need to have the language specifically quoted so that we can know which section you're reading. I know you have low vision, is it possible to copy/paste from the website into this ticket?

**Comment by infernodemon2005** [comment]
it would be this from the exceptional success section under damaging attack:

If your attack roll exceeds the target’s defense by 10 or more, you may apply one bane of a Power Level less than or equal to the attribute you used for the attack. In order to apply a bane, your attack roll must equal or exceed the appropriate defense for that bane. If your attack targeted multiple foes, you may apply the bane to each qualifying target.

combined with the bane attack section:

Instead of attempting to damage a target, you may instead choose to inflict your enemy with a bane. In order to inflict a bane

that being said, without clerification, a person could potentially argue applying exceptional success to bane attacks and pull two banes for the price of one.

**Comment by infernodemon2005** [comment]
granted, to most, common sense would dictate that the two sections are unrelated and exceptional success on a physical attack would not apply to a bane attack, however due to the relation to the two and the example given under the defend action, a person could defend against a bane attack, making it equivalent to an attack. also, attack specialization would apply advantage to bane attacks made with a weapon as well. thus, it is more implied that bane attacks and normal attacks fall under the same rules, thus exceptional success applies to bane attacks also.

**Comment by Hassurunous** [comment]
We were just discussing this in the Discord channel and there are several references throughout the book to "bane attacks", mostly in the feats section, but also in the "Combat" -> "Major Actions" section. Considering these are referred to as "attacks" they could reasonably be assumed to work with the "10 over defense" wording.

**Comment by ucffool** [comment]
I think an easy resolution would be that wherever the text references:

> If your attack roll exceeds the target’s defense by 10

It should be replaced with:

> If your **damaging attack** roll exceeds the target’s defense by 10

The reasoning being that **damaging attack** is the current distinction between the intention of _attack role_ and the hard line between it and a _bane attack_.

**Comment by infernodemon2005** [comment]
this rewording solves this problem.

**Comment by ucffool** [comment]
@brianfeister Close.

**Comment by brianfeister** [comment]
Closed via #204
