### ISSUE TITLE
Clarification on Simple Build NPCs/Monsters

### ISSUE THREAD

**Issue by DMsShadow** [openlegend/core-rules#20]
https://github.com/openlegend/core-rules/blame/master/core/src/07-running-the-game/01-chapter-seven.md#L333

Have to say I love having this section in there now as it will help me plan adventures better. But I wanted some help clarifying a few details.

Here it states that the party's level determines the ability scores, but it doesn't give guidelines around how many NPCs/Monsters per party member. If you see what I mean? (e.g. should it be one monster of party level 1 per PC).

Similarly for the boss later:

https://github.com/openlegend/core-rules/blame/master/core/src/07-running-the-game/01-chapter-seven.md#L404

Though I think that assumes a party of four adventurers.

**Comment by DMsShadow** [comment]
Actually, reading over it again it makes a bit more sense to me now, but I think it's the terms that are throwing me off.

In the build sections we refer to Party levels, but in the Encounter Difficulty section we refer to Monster level.  Would it work better just to use NPC/Monster level?

**Comment by istabosz** [comment]
You caught me! This was one area that I knew would need clarification in the next revision but I had to let it go live as is for the moment just for time's sake.

**Comment by raihje** [comment]
Okay, so quite a bit has been clarified (ie the level budgeting for encounters, which answers the above.) Should this be closed?

**Comment by istabosz** [comment]
I've updated the rules text. Closing this issue.
