### ISSUE TITLE
Resilient cryptic note

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#216]
The effect of this feat reads
> Any time you make a Resist roll, you have Advantage on the d20 roll (roll 2 d20 and keep the higher, contrary to major action rolls)

What is the meaning of
>contrary to major action rolls

What is the contradiction to which it refers?

**Comment by Elvenoob** [comment]
I think it's talking about every other roll in the game where Advantage goes on the attribute dice, but there's no attributes impacting resist rolls (Not sure why but that's the case.)

I'd personally have the actual comparison there;

> Similar to having Advantage when making rolls using an attribute of 0

But that's just me.
