### ISSUE TITLE
Minor Clarification on Craft Beneficial/Baleful Item

### ISSUE THREAD

**Issue by hmack312** [openlegend/core-rules#219]
The question is in regards to invocation times/reagents (if GM's use reagents). Does a magic item crafted through this feat activate all banes/boons as a major action or do boons like animate still take the normal amount of time to invoke through the item? Does a boon/bane invoked  through a magic item still require the normal reagents (if applicable)?

There is no mention in the feat, and I only ask because other TTRPG's that I have played have had magic items ignore the normal casting time and use their own. For example, spell wands in D&D or pathfinder took the edition's version of a standard action to cast said spell regardless of the spell's normal casting time.

**Comment by brianfeister** [comment]
Hey @hmack312, sorry to do this, but as the community grows I need to uphold a standard. Github is not a place for questions, we have a team of moderators on the community site who can answer your question and then escalate it to me and/or Github if it is indeed a rules bug:

https://openlegend.mightybell.com/
