### ISSUE TITLE
What's the difference between PL 7 and 9 Teleport?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#22]
https://github.com/openlegend/core-rules/blob/master/boons/boons.yml#L521

Power Level 9 states that there is no range limit, but PL 7 doesn't actually give a limit. It just says 1 mile per minute of casting time.

**Comment by brianfeister** [comment]
I think the unclear intent about PL 7 is that you can do the same as PL 5, that is, teleport to a place you can't see, except now that place can be miles away. You still get the benefit of being "shunted" out of a mountain for example and being stunned for 1 round.  PL 9 makes it so you no longer simply choose a random direction to go in, and hope for the best, you now have precise control over your arrival destination, which is any place you have ever seen before on the same plane of existence.

**Comment by brianfeister** [comment]
@istabosz feel free to re-open this or make edits to clarify. But maybe the answer to your question is: "There is no limit, the boon can be invoked many times, each time it's invoked, the limit is 1 mile per point in the `Movement` attribute. So, I have `Movement 7`, I spend 7 minutes invoking the boon and then roll, on a success I teleport 7 miles. 

I also realized what you mean about the lack of specified limitation and added text for that. Feel free to let me know or make edits for further clarity.
