### ISSUE TITLE
Need to Update Example Characters to fix Toughness Calculations

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#222]
I was just checking out some of the example characters and realized that they use the old calculations for Toughness, namely that Armor is still factored into Toughness. Since there is only one defense that uses Armor anymore, it might be beneficial to reorganize the sheet a bit as well. I can fix the sheets and submit them later if you'd like.

**Comment by brianfeister** [comment]
👍

**Comment by jcte02** [comment]
@Hassurunous Speed, feats, and attacks should also be updated if you have the time.

**Comment by jcte02** [comment]
What I mean is that speed needs to be converted from squares to feet, feats (e.g. Druid) and attacks (e.g. Arcane Protector) need to be udated to the lastest rule version.

**Comment by ucffool** [comment]
Also, check individual pre-gens for comments. I know I left one on the Assassin.

**Comment by brianfeister** [comment]
Yup, I updated the defenses and speed and passed the task to @Hassurunous to work on the actions / banes / boons in the bottom right

**Comment by brianfeister** [comment]
... oh and feats could possibly be an issue @Hassurunous

**Comment by Hassurunous** [comment]
I'll take a look at all that as soon as I can. Thanks guys!

**Comment by Hassurunous** [comment]
This should be fixed now. I went through and updated them all just a couple weeks back for the latest rules update (as of then). Let me know if you see anything that needs fixed still.

I'll update again after the rules lock if something serious has changed.

**Comment by brianfeister** [comment]
Thanks @Hassurunous !
