### ISSUE TITLE
Feats in Chapter 7 are outdated

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#225]
Some of the feats listed are outdated and need to be updated to the lastest rule version

**EDIT**

To give a sense of what should be changed in Chapter 7 and the corresponding section in the SRD
Most of the work is just a copy-paste from the `feats.yml` file

**Outdated feats:**
- [x] `Boon Focus`
- [x] `Energy Resistance`
- [x] `Evasive Footwork`
- [x] `Lethal Strike`
- [x] `Potent Bane`
- [x] `Resilient`
- [ ] `Superior Concentration` (current version in `feats.yml` is more simpler to understand and also shorter)

**Issues**
- [ ] `Attack Specialization` should mention that you gain advantage only on damaging attacks.
- [ ] `Bane Focus`/`Superior Bane Focus` should say`pick a bane that you can invoke`. Same story for `Boon Focus`.

**Comment by jcte02** [comment]
The paragraph is in Chapter 7

**Comment by Hassurunous** [comment]
I'll add this to the list of updates to the example characters. Thanks!

**Comment by jcte02** [comment]
To give a sense of what should be changed in Chapter 7 and the corresponding section in the SRD

**Outdated feats:**
- [ ] `Boon Focus`
- [ ] `Energy Resistance`
- [ ] `Evasive Footwork`
- [ ] `Lethal Strike`
- [ ] `Potent Bane`
- [ ] `Resilient`
- [ ] `Superior Concentration` (current version in `feats.yml` is more simpler to understand and also shorter)

**Issues**
- [ ] `Attack Specialization` should mention that you gain advantage only on damaging attacks.
- [ ] `Bane Focus`/`Superior Bane Focus` should say`pick a bane that you can invoke`. Same story for `Boon Focus`.
