### ISSUE TITLE
Move "Disease Immunity" from feats to perks

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#228]

**Comment by twystedcures** [comment]
I'm not sure how you envision diseases working. I've been building them as weapons that make various bane attacks, primarily fatigue and sickness bane attacks, a number of times per, hour, day, or week depending on it's power level. 

I could see room for both a feat and a perk, the feat granting general immunity, and the perk granting disadvantage for disease attacks that the PCs have been inoculated against.

**Comment by Th3Way** [comment]
Diseases are currently only existing in the narrative sense. Which is where perk power lies. Feats need to have stronger impact on mechanical effects to be worth while. I'm very much for the move.

**Comment by EliManthey** [comment]
what you are talking about I think @twystedcures is flavoring bane attacks as imbuing a weapon with a disease? what disease immunity is meant for is narrative diseases similar to what @Th3Way is talking about.

**Comment by brianfeister** [comment]
Fixed.
