### ISSUE TITLE
Add "Character Progression" Section or Heading

### ISSUE THREAD

**Issue by mattsayler** [openlegend/core-rules#232]
Relatively small annoyance, and maybe just me: I think the Level Up & Wealth progression info get a little lost in Running the Game. 

The info is of interest to the GM AND players. The way it's organized now feels like it's a bit more of a hunt than it should be for people focused on the PC side of the table. 

I think either creating a separate section or maybe just adding a "Character Progression" heading would help that.

**Comment by istabosz** [comment]
To clarify, do you think that the section at the end of Chapter 1 isn't providing enough information for players? If that's the case, what do you think it is lacking?

The info in Ch 7 is really directed towards GMs as advice for how to award XP and wealth, so I don't see why it should be more focused towards players.

**Comment by mattsayler** [comment]
Wow, nevermind. I don't know how I missed that section. Could have swore I scrolled through that chapter several times looking.
