### ISSUE TITLE
Feat titles: ndash vs - (feats.yml)

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#236]
After playing with some RegEx parsing, I realized that different characters are used in the titles when delineating power levels. Examples:
`Lethal Strike (I – IX)`
`Knowledge (I - III)`

Standardizing them all to use a standard dash "-" is the goal of this issue. Putting it here for discussion before action (if any).

**Comment by brianfeister** [comment]
Sure, standardizing characters is preferable. Very strange how they ended up different but go ahead and PR a fix.

**Comment by ucffool** [comment]
My guess: operating systems. Either way, I'll sync, fix, and pull later.

**Comment by brianfeister** [comment]
Actually I'm glad you mentioned that. If it really is operating system level then you need to handle that in your Regex because we're not going to be able to enforce that level of standardization with upcoming changes.

**Comment by brianfeister** [comment]
Just due to multiple contributors and operating systems. That's a huge maintenance hazard. I mean you can fix it and PR, knowing it'll probably get out of sync right away

**Comment by ucffool** [comment]
Oh I have (I always workaround first, then suggest the fix).
