### ISSUE TITLE
Clarification about Alternate Form feat

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#24]
I'm having a bit of trouble understanding this text:

> While in your alternate form, you can divide your Alteration attribute score amongst your physical attributes.  If your Alteration score is higher than a given physical score, you can raise the physical score to a maximum of your Alteration score. If the physical attribute is higher than your Alteration attribute, you can raise the physical attribute by 1 instead.

Does this mean that you can add your Alteration score to your current physical attributes? Or does it mean that you completely re-assign your physical attributes?

**Comment by brianfeister** [comment]
It's supposed to mean that you become stronger, and faster by taking your alternation attribute and having that many "extra points" to distribute among physical attributes. 

It's a "enhance your existing physical attributes" thing. But it can easily turn into a "freebie" method of augmenting your stats without much drawback. Perhaps it should work like the `Berserker` feat and you should get one level of the `Fatigued` bane when you stop sustaining a given form. Hmmm

**Comment by istabosz** [comment]
Okay. I get it now. You get your Alteration score as bonues to divide, but your Alteration also acts as the ceiling. I'll think about the balance and take a look at Berserker next time I sit down to work on it.

**Comment by istabosz** [comment]
So, I think the two feats could be balanced by making Alternate form cost 3 points. Other than that, the costs/benefits seem to even out. Alternate for costs a normal action, vs. a free action for Berserker, but it doesn't cause fatigue. So that seems like a fair trade. The benefits seem equal because Berserker gives Advantage 1 and +5 defenses, but Alternate form lets you boost your physical attributes and grants the potential utility uses of the new form.

**Comment by brianfeister** [comment]
Sounds good to me 👍
