### ISSUE TITLE
Combat: Initiative - Clarify ties

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#248]
Add wording that clarifies that in the case of ties something should happen.

Suggestions: 

-  Player vs GM: Player wins automatically
-  Player vs GM: Agility score next. If still tied, flip for it.

**Comment by raihje** [comment]
Isn't this covered by the "if you fail you do 5 damage or inflict a bane" type thing? Or is this more for social stuff?

**Comment by ucffool** [comment]
@raihje No, I'm talking about rolling for INITIATIVE order, not attacks.

**Comment by istabosz** [comment]
I've added clarifying text. Ties go first to highest agility. If those are tied, determine order randomly. Also updated in SRD.
