### ISSUE TITLE
Potential errors in new weapons and suggestions about them

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#251]
These are more suggestions and improvements than issues, so here they are in a separate list.

- [x] Following the rules for creating a weapon, some examples have incorrect WL (e.g. ~~`Plasmablade` should have a WL of 5~~; ~~`Sniper Rifle` and `Laser Rifle` should cost the same since they have the same properties~~; `Laser Cannon` should have a WL of 3). 
If it is intentional, I think a note should be added, saying that these weapons do not follow the rules (for people who may use the examples as reference when creating new weapons and may be confused when the WL of the example and their weapon differ).
- [x] ~~`Immobile` property conflicts name-wise with the `Immobile` bane and may cause confusion.~~
- [x] ~~No weapon in the example has the `Immobile` property; I think the `Laser Cannon` would be a good candidate.~~
- [x] It should be noted that all weapons except natural weapons (shuch as fists) have a base WL of 1 (otherwise a `Short Sword` should have a WL of 1 since it doens't have any beneficial property).
- [x] ~~`Defensive` property should increase the wealth level by 1 per tier (so that a `Defensive 3` weapon doesn't cost the same as a `Defensive 1` weapon, as shown with `Small Shield` and `Riot Shield`).~~
- [x] ~~It may be worth to readd the `Heavy` property to the properties list, just to remeber people when acquiring new equipment and for who jumps directly to the weapon table without reading the paragraph about the Carrying Capacity.~~

**Comment by LockeVS** [comment]
Minor typo: The property entry for `Laser Rifle` is missing 'Precise.' Also, the WL calculations appear to be off: Base WL (1) + 'Deadly 2' (+4) + 'Slow' (-1) + 'Delayed Ready' (-1) = 3, not 4.

**Comment by brianfeister** [comment]
The WL formula is still in flux a bit but we'll nail it down soon. Thanks!

**Comment by DukeAnax** [comment]
Moving the Unmovable Object... How about call it Stationary?

Add Thrown property to ranged weapons like the Hatchet to indicate it cannot be used repeatedly like loaded weapons.

**Comment by Elvenoob** [comment]
I think that would be covered by a property we already have, although, I don't see the reason to stop people from lugging around a bagful of hatchets and hurling them at someone.

(Other thrown weapons make a lot more sense for this, like a long quiver for javelins, but whatever.)

**Comment by DukeAnax** [comment]
Well, there is a semantic difference between carrying a melee weapon that you can throw and a collection of throwing weapons. In the first case you may have to bring a spare if you want that. 
A weapon set or a loaded weapon may also be more expensive.

**Comment by brianfeister** [comment]
@DukeAnax - I'm fine with "Stationary" as a replacement for "Unmovable".

I'm intentionally sidestepping a hard ruling regarding thrown weapons like hatchets because, using arrows as an example -- we definitely do not keep track of them nor encourage doing so with Open Legend. Hatchets and javelins are a bit trickier because I think there is a reasonable divide between GMs that will want to track number of (daggers / hatchets / javelins) and GMs who would still prefer not to track that. For this reason, I plan to stay the current course and not comment on this in the Core Rules.

**Comment by infernodemon2005** [comment]
we should at least make an optional rule that some may wish to consider tracking thrown weapons, otherwise some newer gms may not know that they could do such things.

**Comment by brianfeister** [comment]
@infernodemon2005 - A primary motivation is that I don't want to add more rules text for such a thing and increase the bulk of the text.

**Comment by jcte02** [comment]
All issue resolved. Closing.
