### ISSUE TITLE
Add clarification about the Players & GM handleing stacking items to the inventory section

### ISSUE THREAD

**Issue by Elvenoob** [openlegend/core-rules#256]
Coming off the conversation I had with Brian on on mightybell, I'm suggesting an addition to this paragraph;

> You can carry up to twenty pieces of gear. No more. Only track the items that will actually affect the game. So, no, you don’t need to record your pants and shirt on your character sheet. But, your armor does count.

Which would read something like this;

"When it comes to multiples of the same kind of item, which has enough of effect on the game to be noted in your inventory, whether the items take up inventory slots individually or as a group is up to the GM and players"

Because, while Brian envisioned cases like this being a DM-fiat or something the group agrees on, the original text instead appears to explicitly say, every instance of an important item takes an inventory slot.

**Comment by istabosz** [comment]
Just added a few sentences to clarify. Also updated in SRD.
