### ISSUE TITLE
Bolster: Why not Extraordinary?

### ISSUE THREAD

**Issue by Elvenoob** [openlegend/core-rules#257]
http://www.openlegendrpg.com/boons/bolster

This one struck me as a little odd. The generic assistance spell doesn't help out spellcasting at all. 

I'm not sure why this is the case though, I'd say a particularly strong can of coke (Crafted 1-use Bloster item) or some divine insight would probably help a wizard do their thing too.

So, I was wondering, why are they left out of that boon?

**Comment by istabosz** [comment]
Yea, I agree. It's just advantage your getting, not access to more banes and boons, so I think it should be universal.

**Comment by brianfeister** [comment]
I'm good with making it universal.

**Comment by istabosz** [comment]
Updated in boons file and SRD
