### ISSUE TITLE
Natural Defense unbalanced

### ISSUE THREAD

**Issue by DeanWilliam** [openlegend/core-rules#260]
Right now, Extraordinary Defense is far superior, being cheaper and affecting all three defenses.
Maybe its power could be increased slightly?
For example, +2 at tier one, and then +4 and +6.
Another solution might be to make them one feat that increases one defense, but can be purchased multiple times for the different defenses, like Attack Specialization. That way, players can decide whether they want a force field, dragon scales or a mental shield.

**Comment by brianfeister** [comment]
Good point, you're right they're unbalanced. I think this got lost in the shuffle.

Best fix will be:

Extraordinary Defense: 3pts per tier
Natural Defense: 2pts per tier

**Comment by ucffool** [comment]
IT was on my mental list of things to bring up, but glad @DeanWilliam did (last 48 hours on MightBell have been exhausting). @brianfeister I think that's a perfect adjustment.
