### ISSUE TITLE
Add an "Arbitrary Damage by Severity" section in the GM's Chapter

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#261]
The idea is that we don't ever talk about arbitrary damage for things like falling, environment, etc. While it's true this often doesn't matter if it's outside of combat, I think it could be useful as a small table that advises GMs how to deal situational / environmental / etc. damage to a player:

### Situational Damage
|  Severity | Damage | Example  | 
| - | - | - |
| 1 | 1d4 | Falling 10', a minor burn |
| 2 | 1d6 | Falling 20', etc. |
| 3 | 1d8 | Falling 30', etc. |
| 4 | 1d10 | Falling 40', etc. |
| 9 | 3d10 | Falling 90', falling into lava |

**Comment by brianfeister** [comment]
Curious @istabosz thoughts on this.

**Comment by istabosz** [comment]
I agree we need something like this. Makes sense to just use the same progression as attribute dice.

I'm assuming this is straight damage that just bypasses defenses.

**Comment by DukeAnax** [comment]
Well lethal damage has recently be made a non optional concept, so out of combat damage actually matters much more now. And it's a usefull story tool if someone can't get enough rest and has to go into combat with less than full strength.

I'm not sure about straight damage though as you can fully Guard against Falling with Agility, Might and Equipment. There are guys in Parcour that can do 30' without a scratch. 

And Toughness is supposed to help against Poison. It also doesn't make much sense that different characters are affected exactly the same by different effects.

I think we can be simple here and not make a seperate mechanic, just use the regular roll (d20+Attribute vs Defense) the Attribute being Environment, based on the table.

**Comment by brianfeister** [comment]
@DukeAnax make lethal damage part of the standard ruleset doesn't change the fact that Lethal Damage is rarely inflicted, it was just a way to make sure feats like [Lethal Strike])(http://www.openlegendrpg.com/feats/lethal_strike) aren't relying on mechanics that are not part of the official Canon.

The idea here is that you can ad hoc rule that there is a normal attack roll (that's how traps are handled in A Star Once Fallen), but that's not what this is about.

This is about "you take X damage from drowning this round" or "you take Y damage from being stuck in lava this round". Situations where damage is guaranteed but dice should be rolled to determine severity.

**Comment by brianfeister** [comment]
@istabosz I guess my answer above answers your question as well. I'm open to other ideas.

**Comment by brianfeister** [comment]
And I typos in the dice column that I've fixed

**Comment by DukeAnax** [comment]
@brianfeister Ok, I got confused because you mainly based this on Falling, which to me is not a situation where damage is guaranteed.

**Comment by Hassurunous** [comment]
For your parkour example, Duke, there is a feat (Breakfall) that would imitate what you describe. Also, there are the Flight and other Boons that can imitate the same sort of thing. 

I think a short table with examples like this one would do wonders for GMs new to the system to help them gauge the severity of damage they should be doing. Mainly because we are in a relatively low-hp system, at least compared to something like high-level D&D.

**Comment by Th3Way** [comment]
Is there a need to specify the distance of the fall? Wouldn't it be more in keeping with the rest of the system to use degrees of adjectives. 
Minor
Lite
Moderate
Severe
Extreme
That would make it more multi-genre friendly. Falling 10 feet in a Kung Fu style game is trivial compared to a pulp style game.

**Comment by brianfeister** [comment]
@Th3Way Hmm... I get where you're coming from, but I don't think `Minor` / `Lite` / `Moderate` / `Severe` etc. are going to work. 

It'll probably stay as 10' / 20' / 30' etc unless someone has a genius idea I haven't thought of.

I would say that in Kung Fu games falling is still equally damaging, it's just that the people tend to fly or levitate and so they don't really take damage from falling at all.

**Comment by EliManthey** [comment]
in kung fu panda crane still gets injured when he falls even though he can fly...just saying,,,,

as far as this arbitrary damage stuff goes I would fold attribute rolls into this. Someone with protection might be able to cushion his fall. Using agility to grab handholds or roll into a fall decreasing the damage. Just some basic examples using fall damage. Not sure how the attribute roll would be implemented...maybe a dc based on severity to decrease the damage dice by one?

**Comment by istabosz** [comment]
Just added a commit to include ad hoc damage in chapter 7.
