### ISSUE TITLE
Provide versions of the rules

### ISSUE THREAD

**Issue by Idrinth** [openlegend/core-rules#263]
It's currently hard to play a game with rules changing at a high frequency.

Github provides [releases ](https://github.com/openlegend/core-rules/releases)to package a project's status at a specific point in time and name them. This would allow groups running a game to both more easily define the rules to be used(i.e. use v0.11.0 vs use commit https://github.com/openlegend/core-rules/commit/b0edb9a5516843c35e5c0273f0b040df625d1705 ).
In turn it would allow for easier conversions where necessary without ending up with rules that require a complete character rebuild, because it's both easier to keep running on a specific version as well as it's easier to compare two versions before updating the game to it and breaking something while doing that.

**Comment by brianfeister** [comment]
That's assuming that people can parse the YAML and markdown source files and understand the repo structure, which most cannot. But for a few folks I suppose it would be helpful. Though really you'll be better off with a git GUI that offers diff visualization like SourceTree. That's what I do and works better than release tags but we can do release tags as well.

**Comment by Idrinth** [comment]
The yaml files are relatively easy to read since they use normal english words to describe what each part is, but the rules section is a bit harder to read due leftover formatting information not supported by github.
Even those are readable tho, a tiny bit weird at first maybe, but the information is easy enough to gather.

In theory it would also be possible to build a small program to handle providing the desired version in a way more people can understands, but that's more likely a side-project for someone else to do, you would just have provided the option to do that with little overhead.

**Comment by brianfeister** [comment]
Yup. Sounpds good. Keep in mind that all rules changes will cease and the text will be locked for proofreading and editing in abut a month or so.

**Comment by ucffool** [comment]
I simply treat any game as a beta game; things are in flux and that's just been a fact since the KS went live. Right now ASOF is back out of sync, but not so much that you can't get a sense of the game without it, especially since it is a simplified feature set.
The funny thing about *side projects for someone to do* is that more is said than ever done. Nobody's fault, just the reality. And since the core is getting locked before the end of Q1 '17, seems silly to do extra overhead.
This reply seems overly negative. Sorry. high five?

**Comment by brianfeister** [comment]
LOL. No worries. :P  ... it's a valid suggestion, I just think the benefit isn't what it otherwise would be due to the the factors I mentioned earlier as well as your comments @ucffool

**Comment by Idrinth** [comment]
Even most betas have a way to easily reference what version of the beta you had, @ucffool .

The core being locked does to my understanding not decrease the amount of possibly breaking changes, like modifiing the cost of feats or removing them or just noticing that a specific bit of text could easily have been understood and clarifiing that in a way not matching what some players envisioned it to be.

The use of versions would already enable some people to have an easier time dealing with the changes, possible side projects would just increase the benefit to a larger audience without increasing the additional effort for the core team, making sure you don't get burned out from that over time.
I was never talking about one of you doing that extra work and since I'm unsure how much time my own side projects will take I didn't offer to take this one up either.

**Comment by EliManthey** [comment]
I think a simple fix would be a numeric version number on the website so people can easily see if the rules have changed

**Comment by brianfeister** [comment]
Yeah, that's kind of implied as part of the plan with what @Idrinth is mentioning.

**Comment by Idrinth** [comment]
my issue was more about tracking down with what set of rules I created a character and what I need to change, @EliManthey , but yes, having the version number on the website as well would be nice.

**Comment by brianfeister** [comment]
We're about to lock the rules in a week or two so I think this ship has sailed.
