### ISSUE TITLE
Remove references to Resist Action

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#265]
In a few feats and in a few spots in the SRD and core it refers to a "Resist Action", which doesn't exist, as `Resist Banes` is a section under the **Move Action**. 

I'm seeing this as an oversight that needs to be corrected (I'm happy to do it), but just want signoff/suggestion on wording.

> Resilient: Any time you take the Resist action, you have advantage 1 on the roll.

Replaced with:

> Resilient: Any time you choose to resist banes as your Move action, you have advantage 1 on the roll.

----------

This brings up one extra item. Under **Major Action > Assist An Ally**, I suggest the following addition:

> You can use your major action to assist an ally with an action roll if they are using an attribute you have a score of 1 or greater in. **You may instead choose to assist them in resisting all of the banes inflicted upon them.** The ally automatically gets advantage 1 on their roll.

**Comment by jcte02** [comment]
In other parts of the document this is referred as `Resist Roll`.
We should settle with a definitive name and make it universal, for consistency and to avoid misunderstandings (one may think `resist rolls` and `resist actions` are different).
This will solve one item of #242.

**Comment by ucffool** [comment]
I was looking around to see if there was ever a way to trigger a `Resist Roll` outside of a player's own `Move Action` and was unable to find one, thus it's partly **whether that concept is now a core tenet or just a matter of current rules.** If the former, then it makes sense to get rid of the term `Resist Roll`. If the latter, then it should be fixed throughout as `Resist Roll` and that be clearly defined under Move Actions.

**Comment by brianfeister** [comment]
It's in a number of places. Pretty sure I will call it a `Resist` but will follow up after I've had a chance to review relevant text

**Comment by DukeAnax** [comment]
There are also references a "Sustain Action" and a "Defend Action" which might have to be changed as well. Or people might get confused as to when they can use them.

I agree with @ucffool that the term _Action_ should only be used for the mechanical Categories: 
Focus Action, Major Action, Move Action, Minor Action, Free Action and Interrupt Action

You can use Sustain as a Minor Action
You can use Resist as a Move Action
You can use Defend as an Interrupt Action
