### ISSUE TITLE
Clarify Multi-Bane Specialist (shared attribute requirement)

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#266]
`Running the Game`
> **Multi Bane Specialist**: Choose two banes that you are able to inflict. You are able to make attacks that inflict your targets with both banes at once. Your attribute score must be equal to or greater than the power level of both banes combined. If the two banes use different key attributes, provided your key attributes for both banes is sufficient, you use the higher of the two attributes for both the attack and determining if you are powerful enough to combine them.

`Feats`
> Choose two banes that you are able to inflict and that share a common prerequisite attribute. You are able to inflict both banes with a single attack. The required attribute score for combining the banes is equal to the sum of their power levels (e.g., combining knockdown and slowed, both power level 2, would require an attribute score of 4). If the banes target different defenses, you choose which defense your attack targets. On a successful attack roll, the target is inflicted with both banes. They each persist independently of one another and must be resisted separately. 

It wasn't until I read the phrase, *If the two banes use different key attributes, provided your key attributes for both banes is sufficient, you use the higher of the two attributes for both the attack and determining if you are powerful enough to combine them* that I realized that was possible; it's not part of the Feat effect.

**Comment by jcte02** [comment]
@ucffool The feats listed in Chapter 7 are only outdated, as reported in #225.
The version of the feat that is present in Chapter 7 was not updated to the current version (see commit bdbe306f3f07956340bb22a8130d3afd85b85edb).

**Comment by ucffool** [comment]
@jcte02 Good call. I've updated the issue title to reflect the clarification of a shared attribute requirement.
