### ISSUE TITLE
"Heavy" Is not listed as a Weapon Property

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#268]
"Heavy" Is not listed as a Weapon Property in the "Building Your Own Weapons" section. 

Adding the change to my pull request. I assume this should be another property in the section that reduces the cost of an item, according to Brian's calculations in the notes on my commit.

**Comment by brianfeister** [comment]
Nope, it's effect is not sufficiently negative to reduce cost in the weapon building formula.

**Comment by Hassurunous** [comment]
Alright. I'll go in and fix it in the Pull Request then. You had it listed as a -1 which threw me off. Thanks for the quick response!
