### ISSUE TITLE
Consider additional attributes for battlefield defender

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#27]
I'm thinking that Agility and Abjuration might also be applicable.

**Comment by brianfeister** [comment]
Yeah that sounds good. I wonder if it's rare enough to make it 1 point? One thing we need to be on the lookout for is feats that can drop down to 1 point.  There are alot of gaps where you don't necessarily have something you want to buy with 1 feat point. Just saying we should be looking for opportunities there.

**Comment by istabosz** [comment]
Actually, I was kinda thinking this feat might be easily abused. Since I can take a defend action on myself, it gives me the potential to raise my Defense AND still do damage. If someone optimizes for it, they could just constantly be defending. They wouldn't be doing as much damage, of course, because they'd be opposing the enemies attack rolls, which tend to be higher then defense scores.

**Comment by brianfeister** [comment]
True. If you become intimate with the various combinations, there are tons of things that can be abused. The main theme, however, is that in Open Legend, every roll matters, so you can't just decimate an enemy without rolling. You can become very frequently successful, but every character should miss sometimes.

`Attack Redirection` is equally primed for abuse, as it doesn't just return the damage to the attacker, but redirects it to one of the attacker's allies.

**Comment by istabosz** [comment]
Gotcha. Well, maybe keep it at 2 still. Rare, but effective. Ya know. Not quite on the same level of uselessness as Ageless :-D

**Comment by brianfeister** [comment]
Sounds good to me
