### ISSUE TITLE
Fortitude with Armor and Natural defense feat

### ISSUE THREAD

**Issue by Madmadua** [openlegend/core-rules#273]
Hello,

The fortitude prerequisite of the natural defense feat is higher than the require fortitude for the armors. It seems a bit unfair to send feat points to get a worst natural armor than the armor the PC would get with his fortitude. (armor and natural armor do not stack : correct me if I am wrong)
It could be a good idea to remove the fortitude prerequisite of this feat. Natural armor isn't necessarily due to high constitution. 

Concerning the require fortitude for the armors, I found it a bit low. 2 or 3 of fortitude is easily accessible.
And I think that every PC will get at least a few points for the Toughness and HP. 
I propose : 
light armor -> 1 and 2  (Need to invest a little, no free armors)
medium armor -> 3 and 4 (Not to hard to get, fare protection)
heavy armor -> 5 and 6 (Not everybody gets one)

That's my humble proposition. 
Madmadua

**Comment by Elvenoob** [comment]
I'd reverse that and just make the feats easier to access instead.

**Comment by ucffool** [comment]
Fix the feat is better:
Currently:
**Tier 1:** Fortitude 2
**Tier 2:** Fortitude 3
**Tier 3:** Fortitude 5 

Fix:
**Tier 1:** None
**Tier 2:** Fortitude 1
**Tier 3:** Fortitude 2 

The result is that it costs you a little less in attribute spend but a little more in feat spend to acquire the same result.

**Comment by Madmadua** [comment]
My first post was confusing. There was 2 distinct issues : 
1/ Fortitude prerequisite of Natural defense. (I like your solution ucffool)

2/ I wanted to point out that the fortitude requirements for armors are low. 
Warriors type characters easily start with heavy armor and stay with heavy armor. With a higher fortitude requirement, they will have to choose between invest more in fortitude for Guard, Toughness and HP or in Agility or Might for Guard and Attacks.
Mage type characters will invests a few points in fortitude (for Toughness and HP) and will have access to medium or heavy armors. I fear that at level 3 or 4, all characters will have heavy armors. 

Tell me what you think

**Comment by ucffool** [comment]
@brianfeister Close.

**Comment by brianfeister** [comment]
@Madmadua I'm OK with accessing heavy armor at low levels. The goal here is to use armor more as a storytelling thing so that a Paladin can start with their full plate at 1st Level. But at the same time, a Mage can do the same.
