### ISSUE TITLE
Breakfall needs revision

### ISSUE THREAD

**Issue by Th3Way** [openlegend/core-rules#274]
With the introduction of flight feat, breakfall has become obsolete even before the incoming environmental damage changes. I believe a simpler version of the feat can be achieved with a slight change and will function regardless of the incoming damage charts.

Breakfall
Tiers 1-2
Cost: 2 points
Tier 1: If you are able to act, you reduce all fall damage by half.
Tier 2: If you are able to act, you suffer no damage from falling.

I'm sure the wording needs to be worked out a bit but the idea is there. 4 points for zero fall damage is in keeping with power level of other feats and fly feat. In addition removing of the 10 feet per rank keeps it simple and easy to implement. If the inclusion of the requirement that a surface must be nearby to utilize the feat, then the cost needs to be lowered as that isn't nearly as useful.

**Comment by brianfeister** [comment]
Sounds good. I'm in favor of it. It's narrative-first, which is a good fit for Open Legend.

**Comment by istabosz** [comment]
This has been changed and updated in the SRD as well.
