### ISSUE TITLE
Add PL 2 to the Shapeshift boon

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#283]
The Shapeshift boon is referring to the restrictions of Power Level 2, which are then removed subsequently after each additional Power level, but at the moment Shapeshift doesn't have a Power Level 2. Here is the reference:

_You or a willing creature you touch transform into a creature whose highest attribute is less than or equal to your Alteration score. Your Alteration score for the purpose of this feat is limited to your level or 5, whichever is higher. All of the target's existing extraordinary attribute scores drop to zero, and they acquire the Agility, Fortitude, Might, and Perception attributes of the new form. The following limitations apply at **Power Level 2**, and are gradually removed at higher power levels:_

_Shapeshift_
_Duration: Sustain Persists_

_Invocation Time: 1 Major Action_

_**Power Level: 3/ 4/ 5/ 6/ 8/ 9**_

**Comment by istabosz** [comment]
Good catch. I've updated in the boons file and SRD
