### ISSUE TITLE
Boon: Shapeshift > Clarify PL2 in Effect

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#291]
~~Power level was added recently, but neglected in the Effect section.~~
Clarify wording so PL2 is described in the bulleted list.

**Comment by brianfeister** [comment]
I'm so confused. I haven't seen anything about PL2 `Shapeshift` what exactly are we doing?

**Comment by EliManthey** [comment]
in shapeshift right before the first bulleted list of restrictions it states that those are for power level 2

**Comment by ucffool** [comment]
Reading MightBell on 6 hours sleep not a good idea.

**Comment by brianfeister** [comment]
Hmmm.... I don't know. I think we should re-structure the text. I would say your confusion is quite justified. Having PL2 in the list at the top and then an effect breakdown that doesn't have a bullet for PL2 is not something we do anywhere else and is a confusing format.

**Comment by brianfeister** [comment]
Also 6 hours of sleep sounds decadent... mmmMMMmmmm

**Comment by istabosz** [comment]
The way the feat works is that you have all of the restrictions listed when you cast at PL 2. Each PL above that removes some restrictions.

I know you don't like tables in the boons @brianfeister , but it might work better to have something like this:

| Power Level | Size | Physiology | Special Movement | Extraordinary Abilities |
| - | - | - | - | - |
| 2 | No change | humanoid or animal | No | No |
| 3 | half or double original | humanoid or animal | any non-flying | No |
| 4 | one-quarter to quadruple original | humanoid or animal | any non-flying | No |

**Comment by ucffool** [comment]
Also want to add this post to the discussion:
https://openlegend.mightybell.com/posts/1001018
(not everyone has 'humanoid' as a starting point)

**Comment by ucffool** [comment]
List elements are fine, but I have to agree with @brianfeister on not having table html within a boon.

**Comment by brianfeister** [comment]
There's no way that table would fit into the 2 column layout in the book.

**Comment by EliManthey** [comment]
I think it is structured fine as is but that first list should be comma'd out and given its own bullet point similar to how barrier is structured
