### ISSUE TITLE
Starting Wealth Level for weapon creation

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#299]
The weapon creation rules are missing a starting WL to build weapons. 
There should be a line added in _Building Your Own Weapons_ under _Step 2: Choose Properties_ which says that any WL-calculations for weapons start at WL1, with the exception of an unarmed attacks.

**Comment by brianfeister** [comment]
I'm confused on this one. I thought we fixed this by making it so that **Deadly** is WL 2 per tier. If we start with a base WL 1, then a Katana / "Basic" Enchanted Sword becomes WL 5. Right now they're listed as WL 4 which seems correct.

**Comment by JVanGo** [comment]
I don't know how you end up with WL5 for the Katana, if you start at WL1. Katana has only Deadly 1, which raises WL by 2, so we end up with WL 3. BUT, we added this line:

> If the item has the Deadly property, it’s Wealth Level cannot be lower than 4. Depending on the story, a GM may wish to lower this threshold if they want their game to be more dangerous or it takes place in a world where high-tech weapons or firearms are common.

which brings the Katana to WL4. Also, if we start the calculation at WL0, we end up with Deadly 1 and Deadly 2 being both WL4, if you don't add anything else. 

The problem is there are a few lines, which negate the WL1 calculation starting point, even if nearly all the examples point towards WL1. I'll try to point them out:

- Every single weapon seems to be calculated starting from WL1, with the exception of Plasmablade, Vorpal Sword
- The Deadly property increases an item’s Wealth Level by 2 per tier. So a Deadly 2 item has a starting Wealth Level 4.
- WEAPON BUILDING EXAMPLE: KUSARI-GAMA (CHAIN & SICKLE)

So either way, we need to clean these up.

**Comment by JVanGo** [comment]
Nevermind, I missed the line, but is in Step 2:

> The Wealth Level of all weapons begins at 1.

Still the whole section needs a clean up,  as there are quite few mistakes in there.

**Comment by brianfeister** [comment]
Cool. Thanks for breaking that down.

Hmmmm, maybe I need to change the example weapon, because it actually sucks for historicity to use Kusari-Gama and have it be WL3 when historically it was an improvised weapon for people that were pretty poor and didn't have options.

**Comment by JVanGo** [comment]
You could add the Slow propriety to notch it a tad down in WL. Looking at some videos, readying the chain and starting to swing it around for momentum for a fight doesn't look very efficient, so I'd say that would be reasonable.

Also the weapon doesn't look that defensive to me, so you could bring it down further by removing defensive, but it's up to you.

**Comment by brianfeister** [comment]
Brilliant, I like the `Slow` suggestion. Thanks man! ❤️
