### ISSUE TITLE
Removing Combat Opportunist?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#30]
Did we have a discussion about removing combat opportunist because we are changing Lethal Strike to grant advantage?

**Comment by brianfeister** [comment]
Do we have a note about flanking anywhere in the core rules. Mentioning that it grants Advantage 1. Which reminds me of why I introduced "Tactical Advantage" as a way of helping GMs combat players saying "well I'm flanking, that's 1, I'm swinging from the chandelier, that's 2, I'm [...]" etc.

**Comment by brianfeister** [comment]
That said, I've cleaned this up partially (deleted the Combat Opportunist feat) and left the flanking specific explanation in the Lethal Strike description for now

**Comment by istabosz** [comment]
Sounds good. I don't think we mention flanking specifically in the core rules. In chapter two, there are some examples of what might constitute advantage, two of them relating to combat. They are attacking a surprised foe and swinging from a chandelier.

**Comment by istabosz** [comment]
Added flanking as an example of granting advantage. Closing this very OLD issue :)
