### ISSUE TITLE
Add "Building Custom Vehicles/Mounts" section

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#309]

**Comment by brianfeister** [comment]
Not planning to do this. Would involve too much text and Open Legend is full of examples (like the `Animation` boon) where the option is there for GMs to create their own monsters / creatures and then later on, we will add support for them with a Monster Manual. Same principle applies here. If people want to build their own mount / vehicle and we get enough demand for it, we will publish an official "Mounts & Vehicles" compendium which will also contain the recipe for creating them.
