### ISSUE TITLE
Confused by companion feat 

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#31]
https://github.com/openlegend/core-rules/blob/master/feats/feats.yml#L315

Do companion's always have 3 attributes? If so, how do you calculate the value for the second two?

Here's my suggestion for simplification:

Your companion has three attributes. The primary attribute is determined by your tier. The other two attributes are equal to the primary attribute minus 2.

Tier 1 - Primary attribute equals your level minus 2 (minimum of 3).
Tier 2 - Primary attribute equals your level minus 1 (minimum of 4).
Tier 3 - Primary attribute equals your level (minimum of 5).

**Comment by brianfeister** [comment]
I like the idea of simplifying, however, in this case, the companion is missing out on quite a bit by not having the potential for multiple attributes to accommodate both defense and offense. But maybe it's OK.

One thought is that by the time you spend 9 points, you could have had a free extra attack, so I think it might make more sense for the two secondary attributes to be one less than the primary, as opposed to 2.  Also, maybe you get an extra secondary at tier 2 or tier 3?

**Comment by istabosz** [comment]
I don't disagree. I just couldn't tell how many attributes they were
supposed to get because the original text only specifies the value of the
highest attribute and the example you give has three attributes. So, how
many did you intend for them to get?

**Comment by brianfeister** [comment]
Ah. The original intent was a cascade. e.g. if your high attribute would be 5, then you get `5, 4, 3, 2, 1`. If your primary would be 7, then `7, 6, 5, 4, 3, 2, 1`

**Comment by istabosz** [comment]
Ok. I get it now. I've updated the text.
