### ISSUE TITLE
Surprised is the only Power Level 0 Bane

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#314]
@istabosz it's funny, when I first made `Surprised` a Power Level 0 bane, I was in a mindset where I was more willing to put up with minor wrinkles in the rules. I think we've gotten things so well ironed out, streamlined, etc. that it's a shame to keep this very strange arrangement where we have this one bane that can't be directly invoked, is meant to be decided by the GM, and has a "Power Level" of zero despite it not being invokable anyway.

Thoughts on how we might streamline this? It seems like we could push some of this to the "Determining Surprise" section, but some of the bane's mechanical description and the aspect of it being situational and not necessarily determined by roll of initiative... I just don't know where that could find a home. But currently, right now it really doesn't feel right in it's current home as a "non-invokable bane"

In Chapter 6 we currently have

---
## Determining Surprise

In any combat, one or more combatants may be surprised if their enemy catches them off guard or unaware. For example, if a pack of bandits lays an ambush for the PCs in a rocky chasm, the GM may have every member of the party make a Perception roll contested by the bandits’ Agility roll. Any PC who fails the check is surprised. The GM decides when some or all combatants may be surprised.

Surprised characters always act after non-surprised characters, as explained in the rules for initiative. Furthermore, until a surprised character takes their first turn, they may not take any interrupt actions and all attacks made against them gain advantage 1.

===
And then the surprised bane currently reads as such:

## Surprised

**Duration:** 1 Round
\
**Power Level:** 0
\
**Attack Attributes:** N/A
\
**Attack:**

-   N/A

**Description:** Being surprised is being caught flat-footed and scrambling to react to
an enemy that the character was either unaware of or did not realize was
an enemy. \newline

**Effect:** All attackers gain advantage 1 against surprised characters. Surprised
characters cannot take any actions that are interrupt actions. \newline

**Special:** Unlike other banes, surprised cannot by inflicted directly with an
action roll. Instead, it is determined by situations resulting from the
story, such as a party being ambushed by a band of thieves hiding in the
brush.

Under certain conditions a character may be surprised against **only one
opponent**. The most common example being an opponent that is disguised,
hiding, invisible, or for some other reason *not perceived as a threat*.

**Comment by istabosz** [comment]
I agree it's awkward. It's either got to stay a bane and be made invokable, or it's just got to be a special condition related to initiative.

If it was invokable, I'm imagining the attributes would be Agility, Logic, Deception, and Influence - all vs. Resolve. Resolve seems a bit awkward in some situations because Perception doesn't factor in, but I think it's passable. If we go with this option, I think that we can keep the surprise rules in the initiative section as is. Just because a bane can be invoked doesn't mean that is the only way it can be applied.

**Comment by brianfeister** [comment]
There's a tidiness about making it invokable, but what really throws me is the idea that you spend an action / turn "invoking surprise" but not really doing anything about it. 

I suppose one option could be to make it a Minor Action invocation so that you do it as a singular roll when you go to attack to check and see if you can get the drop on one or more targets. That does create a follow-up question about "who is surprised by who?"... in other words, if a target is afflicted by the Surprised bane, does that mean your allies get the benefits you do or not? Seem slightly weird, but for tidiness, I suppose it's passable.

**Comment by ucffool** [comment]
The solution is really simple, just remove the bane and then take the following part of the bane and add it to CH6:
> Under certain conditions a character may be surprised against only one
opponent. The most common example being an opponent that is disguised,
hiding, invisible, or for some other reason not perceived as a threat.

There is nothing else unique about the bane and it is out of place. The placement of this in CH6 is perfect already, with additional info in [Ch2 (Adv/Dis)](https://github.com/openlegend/core-rules/blob/master/core/src/02-actions-attributes/01-chapter-two.md#assigning-advantage-and-disadvantage).

**Comment by brianfeister** [comment]
That's fine, I should put out at this juncture that while both are viable solutions, I think it's probably best that it just be part of the surprise section in chapter 6.

**Comment by istabosz** [comment]
Yea. I agree. We don't need a bane for this. It's really just a special condition. I'll make the changes.

**Comment by istabosz** [comment]
I've removed the Surprised bane from the core and SRD. I don't actually think we need to keep the clause that @ucffool mentioned. I think it's already implied in the combat chapter.
