### ISSUE TITLE
Re-organize Combat Chapter

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#318]
I think that because this chapter was sort of built in chunks and updated a lot, it needs a bit of streamlining.

Mostly I should be able to accomplish this just by re-ordering how the information is presented.

**Comment by brianfeister** [comment]
Sounds good. I'll be curious to see what you have in mind. By all means start digging in. You and I need to check-in soon and go over the current timeline for release. Official "rules lock" is probably a week away and then we need to get a second pass on this in terms of editing. I'm not sure if I can easily find a technical editor (with availability) that I can trust on such short notice. I wish that you weren't having to self-edit, but I think the number of eyes on this up until this point might be sufficient to consider it largely  crowd-surfed in terms of feedback. 

My goal is to have you do a thorough second pass on the editing and have the text completely locked in order for me to begin laying out the book by March 15.

**Comment by istabosz** [comment]
You can see my full proposal here: https://docs.google.com/document/d/1Y1Eg5aW8kjMSily22wRiIyyqQi9itlmXMcKu7Bm3RsM/edit?usp=sharing

To highlight the changes, I'll just show the major headings below:

## When Combat Ensues

## Starting Combat

- Determining Surprise
- Roll for Initiative
- Waiting to Act

## Taking Your Turn

- Major Actions
- Move Actions
- Minor Actions
- Focus Actions
- Interrupt Actions
- Free Actions

## Damage and Healing

- Finishing Blows
- Reaching Zero Hit Points
- Healing After Combat
- Lethal Damage

## The Core Mechanic in Combat

- Why Succeed on a Failed Roll?
- Interpreting Twists and Failures in Combat

**Comment by istabosz** [comment]
I moved the core mechanic to the end because I think its previous place disrupted the flow of the combat sequence.

I also redrafted the rules for damaging attacks, bane attacks, and boon invocations to make them more streamlined. Reduced them down to 3 mostly parallel steps, and removed what I think was a clunky table. Repositioned the multi-targeting rules outside of the standard targeting rules to help players digest their options more easily.

**Comment by brianfeister** [comment]
Looks good to me, go for it. Reading through the examples, I'm reminded that some of these names are sillier than I prefer, but we'll fix that in a future (but not too far in the future) edit 😝

**Comment by istabosz** [comment]
lol. Fair enough. You and I have such different gaming styles. I think 95% of the characters I've ever played have been silly.

**Comment by istabosz** [comment]
@brianfeister I'm a little hesitant to implement this change because I don't want to screw up the SRD. It's one thing to change a paragraph here and there, but this is restructuring the entire chapter. So, I imagine just cutting and pasting it all into the SRD will mess things up.

Any advice on how to proceed?

**Comment by istabosz** [comment]
Implemented these changes, so closing this issue.
