### ISSUE TITLE
Replace static movement penalties with "move up to half your movement" clause

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#319]
In recent the recent changes, the slow bane saw the following revision:

> The afflicted target’s speed is reduced to half it's current speed, rounded down to the nearest 5' increment. This applies to all movement that is physical (flight, walking, climbing, etc.).

That modification should also be applied to the special section of the **Immobile** bane.

**Comment by brianfeister** [comment]
This was fixed recently.
