### ISSUE TITLE
Updating the craft feat given our new wealth system

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#32]
So, this feat doesn't work with wealth levels. Here's my thought on how to update it:

Tier 1 - You can craft items equal to your Wealth Level.
Tier 2 - You can craft items equal to your Wealth Level + 1.
Tier 3 - You can craft items equal to your Wealth Level + 2.

We would leave things like how long it would take up to the GM based on the item being crafted.

Although it might seem OP to give a means of getting items 2 higher than your wealth level, the downside (other than the feat points invested) is that the equipment is only in the narrow sphere of your craft focus.

**Comment by brianfeister** [comment]
I like your suggestion. There's also the thought that it could be removed altogether.

**Comment by istabosz** [comment]
True... Tough call. I'll leave that up to you :p

**Comment by brianfeister** [comment]
Ok, let's keep it for now. I like the idea of keeping it but the combination of this with the `Wealthy` feat is super broken. I propose we make this only have two tiers (max is 1 higher than your wealth, otherwise a 4th level character can easily abuse feats to build themselves a castle)

**Comment by istabosz** [comment]
Got it. This one's complete.
