### ISSUE TITLE
Telepathy Boon Attribute: Prescience but not Influence

### ISSUE THREAD

**Issue by mercuryred5** [openlegend/core-rules#324]
It seems to me like the Telepathy boon Attribute should be "Influence" instead of/in addition to "Prescience". 

From Ch 1, Attributes at a Glance
Influence: Control the minds of others, speak telepathically, instill supernatural fear, create illusory figments, cloak with invisibility
Prescience: See the future, read minds or auras, detect magic or evil, scry, communicate with extraplanar entities

I mean, it's in the wording there there.  It seems sort of weird that I'm like, hey, I can read minds, but only if I see the future or something?

**Comment by brianfeister** [comment]
Telepathy is broadcasting information psychically. Reading minds us a separate bane called Mind Dredge. 

So, the Influence attribute has to do with broadcasting an extraordinary mental effect, while Prescience has to do with receiving mental information in an extraordinary way. 

Receive-only telepathy is Mind Dredge, while Telepathy sets the invoker up a relay to push mental signals to one or more targets

**Comment by mercuryred5** [comment]
Would a super minor substitution of "project telepathically" for "speak telepathically" be appropriate for the Influence Attribute description?

**Comment by brianfeister** [comment]
Mmm... I don't see the change as obviously helpful, because Telepathy is more logically thought of as speaking rather than projecting

**Comment by mercuryred5** [comment]
This is what led to my confusion, that if Influence is to 'speak telepathically', then Telepathy (speaking telepathically) should be driven by Influence.

**Comment by brianfeister** [comment]
Gotcha. No problem, the great debate of weather sending and receiving Supernatural mental signals should fall under the receiving or sending attribute has raged too long. Going to remove the controversy and just make it accessible from both
