### ISSUE TITLE
Remove Tech Level Indicators from Specific items

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#325]
I don't think that a tech level needs to be assigned to every single mount, weapon, extraordinary item, etc.

I think it creates one more piece of information to track that will rarely come up in play. The only real time tech level matters is when mixing them.

I think an appropriate solution would be to keep the tech level call out box that we have. The GM could assign a tech level to a world, region, or faction. I think the descriptions provided in that call out box are enough to help people know what items are available.

**Comment by brianfeister** [comment]
Yup, I'm good with it!
