### ISSUE TITLE
Final Edit Follow-ups

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#327]
I'm going to use this issue to track areas that come up in my final round of edits that require some input or further action.

**Comment by istabosz** [comment]
Chapter 1, around line 13:

> ### Choose an Example Character & Modify It
>
> For anyone who feels they could benefit from some inspiration, you can easily make a copy of any of these spreadsheets (they include formulas for doing most all of the calculations for you), and then increase or decrease attribute scores, as well as add or remove feats. Be sure to adjust the **Level** field to get the correct calculations for attribute & feat points at your current character level.
>
> [**View Pre-generated Character Options**](https://drive.google.com/drive/u/0/folders/0Bx_UrXHMi3wmUlJjbDZiaGtIX00)

**Comment by istabosz** [comment]
Chapter 1, around line 151.

@brianfeister I know you said that the archetype builds are already being handled, so do you want me to leave the current ones in here until you add the new ones?

**Comment by istabosz** [comment]
The following text makes sense on a website, but not in a book:

Chapter 1, around line 295:

> You can read the feat descriptions in a searchable list [*here*](http://www.openlegendrpg.com/feats).

**Comment by brianfeister** [comment]
@istabosz we will add the new character archetypes and probably leave most of the existing ones. I'll handle that bit and you can check my work after.

Agreed about anything that links to a web page. Instead mention where it exists in the book.

Bookmark the following link and browse the files you change starting here and ensure that new changes you make are applied to the `print-edition` branch - https://github.com/openlegend/core-rules/tree/print-edition.

This will allow us to continue to pull in micro edits from the main branch while making unique tweaks like those mentioned to the `print-edition` branch without merging those changes back to the `master` branch. If this needs explaining or help, don't hesitate to ask for it.

**Comment by istabosz** [comment]
@brianfeister I don't quite get it. 

1) Should I be duplicating all of my edits in both the core and the print edition branch?

2) Should I keep web references in the core and convert them in the print edition branch?

**Comment by brianfeister** [comment]
Okay sorry, yeah my suggestion doesn't quite account for the whole situation. What we need to do is make print edition specific changes in the print edition branch, and then ones that should go to the website in the Master branch. You won't have to duplicate changes between them, because one of GitHub's primary purposes is allow the changes from Master to be pulled into print edition without the extra step of doing it manually via a pull request, which I can do it or show you how

**Comment by istabosz** [comment]
Ok. I think I got ya. I'm done with chapter 1, so you can check my work to make sure I did it right.

I made all the typographical/organizational/etc edits on the master branch.

I changed the web references on the print edition branch.
