### ISSUE TITLE
Find a Place for Perks and Flaws

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#329]
I'm pretty sure this was discussed and agreed upon before. Perks and Flaws don't really fit in the character creation section. The character creation should just say how to pick your perks and flaws, and the lists and rules for use should appear somewhere else.

I suggest they become Chapter 4: Perks & Flaws.

This would require Wealth& Equipment to become chapter 5, and references be updated throughout the core.

**Comment by brianfeister** [comment]
@istabosz sounds good. I need to get my new stuff published (Chapter 8) which would then become Chapter 9 :)

**Comment by Hassurunous** [comment]
That or add them as a separate link, like Boons, Banes, and Feats.

**Comment by istabosz** [comment]
@Hassurunous Good idea. It will need its own chapter for the print edition though for sure.

**Comment by istabosz** [comment]
@brianfeister Can you confirm this is the desired chapter order? I want to go through every file and update the chapter references.

Introduction
Chapter 1: Character Creation
Chapter 2: Actions & Attributes
Chapter 3: Feats
Chapter 4: Perks & Flaws
Chapter 5: Wealth & Equipment
Chapter 6: Banes & Boons
Chapter 7: Combat
Chapter 8: Running the Game
Chapter 9: Rewards

**Comment by brianfeister** [comment]
@istabosz Looks good to me!

**Comment by istabosz** [comment]
Done. Made a new chapter and updated all chapter references throughout the text
