### ISSUE TITLE
Two-Weapon Defense Feat

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#330]
During the moderators meeting around two weeks ago, we pretty much agreed upon that the feat cost should probably reduced by 1, to bring it down to a cost of 2 feat points.

Also we talked about changing the prerequisite, because Multi-Attack Specialist didn't feel thematically fitting. Defensive Reflexes was proposed as a replacement prerequisite, because it also shares the agility prerequisite and would fit narratively better, as it involves defending already.

This topic probably got buried in favor for the new Extraordinary Items section, so this is just a reminder.

**Comment by brianfeister** [comment]
@JVanGo I think I'm going to make the prerequisite `Attack Specialization (Any one-handed weapon)` because `Defensive Reflexes` doesn't necessarily fit thematically for a "whirling dervish" two weapon character that moves quickly and uses their speed to defend while on the offense.

**Comment by Hassurunous** [comment]
That sounds like a solid plan. 

As for the Two-Weapon Defense, I agree with the proposal to decrease the cost to 2.
