### ISSUE TITLE
Craft Mundane Item

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#336]
Craft Mundane Item (I - II) 
Cost: 2 points

Prerequisites
Tier 1: Learning 3Knowledge I

this is how it's current displayed in the OL site
i assume it was intended to say "Tier 1: Learning 3 OR Knowledge I" since that's how it used to be before the Extraordinary Items went live

**Comment by brianfeister** [comment]
Fixed I believe
