### ISSUE TITLE
Reconsider Restoration boon

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#337]
This boon currently allows you to dispel banes beyond the PL of the boon by making a roll with a CR equal to 20 + four times the PL of the bane. That seems so high that it's basically impossible beyond PL 3.

What if we just make it 20 + twice the PL?

That seems slightly more reasonable though still out of reach.

**Comment by brianfeister** [comment]
Sure thing, works for me. 👍

**Comment by istabosz** [comment]
Complete.
