### ISSUE TITLE
XP Progression at level 9 and 10

### ISSUE THREAD

**Issue by SamWilby** [openlegend/core-rules#342]
Seemingly a typo in Character Creation, the table for level progression at the bottom of the page has it costing 2xp to get from level 8 to 9, which also throws off the numbers for level 9 to 10. 

![image](https://cloud.githubusercontent.com/assets/26345039/24098336/e6e89b92-0d61-11e7-864d-940e0f561b08.png)

Should be 9 -> 24, 10 -> 27

**Comment by istabosz** [comment]
Good catch! Fixed

How embarrassing. lol. Mental note: when proofreading, remember to check the stuff that I just added too.
