### ISSUE TITLE
Arcane Bloodline > Extraordinary Bloodline

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#347]
Currently, it only talks about "magical" creatures, but it could just as easily be tooled to be something like "you're the son of a family of soldiers, so everyone knew you'd be an officer in short time."

Think this is a holdover from the "fantasy" Open Legend. It should probably be retooled in some way to support multi-genre. Perhaps change wording from:

"Your ancestry can be traced to dragons, fey, or a similarly magical race. As such, you command the respect of those who practice the arcane arts. You are assumed to have knowledge and a destiny for greatness in the ways of magic, and others treat you with deference. This influence could guarantee your placement within an Arcane College, grant you an apprenticeship with a famous Archmage, or cause a magic-user who does not know you well to follow a prescribed course of action based on your advice if the question is one of Arcane knowledge."

to:

"Your ancestry can be traced to dragons, warriors, or another such powerful group. As such, you command the respect of those who respect your heritage. Choose an area of expertise, such as Arcane, Political, or Combat. You are assumed to have knowledge and a destiny for greatness in the chosen area of expertise, and others treat you with deference. This influence could guarantee your placement within an Arcane College, grant you a mentorship under a famous Senator, or cause a Lieutenant who does not know you well to follow a prescribed course of action based on your advice if the question is one of the selected area of expertise."

**Comment by brianfeister** [comment]
I'd rather keep fantasy in there than have something bland replace it. I think what we actually need is a word other than "extraordinary" to replace "arcane"

How about "legendary bloodline" I don't think "warriors" is flavorful or epic enough.

**Comment by brianfeister** [comment]
Use "void Templars" (a sci Fi thing I made up) in there as well.

**Comment by Hassurunous** [comment]
Illustrious Bloodline/Legendary Bloodline

"Your ancestry can be traced to dragons, void templars, a political dynasty, or another such powerful group. As such, you command the respect of those who respect your heritage. Choose an area of expertise, such as Arcane, Political, or Combat. You are assumed to have knowledge and a destiny for greatness in the chosen area of expertise, and others treat you with deference. This influence could guarantee your placement within an Arcane College, grant you access to the Templar libraries, grant you a mentorship under a famous Senator, or cause a Lieutenant who does not know you well to follow a prescribed course of action based on your advice if the question is one of the selected area of expertise."

Trying to include examples that are less fantasy-oriented, hence the "political dynasty" addition. Void Templar still sounds pretty fantasy-esque to me, so I wanted to make sure we included at least one example that was genre-agnostic.
