### ISSUE TITLE
Reword Nature's Ally and Whisperer of the Wild

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#350]
These are two more perks that are almost exclusively tuned to fantasy settings. 

Nature's Ally should reflect that it intends what is "natural" to the setting. In a cyberpunk scenario, this might be droids instead of small animals, for example.

Whisperer of the Wilds should be the same. Perhaps instead of talking to a plant, you are jacking into a phone terminal to see if someone just called a number, or you are checking the stones for signs of recent alchemical mutation.

If someone doesn't beat me to it, I'll post a suggested rewording tomorrow.

**Comment by brianfeister** [comment]
This one is going to be really hard to reflavor and I'm likely to keep it without changing. We don't need "no fantasy" we need "more non-fantasy"

**Comment by Hassurunous** [comment]
Nature's Ally

Current Wording: "Creatures of nature can sense your deep respect for the natural order. Wild animals give you a wide berth, Druids give you the benefit of a doubt by assuming that you do not have destructive intentions, and you can typically gain an audience with the chief of a small local tribe by virtue of your reputation for defending nature."

Suggested Change: "Perhaps you are a preservationist, seeking to bring more green to your dystopian cyberpunk world, or maybe you are a hermit, in touch with the animals and plants of your fantasy forest home. Whatever your circumstance, the common people and creatures of your land can sense your deep respect for the natural order. Wild animals are more receptive to your desires, Druids give you the benefit of the doubt by assuming you do not have destructive intentions, and you can typically gain an audience with the leader of a small local tribe or faction by virtue of your reputation for defending nature."

It's a simple change, but it gets people thinking about Nature's Ally in a non-fantasy setting, which I think is valuable. 

Whisperer of the Wild
Current Wording: "Once per game session, you can ask a single “yes” or “no” question of a plant or animal within earshot. The plant or animal automatically trusts you at least enough to answer the question truthfully. You receive the answer by way of an inner sense, and so this ability cannot be used for further two-way communication."

Suggested Change: "You have an innate connection with the world around you. Once per game session, you may ask a single "yes" or "no" question of a plant, animal, or other environmental object within earshot and receive a truthful answer by way of an inner sense. This does not facilitate further two-way communication. The GM decides the nature of the response, perhaps via discovery of fingerprints to prove that someone recently used a phone, a sense of familiar magic, or anything that fits the narrative of the campaign."

Whisperer still sounds a bit too "fantasy", but I'm still working on it. Just wanted to jot down a couple ideas in case anything helped spark some creativity. 


To be clear, I'm fine with leaving them as they are if we are okay with "fantasy-only" perks. Given that there are no real "fantasy-only" flaws, however, and we have removed most "fantasy-only" elements from the gameplay, I thought it prudent to bring up these two Perks.

**Comment by brianfeister** [comment]
I'm good with the first one, but `Whisperer of the Wild` shouldn't have "fingerprints show up on a phone". That one is fine as is, there are terrariums and potted plants on spaceships, and there are planets that still have vegetation in a sci fi setting.

**Comment by Hassurunous** [comment]
Was mostly just trying to steer away from plants and animals because talking to plants feels very fantasy to me and wouldn't really fit in a cyberpunk (by my own understanding), but it's flexible enough that I don't think it matters. In cyberpunk, just go talk to the rats or something. lol

**Comment by brianfeister** [comment]
LOL, exactly.
