### ISSUE TITLE
Sentinel

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#351]
The title should read:
Sentinel I-III

Right?

Also, a suggested re-wording on the description:

For each tier of this feat, each round, you get one free defend interrupt action. Your free defend interrupt action(s) may not be used to perform any other type of action. Your free defend interrupt action(s) do not cause you to lose your usual major action on your next turn.

At Tier III, this means you gain 3 FREE defend interrupt actions. In addition you may use another defend interrupt that would take away your major action on your next turn.

**Comment by brianfeister** [comment]
Yeah, need to add the "I - III" bit, but I'm not a fan of this wording.

**Comment by BuildAndDie** [comment]
reasoning? Right now the wording is a little wonky.

**Comment by BuildAndDie** [comment]
For each tier of this feat, each round, you may make one free defend interrupt action without losing a major action the next time your turn in the initiative order comes up.

**Comment by brianfeister** [comment]
"For each tier of this feat, each round, you get one free defend interrupt action"

means the same as the following but has  a clumsy conjunctive "For each tier of this feat, for each round..." Too many words to close together

"Each round, you get a free defend interrupt action"

But the latter is simpler. If it has tiers, then the stacking is implied or there would be no tiers.

"At Tier III, this means you gain 3 FREE defend interrupt actions. In addition you may use another defend interrupt that would take away your major action on your next turn"

Basically, I just feel the opposite that you do about it and that people who need it spelled out are being pedantic and I don't want to cater to that. There really isn't a clear problem with the current text RAW. Let's stick much closer to it. In fact, I can't see a reason to change it:

"Each round, you get one extra major action which can only be used to perform a defend action. Using this extra action prevents you from losing the next major action you would have spent to perform a defend action. Multiple tiers of this feat allow you to take multiple defend actions without losing your usual major action on your turn."

**Comment by BuildAndDie** [comment]
yeah.. but really you are not getting a major action....

Wording it as "free defend interrupt action" I feel is much more accurate to what is happening.

**Comment by BuildAndDie** [comment]
Each round, you get on free defend interrupt action without losing your major action the next time your turn comes up in the initiative order. Multiple tiers of this feat allow you to take multiple defend actions without losing your usual major action.

**Comment by brianfeister** [comment]
You **are** getting a major action. Read the combat chapter under interrupts. An interrupt is an action that uses your next major action. So, but giving a major action that can only be used for a Defend Interrupt, we're sticking to RAW.

**Comment by brianfeister** [comment]
@BuildAndDie I was about to go more your direction, but RAW yours doesn't work. It needs to be a Major action. If it's free, then it works while Stunned, which is not the intent. If you're Stunned, it doesn't work.

**Comment by brianfeister** [comment]
Ok, how about:

"Each round, you get one extra major action which can only be used to perform a defend interrupt action. Using this extra action prevents you from losing the next major action you would have spent to perform a defend action. Multiple tiers of this feat allow you to take multiple defend actions per round without losing your usual major action on your turn."

**Comment by BuildAndDie** [comment]
Well, then with the current wording, you are admitting that Haste can work with defend interrupt, which earlier you said it couldn't. Because now you are admitting you just need major actions, which haste gives you three of potentially.

Earlier you also said that defend itnerrupt was unique and doesn't interact the same as other things.

**Comment by BuildAndDie** [comment]
you could just word it as:

Each round, you get one defend interrupt action without losing your major action the next time your turn comes up in the initiative order. Multiple tiers of this feat allow you to take multiple defend actions without losing your usual major action.

take away FREE

**Comment by BuildAndDie** [comment]
and with stunned, technically i have anything that is free then..... So boon focus III works and I can take a major action? Maybe stunned just needs re-wording then?

**Comment by brianfeister** [comment]
I see, thanks for explaining. Actually the problem is that I got mixed up and thought the wording fix for MAS was somehow involved with Haste as well.  

Can you remind me why Haste should not be used with Defend actions? If we're giving this capability to attackers, wouldn't it be symmetrical to do the same for defend character builds? I just don't recall the argument against Haste for Defend?

**Comment by BuildAndDie** [comment]
it is all about debt.

if a person uses 3 defend interrupt b/c they have haste, and before their turn comes up they get nullified or slowed, then they suddenly have a debt they can't spend.

and having to figure out the debt economy was bad in that case.

**Comment by brianfeister** [comment]
Ah, yes. That was it.

**Comment by brianfeister** [comment]
Actually Boon Focus III only works because you spent 9 feat points on it. The keyword `Free Action` should be **VERY** rare, but in the case of Boon Focus III it's intended.

**Comment by brianfeister** [comment]
So, because of how `Interrupt` type actions are worded, I think we need to specify in `Haste` that the actions can't be used for `Interrupt`s and that seals it off

**Comment by BuildAndDie** [comment]
Man... I just realized... if you use your defend interrupt, and then get stunned, you can't do anything. Gotta wait a full turn to be able to have your move action to resist stun.

**Comment by BuildAndDie** [comment]
that could work for adding it to the Interrupt wording.

**Comment by brianfeister** [comment]
LOL, that's intended with losing your next turn from `Stunned` if you `Defend`

**Comment by BuildAndDie** [comment]
yeah, just realizing how good that would be vs my players, muh hahahaha

**Comment by BuildAndDie** [comment]
by the way, what did you think of this wording, not sure if you missed it with us posting at the same time.

Each round, you get one defend interrupt action without losing your major action the next time your turn comes up in the initiative order. Multiple tiers of this feat allow you to take multiple defend actions without losing your usual major action.

**Comment by npavlinsky** [comment]
That looks great!

**Comment by brianfeister** [comment]
@BuildAndDie getting close. Question. With this wording, does it imply that if I'm first in the initiative order I can't use my free Defends later, since it falls outside of the "each round" bucket since my "next up" is not during this round?

**Comment by ucffool** [comment]
@BuildAndDie Defend should always be capitalized when referring to the action, just FYI.

**Comment by BuildAndDie** [comment]
@brianfeister I would say the current wording already implies that. Even if you didn't have Sentinel.

**Comment by BuildAndDie** [comment]
I mean, you would still have the Defend, but it would take away from your next round, not this one. And if that wasn't the case you could in theory build up Defend, which doesn't make sense.

**Comment by BuildAndDie** [comment]
Another question. Do some of the feats need to be looked at for cost now that you can do more than 1 defend? Defensive Reflexes only be 2 feat cost.

Lots of discussion on whether the additional defend actions should have some sort of disadvantage like haste or MAS with more than one action. I think it might be fine as is, but I understand the talk that it could be more powerful.

**Comment by brianfeister** [comment]
Yeah I understand the discussion around it. But I made the bonus action cost 3 for that reason. I think Advantage on it is still weaker than multiple attacks. It just wouldn't be right to make advantage on Defend cost the same as Advantage on attack

**Comment by BuildAndDie** [comment]
Another question, should Stun, in relation to this conversation say: You only get one Major, Move, Minor, or Interrupt action" or is the wording already good enough for that?

**Comment by BuildAndDie** [comment]
if Defend is in fact powerful now, one way to change that is that you DO use your major action first, but still have other ones. This way the big drawback to defend still exists (you lose your major action), but you have additional ones you can use.

Some suggestions of this on discord chat.

**Comment by npavlinsky** [comment]
@brianfeister To answer your question " Question. With this wording, does it imply that if I'm first in the initiative order I can't use my free Defends later, since it falls outside of the "each round" bucket since my "next up" is not during this round?"
I would say it does not at all, since you are no longer gaining actions on your turn to use, you are instead now just gaining the ability to X times per round make a defend action without incurring the normal action debt.

**Comment by npavlinsky** [comment]
I also Agree with @BuildAndDie to say we should consider changing this to force the defender to First use their Major action before dipping into those freebees.

**Comment by ucffool** [comment]
Except that goes against the whole reason for it... to be able to Defend once without losing your Major Action. That needs to be the case for at least the first Defend in a round.

**Comment by BuildAndDie** [comment]
the point of the more defend is to... have more defends. Not that it doesn't take away from your major action

**Comment by brianfeister** [comment]
@ucffool @BuildAndDie I'd argue that it helps with balance since the Defender build now has two advantages:

1. The feat that grants it does so without a penalty like the Multi-Attack feat does
2. The feat to get Advantage on attacks (attack spec.) costs 3 while Defensive Reflexes costs 2. 

So this would balance it out

**Comment by ucffool** [comment]
Throwing up my hands. I realistically don't have as much skin in this game and I'll just look over the changes when they happen for typos or clarification (like with the latest Companion change). ;)

**Comment by brianfeister** [comment]
@BuildAndDie this phrasing actually allows the feat to work when you're `Stunned` which is not my intention:

> Each round, you get one defend interrupt action without losing your major action the next time your turn comes up in the initiative order. Multiple tiers of this feat allow you to take multiple defend actions without losing your usual major action.

I'm going with this:

> Once per round when you use the defend action, you get an additional major action that can only be used to make another defend action. Multiple tiers of this feat grant additional major actions usable only for defend actions.

**Comment by BuildAndDie** [comment]
cheer!

**Comment by npavlinsky** [comment]
@brianfeister But That seems problematic as wording as well, because you dont use major actions to defend, you lose your next major action. So that language doesn't make sense. 
Also, nothing in the interrupt action text excludes you from using Defend when you are stunned as it is written now. 

The better text would be a combination of the two, as I like how you made using a defend action a requirement to gain the extra defends, something like:
Once per round when you use the defend action, you may make an additional defend interrupt action without losing your major action the next time your turn comes up in the initiative order.Multiple tiers of this feat allow you to take multiple additional defend actions without losing a major action.

But the Interrupt action text still needs to be reworked, the entire indebted mechanic of it makes it a difficult nut to crack, cause you need some text in there that prevents the player from using that action if they would not be receiving that action next turn.

**Comment by brianfeister** [comment]
@npavlinsky Ok, does this work for you?

> Once per round when your next major action is expended to perform a defend action, you get an additional major action that can only be used to make another defend action. Multiple tiers of this feat grant additional major actions usable only for defend actions.

**Comment by npavlinsky** [comment]
How about:
Once per round when your next major action is expended to perform a defend action, you get an additional major action _on your next turn in the initiative order_ that can only be _lost_ to make another defend action. Multiple tiers of this feat grant additional major actions _that can only be lost_ for defend actions.
Keeps it more consistent with the Language of Interrupt actions.

**Comment by brianfeister** [comment]
this part is quite dense and difficult to read:

> additional major action on your next turn in the initiative order that can only be lost to make another defend action

**Comment by npavlinsky** [comment]
It seems like you need to specify that the action is gained on the PC's Turn, and not outside that turn, as the rules for combat assume actions are always gained on their turn, and either used or not.

**Comment by npavlinsky** [comment]
There was a comment on Discord 
"In all other instances of using or gaining actions, the timeframe for gaining and losing them is clear. For regular actions, they refresh each turn. When you gain them with haste or multi-attack, they last for that turn. For regular defending, you use up the major action of your next turn. In this case, however, there is no such specified time constraint."
And the someone felt on discord they could save up and stack up those additional actions.

**Comment by brianfeister** [comment]
When I read yours I hear 

"AFTER my next turn comes around I get an extra major action to defend."

But it's supposed to say

"BETWEEN NOW AND THE START OF YOUR NEXT TURN"

Are you sure that you're not trying to change this due to a misunderstanding of my intention for the rules?

The goal is this:

1. I spend my next turn's major action to do a defend action
2. The defend action has already spent my next turn's major action
3. I don't recover the major action I spent, but I **do** get a bonus action to do another defend as long as I use it prior to my next turn.

**Comment by brianfeister** [comment]
I honestly am considering not making any changes to this, it's getting too pedantic. There is absolutely zero evidence that actions can be stored or saved. The rules say nothing about it anywhere, and that is a total misunderstanding of the RAW. I'm not going to turn the rules text into an FAQ for silly misreadings that can't be gleaned from the RAW of the text.

**Comment by npavlinsky** [comment]
No, my intent is the same, The way my text is written , you make the defend, you lose your next major action, you then gain another major action that you will receive in your next turn, which you can now make other defend actions against.

**Comment by npavlinsky** [comment]
Well your last suggestion is good, the only thing that really bothers me is the use of the word USE as you can only use actions on your turn, and Interrupts actions are made by losing actions , not using them.

**Comment by brianfeister** [comment]
@npavlinsky Alright, here's the final

> Once per round, after you have expended your next major action to perform a defend action, you get an additional major action that must be spent before the start of your next turn to make another defend action. Multiple tiers of this feat grant additional major actions usable only for defend actions

**Comment by npavlinsky** [comment]
It kind of has to say "must be spent before the _end_ of your next turn" instead of the start
Because Interrupt Action says "you lose your major action the next time your turn in the initiative order comes up."  So it cant happen before the start of your next turn.
