### ISSUE TITLE
Nullify > Barrier > Darkness

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#354]
How is Nullify suppose to interact with Darkness and Barrier, which target an area.

What is the resolve of the area that Nullify needs to have for the CR?

**Comment by BuildAndDie** [comment]
Also.. Barrier

if Impassable, what happens if it is cast on the area that a person is standing. They are essentially Immobile now, but no resist rolls?

Do they get shunted out?

**Comment by brianfeister** [comment]
@BuildAndDie good question about Impassable - that needs a fix. Should we say that "Impassable = you can't place the barrier in a square if a creature is present" - OR - "Impassable = creatures are shunted out" ? ... suppose it makes no difference. I'll go with "shunted out"
