### ISSUE TITLE
Truthfulness Bane

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#355]
it says:

When a target resists the bane, you cannot target them with this bane again for 24 hours.

However there is no resist on this bane as listed currently.

I figure either there is suppose to be a resist on it, or the wording is suppose to be that if you fail to beat their resolve, they are immune for 24 hours.

**Comment by brianfeister** [comment]
It's quite powerful in bypassing the usual "Resist Ends" and not allowing a Resist roll to shake it off. Tough call there

**Comment by brianfeister** [comment]
Nah, no more changes, I'll fix the "when they resist" part
