### ISSUE TITLE
Feat Pre-Req

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#356]
I fully admit I could be interpreting this completely wrong.

It is my understanding that if a Feat as an Attribute pre-req for it, then in order to accomplish what the feat says it does, you need to use the attribute to accomplish it.

For example, silencing strike says pre-req has Agility

This, to me, means you should only be able to apply silencing through an agility/percise attack.

This is also like the old feats of battlefield punisher, which had pre-req of Might and/or Agility. You shouldn't have been able to use Protection to do the battlefield punisher feats.

Maybe I'm wrong on that, but if I am not, we need to add some wording in the feats section under pre-req the reflects this.

that or silencing strike needs further clarity in it that says only percise attacks.

**Comment by brianfeister** [comment]
Correct. Protection does not allow you to do the "Damage Reflection" trick via the **Battlefield Reflexes** feat.

**Comment by ucffool** [comment]
Wait, why would `Protection` which is `Any Extraordinary 4` not allow you to benefit from **Battlefield Reflexes** feat? You're not making an attack, you're placing an invisible barrier in front of someone and maybe it has magical backlash that demoralizes (read: reduces HP) the attacker.

**Comment by BuildAndDie** [comment]
he mistyped some of that, Protection can benefit

**Comment by BuildAndDie** [comment]
we cleared it up in discord chat.

He was more referring to Silencing strike and tthe old Battle field Punsher/Sentinel feats

**Comment by BuildAndDie** [comment]
so Silencing strike will have something added that it has to be precise attacks to trigger the silence.

The old Battlefield Punisher - Knockdown should have said forceful/precise attacks

**Comment by brianfeister** [comment]
Closing the books on this one. `Silencing Strike` now specifies `precise damage`
