### ISSUE TITLE
How does multi bane specialist work if the banes target different defenses?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#36]
I'm kinda thinking it might make sense to require that you can only choose two banes that target the same defense. That way you avoid weird combos of Charm and Knockdown and the such.

**Comment by brianfeister** [comment]
The problem with "Charm + Knockdown" as an example is that it violates a limitation that is implied but needs to be stated. There is no attribute that can trigger both of those banes. We definitely need to require that multi-bane attacks need to be two banes accessible with the same attribute. But targeting the same defense I think is problematic. 

"Blinded + Forced Move" is a very reasonable combination for an `Energy` wielder. One targets Evasion, one targets Toughness. I would vote for just sidestepping realism in favor of simplicity here and having the attacker choose. Also, keep in mind that this "bug" is already in the rules in a sense. We need to add this to the core rules, but when a damaging attack is made against Toughness, it's overly complicated to restrict triggerable banes to the intersection of both the attacking attribute and the target defense. You can attack Toughness but still trigger a bane that targets Evasion. The target defense is only used for bane attacks, which I propose we allow the attacker to decide with multi-bane specialist.

**Comment by istabosz** [comment]
I like that the attacker picks the defense. That was actually my first inclination.

You mentioned that the combined banes both need to use the same attribute. That wasn't in your original write up. In fact, you had explicit instructions on what do do if they didn't use the same attribute.

Is that something you'd like me to change?

**Comment by istabosz** [comment]
Nevermind. I re-read your post and see that you do want to change that. The feat has been updated to reflect needing a common attribute and that the attacker gets to choose the defense.
