### ISSUE TITLE
Submachine Gun and M16

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#360]
The Submachine Gun and M16 example on the weapon table in Chapter 5: Wealth & Equipment have the "Provoked" bane attached to them, even though agility doesn't give access to provoked. So that bane needs to be removed from these weapons.

**Comment by istabosz** [comment]
I think the more fitting solution is to add Agility to the provoked bane. Definitely seems like you should be able to provoke someone with a deft strike just as much as a powerful blow.

@brianfeister Does that sound good?

**Comment by brianfeister** [comment]
Yup. We agreed to this at the last Moderators meeting.
