### ISSUE TITLE
"Getting into and out of armor" heading rendering improperly on website

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#361]
![image](https://cloud.githubusercontent.com/assets/20313287/24315733/47288a7a-10bf-11e7-9124-2a527a5e0b77.png)

Not sure why this is happening. I checked the code and everything looked good.

**Comment by ucffool** [comment]
Funny enough, that also needs to be updated since 1 level of Fatigued is disadvantage 1 to all *non-attack* action rolls.
