### ISSUE TITLE
Sworn Enemy

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#362]
Hey @brianfeister 

We had been talking about this some. Wanted to bring it up to remind.

https://openlegend.mightybell.com/posts/1068375/comments/1166107

**Comment by brianfeister** [comment]
After some thought, this is going to be ruled as "foul ball", the existing feat is not broken or wrong. It's a perfect way to make a "Ranger Favored Enemy" that gets huge bonuses (only 1 feat point per tier) to non-combat rolls against an enemy they have carefully studied.
