### ISSUE TITLE
Clarification on "sword and board" not gaining adv1 from one-handed melee weapon

### ISSUE THREAD

**Issue by trioderegion** [openlegend/core-rules#367]
This is mainly an issue of clarity.  As per the discussion found here: https://openlegend.mightybell.com/posts/1074407/comments/1172054

The interaction between a one-handed melee weapon being used with a shield vs another melee weapon is a bit unclear in that the adv1 from a one-handed weapon is nullified if you are wielding any weapon with the defensive property.

I am not sure what should be re-arranged or re-worded (if anything), but having the mechanics for "sword and board" being split so far apart in the core rules (one in weapon categories and one in weapon properties) makes it very easy to overlook.  This is a rather important point because many character concepts will be built around their fighting style (2-handed, dual wield, sword and board, sword and spell).

**Comment by brianfeister** [comment]
I can understand this perspective but don't currently have an idea for how to implement it. If no one has an idea, it will probably ship as is without a change.

**Comment by BuildAndDie** [comment]
Currently:

One-handed Melee - The weapon uses a single hand and allows the other hand to be used for carrying another object, second weapon, or kept free for other actions. When wielding a one-handed weapon in each hand, you gain advantage 1 to all melee attacks. If both weapons you are wielding have passive benefits such as the defensive property, use the best of the two benefits; they are not added together.

Suggested:

One-handed Melee - The weapon uses a single hand and allows the other hand to be used for carrying another object, second weapon, or kept free for other actions. When wielding a one-handed weapon **without the defensive property** in each hand, you gain advantage 1 to all melee attacks. If both weapons you are wielding have passive benefits such as the defensive property, use the best of the two benefits; they are not added together.

**Comment by trioderegion** [comment]
Simple and plainly links the interaction between these two modifiers (one handed and defensive).  While we are on that paragraph, there could be some additional clarity on not stacking duplicate weapon passives:

Currently:

If both weapons you are wielding have passive benefits such as the defensive property, use the best of the two benefits; they are not added together.

Suggested:

If both weapons you are wielding have **a common passive benefit, such as the defensive property, use the better of the two; passive weapon benefits do not stack.**
