### ISSUE TITLE
Does supernatural presence still fit as a feat?

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#37]
Since this feat is so fluffy, do you think it should instead be re-written as a trait when we get to those?

**Comment by brianfeister** [comment]
Yeah, I think that's a great plan. It should be a "Perk" when we do Perks & Flaws.

**Comment by brianfeister** [comment]
But we probably need to leave this issue open and let it stand until we have those rules available to players.

**Comment by istabosz** [comment]
Agreed.

**Comment by vehemot** [comment]
Hi guys. I had the same thought as istabosz when I first read the Supernatural Presence feat. If it were to come to a vote my vote would be classify it as a trait/perk.

**Comment by istabosz** [comment]
Thanks for bringing this one back to the light, @vehemot 

I've made this change.
