### ISSUE TITLE
Heightened Invoc Typo and Question

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#376]
Tier 2 says:

You can lead others to join you in group invocation as long as they are also able to invoke the bane or boon at the same power level that **you're are** invoking it at.

Either contraction taken out or the are.

For Tier 3, it mentions group, but doesn't mention any benefit of having more than 2 people be the group. Is this intended, or is there a minimum that was suppose to be mentioned based on the power level of the bane/boon?

**Comment by BuildAndDie** [comment]
Also in Tier 3, under dispel boon

Dispel Boon - Make an Entropy roll with a Challenge Rating equal to 10 + twice the power level of the boon you are attempting to dispel. If successful, you cause a permanent boon to be forever stripped from the target, causing them to lose the ability to invoke the **bane** automatically.

Bane should be boon.

**Comment by istabosz** [comment]
Fixed this via d9cbd20

I'm assuming that we don't need a group invocation for the bestow/dispel bane and boon effect. It seems like that is something that a powerful mage or mad scientist should be able to do on their own. I think group invocations are just meant for the tier 1 effects. Correct me if I'm wrong @brianfeister

**Comment by brianfeister** [comment]
Yup, agreed we don't need group invocation for the higher level one.
