### ISSUE TITLE
Attack Redirection

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#377]
Description and Effect don't match.

Description says "you can use your opponents' attacks against themselves" leads one to believe you can attack the attacker with it. Sure you can dig deep into the meaning and say that it works against the attacker b/c it ends up hurting his allies, but a quick read of it will not lead to the right conclusion.

Perhaps instead:

You are adept at redirecting your enemy's attacks. Whether using fancy footwork, magical force, or tactical superiority, you can use your opponents' attacks against **their allies**.

or something similar

**Comment by BuildAndDie** [comment]
Also, typo for Niether

should be neither

**Comment by istabosz** [comment]
Closed via 8c10d1e
