### ISSUE TITLE
Ferocious Minions

### ISSUE THREAD

**Issue by npavlinsky** [openlegend/core-rules#381]
"Creatures under the effects of your charmed or dominated banes, or those created by your invocation of the summon creature boon, gain advantage 1 on all attack rolls to defend or act in your favor you for each tier of this feat you possess."

Two things with this
1.) I assume this meant to say "to defend __you__ or act in your favor ~~you~~"
2.) "or act in your favor" is very ambiguous, pretty much anything could be considered to be in your favor if you justify it. Is there a specific intent for this that is not coming through in the text? Or is it meant to be very open to interpretation?

**Comment by istabosz** [comment]
Fixed the typo. I think this one is meant to be open to interpretation. Basically, your minions are better at attacking in all sorts of situations.
