### ISSUE TITLE
Non-extraordinary Boons and Banes

### ISSUE THREAD

**Issue by SamWilby** [openlegend/core-rules#386]
There is currently no ruling for how to target non-extraordinary boons and banes, but the bane examples in chapter 7 seem to assume they're following the same as the extraordinary attributes 

> "The dragon’s Presence is 8, giving him a range of 75’"

However, this ruling causes problems for physical attributes; such as inflicting Blind with Agility from 75' away with no equipment. The suggested fix is to make Physical attributes follow weapon targeting rules for banes and Non-Physical attributes follow the rules for Extraordinary attributes currently written in Chapter 7
![image](https://cloud.githubusercontent.com/assets/26345039/25014601/638f78ca-2070-11e7-8ff9-12bc8613a165.png)

**Comment by SamWilby** [comment]
Potential problems with this suggestion are the Fear and Provoke banes which target Resolve, meaning that it doesn't make much sense for them to be restricted to weapons. I currently have no thoughts for fixing these beyond removing the physical attributes from them; I'm open to suggestions.

**Comment by SamWilby** [comment]
### Decision from April 14th mod meeting, okayed by @brianfeister 
- Banes invoked with physical attributes require a weapon (including unarmed) 
- Demoralised, Fear and Provoked will have special exceptions written in to allow them to be invoked at range.
- Banes invoked with other attributes follow the range rules from the "Extraordinary Attack Range"  table in chapter 7 which should be renamed to "Non-Physical Attack Range" (placeholder name)

**Comment by brianfeister** [comment]
I want @istabosz to weigh in on this

**Comment by istabosz** [comment]
I am on board with the proposed changes above. I can implement them in the text.

**Comment by istabosz** [comment]
Proposed changes have been implemented
