### ISSUE TITLE
Ambiguity around reach

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#393]
Ch 5 says:

> Reach - This weapon can be used to attack enemies 10' away.

While Ch 1 says:

> A large creature's reach is always equal to the length of its base. So, a giant with a 15'x15' base would have a 15' reach. Small creatures always have at least a 5' reach.

It seems like the Reach weapon property is written with a 5' reach in mind without taking larger creatures into account. Perhaps something like:

> Reach - The weapon extends the reach of your melee attacks by 5'.

Would achieve the intended effect on all creature sizes.

**Comment by BuildAndDie** [comment]
maybe... It seems like reach is intended to double your normal "reach". If a giant is wielding a scythe, for his size, it wouldn't just extend his reach by a small 5'

I think reach is meant to double your melee range.

**Comment by oconnor0** [comment]
I had considered that, and that could be written as something like:

> Reach - The weapons doubles the reach of your melee attacks - from 5' to 10' for medium and smaller creatures, from 10' to 20' for large creatures, etc.

My concern is that doubling the radius geometrically increases the threatened area so that reach for larger creatures is even more valuable - but maybe that is as intended.

**Comment by SamWilby** [comment]
I think doubling might be too strong. Increasing by only 5' may be a little weird for large creatures but prevents melee weapons wielded by large creatures from being nearly equivalent to ranged weapons wielded by smaller creatures.

**Comment by brianfeister** [comment]
Closed via https://github.com/openlegend/core-rules/pull/398
