### ISSUE TITLE
Weapons Table Issues

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#396]
I finally managed to go through the whole Weapons Table and check weapons' costs and the associated banes and I found a few mistakes, issues and I have a few suggestions for changes.

Let's start with the mistakes:

- Chainsaw can't apply **Persistent Damage** as a **Forceful Weapon**
- Flamethrower can't apply **Fear**, as it is a **Precise Weapon**
- Flamethrower **WL** should be **2** (1+2(Area)-1(Slow))
- Sniper Rifle's new **WL** should be **1**
- The Cannon's **WL** should be **1** (1+3(Area)-1(Slow)-1(Stationary)-1(Delayed Ready))
- Cannon's **Area** descriptor says **Square**, while it should be **Cube**

Suggestions:

- Add the **Heavy** propriety to the **Flamethrower**
- Give the **Cannon** the **Knockdown** bane, instead of **Persistent Damage**
- Add to the **Submachine Gun** an Area of **10' Line**
- Add **Heavy** to the **Tower Shield**
- Replace **Disarmed** with **Silenced** on the **Shiv**

Issues:

- The **Sawed-off Shotgun** attacks behave strangely in terms of verisimilitude, as they are ranged area cones. Maybe switch it to melee with a bigger Cone?

**Comment by BuildAndDie** [comment]
> Chainsaw can't apply Persistent Damage as a Forceful Weapon

I've always been bothered by the fact forceful can't do persistent damage. Doesn't make any sense to me. Internal bleeding is just as real as external, yes?

**Comment by JVanGo** [comment]
I guess, but it feels strange to me, because I have a hard time seeing how you would apply it purely as a bane. If you punch someone hard enough, then you might cause internal bleeding, which I would fit into "exceptional success", but else I have a hard time fitting it in.

**Comment by oconnor0** [comment]
A *greatsword* is *forceful* but seems like a gash from that fits nicely into *persistent damage*.

**Comment by JVanGo** [comment]
> A greatsword is forceful but seems like a gash from that fits nicely into persistent damage.

Oops, I did miss that one, so I'll add it to the list.

**Comment by BuildAndDie** [comment]
Greatsword is Forceful AND Precise, though it doesn't have persistent damage as a bane listed on the table.

He was just mentioning that it made sense for it to do that VanGo as an example of a forceful weapon that can do persistent damage.

Another example would be a mace, one with spikes. Yeah it is a forceful blow, that also might leave a hole or two.

Also, if an exceptional success can do the bane, then just attempting the bane directly can do it. That is just about imagination at that point. I mean, a great axe is usually forceful. I lay into you with one of those, it is quite forceful, but it has a blade too.

**Comment by istabosz** [comment]
Regarding weapons with banes that they can't inflict, I propose the following change to the banes column description (changes in **bold**): 

Banes indicate specific banes that the weapon is particularly effective at inflicting. **You may use the weapon to inflict the listed banes even if you are not using one of the attack attributes listed in the bane description.** When an attacker uses the weapon to inflict one of the listed banes, they may treat the power level as reduced by one for purposes of meeting bane invocation attribute prerequisites, which the attacker still must meet. In addition, if you make a bane attack with the weapon, you get advantage 1 on the attack.

**Comment by brianfeister** [comment]
Done. Also making note for posterity. The new rule is

`Deadly WL Adjustment =| 2 + *deadly* value `
