### ISSUE TITLE
Grammar Check

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#401]
@istabosz I changed our intro text because I have an illustration being worked on (forgive the ugliness, that's my hackjob Photoshop work to correct some things the illustrator did. But this is going to be the opening page illustration to accompany the text, so I modified the text to better suit the illustration. Since this is the **VERY FIRST** text people read, I wanted to run it by you for grammar.

![image](https://cloud.githubusercontent.com/assets/806536/25311077/a58562de-27c4-11e7-8417-5153e137e0a9.png)

> *Deep in the bowels of a long abandoned star freighter, a pair of rogues huddle around a massive stasis pod. A shadowy form drifts through the clouded liquid, just out of range for them to discern. One of them, covered head to toe in cybernetic implants, attempts to make sense of the hidden symbols, detectable only via ultraviolet spectrum.*
>
> *“Hold that UV beam steady!” he mutters to his companion.*
>
> *But his whisper is like a shout that shatters the perfect silence of the Zeta class cruiser's massive chamber, and soon the echoes are like a siren in the darkness. Pairs of red eyes awaken at the edge of the light, fires of malice that yearn to taste flesh once again. “Zak,” stutters the light bearer as she draws a shining six-shooter, “I don’t think this freighter is abandoned no more.”*

**Comment by brianfeister** [comment]
And here's another one to grammar check for the same reason, related to art direction and artist input:

https://github.com/openlegend/core-rules/commit/10e2ffa21634be85e13821ffd1bd32e3a094af65

**Comment by istabosz** [comment]
Got these cleaned up.
