### ISSUE TITLE
Surprise in initiative

### ISSUE THREAD

**Issue by Fenrisulfr774** [openlegend/core-rules#403]
In the Combat chapter, the rules for initiative and surprise seem to imply that surprised characters acting after non-surprised characters lasts for the entire combat, so if there are 3 characters A, B, and C with initiative rolls 11, 21, and 15 respectively and B is surprised, the order will be C, A, then B for the entire combat.

However, looking at issue # 314 where the old Surprised bane was removed, that bane had a duration of 1 round which implies to me that the way it used to work the order would have been C, A, B for the first round (when B is surprised), then B, C, A for subsequent rounds when the Surprise bane afflicting B wore off.

Is the "surprised" condition lasting for the entire combat an intended effect of removing the Surprised bane and its 1 round duration, or should the 1 round duration be added to the rules text of the initiative section in the Combat chapter?

**Comment by brianfeister** [comment]
Surprised is no longer a bane because it's a condition that the GM adjudicates, rather than the players initiating it. 

The condition is "instantaneous", it alters your initiative once and remains in effect throughout the combat.

**Comment by oconnor0** [comment]
@brianfeister The issue in the Discord around surprise had to do with ambiguity on its duration. Additional clarity along the lines of "The initiative order of combatants remains the same throughout the combat and does not change after the first round." might help to clarify.

**Comment by brianfeister** [comment]
I hear ya @oconnor0 unfortunately if we said every time "when we say X, we don't mean Y" the rules would become dense and more painful to read. 

There's nowhere that it's implied the duration is only one round. In fact I would suggest that **always** really does mean ALWAYS.

From the combat rules

>  Surprised characters **always** act after non-surprised characters
