### ISSUE TITLE
PL 4 missing in Phantasm bane

### ISSUE THREAD

**Issue by Binary-Four** [openlegend/core-rules#404]
[problem]
The phantasm bane defines a level 4 in the header but the corresponding effect is missing.

[suggestion]
A 10 feet cube would fill the gap between the existing power levels. E.g.:
`Power Level 4 - Manifest a 10' x 10' x 10' area phantasm`

**Comment by brianfeister** [comment]
Ok, that's a good suggestion. PL 4 is noted there because  of the ability to combine multiple different senses can result in 4, but you're right, that removes the confusion and jumping from 10' to 15' is quite reasonable
