### ISSUE TITLE
Error in charmed bane effect

### ISSUE THREAD

**Issue by Binary-Four** [openlegend/core-rules#405]
[problem]
In the major charm effect of the `Charmed` bane you can find following sentence.
`The attacker is unable to do anything to plot against the one who afflicted them, and will (at the earliest possible opportunity) tell their charmer of any rumored harm or danger coming their way.` Referring to the attacker at the beginning makes no sense.

[suggestion]
replace attacker with target, e.g.:
`The target is unable to do anything to plot against the one who afflicted them, and will (at the earliest possible opportunity) tell their charmer of any rumored harm or danger coming their way.`

**Comment by brianfeister** [comment]
Good catch. Will fix.
