### ISSUE TITLE
One word restriction in Dominated bane is too language dependend

### ISSUE THREAD

**Issue by Binary-Four** [openlegend/core-rules#406]
[problem]
Since I play this game in a different language than English, I found that I get different possibilities in different languages. My players also tended to search to much for some one word term to get what they want, leaving it all to spelling. But even with simple commands like "stop", "run" it there is too much room for interpretation.

[suggestion]
Instead of one word I suggest a simple and short command. This leaves it to the GM's where they draw the line whats possible in their setting with this bane. With the greater range of possibilities it would be also necessary to add a phrase to prevent players to make the target kill themselves. For example: 
`Lesser Domination - The target obeys a simple and short command until the end of their next turn. The dominated creature will do nothing that is an extreme violation of its nature.`

**Comment by brianfeister** [comment]
Short is very vague, each person's definition of that is going to be different. The goal is to remove ambiguity wherever possible. Also not getting what you want is intentional, as controlling someone else's body is VERY powerful.

**Comment by Binary-Four** [comment]
Yes, it would be more vague and possibly more powerful but the action the target performs has still to fit into one turn. Also you could only control one aspect of the enemies turn (you would have to stretch the meaning of "short and simple" very far to fit an "and" into a command). To prevent misuse like suicide of the target or other tasks that are complete against its nature, you need an additional phrase (see above).

To reduce the ambiguity, examples could be added like "drop your weapon!", "stop running!", "shut up!".

**Comment by brianfeister** [comment]
I guess I did forget about the one-turn limitation, though I think I would try to reduce ambiguity by simply say ing either 3, 4, or 5 word command.

**Comment by Binary-Four** [comment]
I agree. This should suffice for most languages and basic commands.

**Comment by brianfeister** [comment]
The spirit of Open Legend is to drive storytelling, and how the GM interprets the player's carefully selected word should drive the story forward. I don't want to add a caveat that states "kill yourself" is not allowed. By keeping it a single word, we avoid the ability to specify a "kill target", which in turns helps keep the interpretive power in the hands of the GM where i belongs.

**Comment by Binary-Four** [comment]
Well, you already have a similar phrase in the same bane:
>Greater Domination - [...] Every action which the attacker orders the afflicted character to perform which is in extreme violation of their nature gives the target a resist roll as a free action to break free from the effect. [...]

I formulated my suggestion based on this before: 
`Lesser Domination - The target obeys a simple and short command (about five words at most) until the end of their next turn. The dominated creature will do nothing that is an extreme violation of its nature.`

The definition of what exactly is against the creatures nature is completly up to the GM.

Also in my opinion the single word is restricting creativity to much. One word commands can mostly substituted or be outranked by other banes like disarm or incapacitated. Or players start searching for minutes to find the right word, stopping the game flow. Yes, it makes it more powerful but also more spontanious. First one can be probably mitigated by raising the power level to 6 and the second one brings most of the fun.

**Comment by brianfeister** [comment]
You didn't answer my main question: do we come up with a list of "the command cannot be x, y, z"?

That's my main objection

**Comment by Binary-Four** [comment]
No, that should be covered by `The dominated creature will do nothing that is an extreme violation of its nature.`. And with that its up to the GM.
