### ISSUE TITLE
Deadly and Tables

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#408]
Was Deadly meant to be dropped to only +1 to WL?

It seems like it drops a LOT of weapons down really low. I know we took off the minimum of WL 4 for a weapon with deadly, but I don't remember switching it to only +1.

Lots of the special weapon table is showing weapons with +2 per deadly on WL cost too.

**Comment by brianfeister** [comment]
Wow, I'm worried that some of this stuff is still being found. 😫

I need to look at git history to see when that slipped in

**Comment by JVanGo** [comment]
I still want to do a check up on the extraordinary items table, just like I did with the weapons table, because there were some mistakes reported. I'll see if I'll get to it today.

**Comment by oconnor0** [comment]
Powerful is +1 WL per value as well. Is that intended?

**Comment by JVanGo** [comment]
Oh man, the whole extraordinary table is an inconsistent mess. It will take me a while actually to make sense of it all...

**Comment by brianfeister** [comment]
I've decided on something that I've wanted to do for a long time. I've added a "Check with your GM" as the last for weapon creation. I've explained there that we can do whatever we want and we don't need to make a Sniper Rifle a Wealth Level 1 item. Because that's idiotic.

**Comment by brianfeister** [comment]
So, @JVanGo if you do start looking closely at the Extraordinary Items table, just make sure you're doing the OPPOSITE thing. Instead of doing the math on each one and correcting it to follow the math, add the "Step 5" in there which is the "use common sense" step where we verify that this follows the realistic placement of the item in the real world.

**Comment by JVanGo** [comment]
I actually don't understand exactly what you are saying here @brianfeister. I recalculated the items and posted the discrepancies in another issue. I don't know what settings you had in mind when building these and neither will have any other reader, so to the readers who notice these discrepancies it will look like mistakes. Also I haven't checked prices for frost emitting medieval armors in a while, so I can't factor those in. ;)

**Comment by brianfeister** [comment]
@JVanGo The only way they'll know that the Wealth Level calculations are wrong is if they read the "Build Your Own Weapon" section. If they do, they'll find the new "Step 5", which explains it ;)

https://github.com/openlegend/core-rules/commit/d97659561f57d00b976366af323a523eedf012f1#diff-ba8cf1dbb8cf106983785a8f630f6493R2628

**Comment by brianfeister** [comment]
Fixed via https://github.com/openlegend/core-rules/issues/411
