### ISSUE TITLE
"Check" vs. "Roll"

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#412]
I know this one may seem pedantic, but we refer to "checks" and "rolls" and if we want the game to be most easily understood by new players, I would propose we should be choosing one or the other and sticking with it. Personally I think every thing is a "____ roll" of some kind (action, logic, perception, attack. etc.), and perhaps never a "check". 

"Snitch makes a logic roll (CR 16) to determine..." rather than ""Snitch makes a logic check (CR 16) to determine..."

**Comment by brianfeister** [comment]
(I've done most of the conversion on my end, but I wanted to run it by you before I changed it.

**Comment by BuildAndDie** [comment]
I like roll better as well

**Comment by istabosz** [comment]
Agreed. I like roll better.

@brianfeister To confirm, do you need me to implement these changes? Or did you just want my opinion.

**Comment by brianfeister** [comment]
I think I should have it mostly good to go, mainly checking that you agreed
