### ISSUE TITLE
Lack of clarity in Jumping

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#415]
> TAKE SPECIAL MOVEMENT
Special movement includes climbing, jumping, swimming, and other movement that is typically more restricted than just running across the battlefield.
Jump. Make a Might roll. If you can’t get at least a 10’ running start, you have disadvantage 1.
For a long jump, you cover a number of feet equal to your roll.
For a high jump, you cover a number of feet equal to your roll divided by 2.

So, the first thing that is unclear here, it states 10' running start. Common sense to me is that doesn't apply to High Jump, but you could run and attempt to do a high jump, so I guess it makes sense to apply to both (disadvantage 1 if you aren't running)

Next, how does that 10' of movement even factor into it. Do you add that to your Might roll, or does what you roll assume the 10' of movement is included.

Mark runs 10' and then leaps.
Might Roll for 14.
Mark *moves* 24'
or
Mark *moves* 14', only jumping 4'

Not 100% sure additional clarity is needed, but I can see how it might be unclear. The way I read it, is, the 10' of movement is done before the jump, and whatever you roll is additional movement. But then perhaps that could be abused?

What if Mark runs 30' and then leaps. He gets the 30' + his might roll in movement. Does it needed to be added that you can't do MORE than 10' of movement before the jump?

**Comment by BuildAndDie** [comment]
And if a running start already has the advantage of 10' of extra distance covered, is the disadvantage even needed?

Maybe it just needs to say, you can move up to 10' before you jump or something?

**Comment by BuildAndDie** [comment]
Ok.. and then if you get movement BEFORE the jump, can you get movement after the jump.

If I do a standing long jump, can't I then move 10' after the jump just like I can do before the jump?

**Comment by BuildAndDie** [comment]
Jump.
Make a Might Roll. You may have up to 10/15 feet of movement either before or after the jump. If the movement is after the jump, you have disadvantage 1 to the might roll.

**Comment by istabosz** [comment]
I'm having trouble understanding the lack of clarity on this one. Your roll determines how far your jump is. If you don't get a running start (by moving at least 10') you have disadvantage on the roll.

**Comment by brianfeister** [comment]
I feel like we are way down the rabbit hole on this one. 

I think there's a question about whether or not you should be able to move beyond your speed by rolling really high on a jump check. My thought is that's fine since you could end up rolling really poorly or you could really well so it's a wash. 

As far as whether you move before or after or whatever I really think that's not a problem.

**Comment by BuildAndDie** [comment]
so someone can move 30' and then jump?

**Comment by BuildAndDie** [comment]
so if you don't care about moving before or after, thattt needs to be mentioned, b/c right now that isn't clear. all it says is "at least 10 feet", so it is unclear, and basically saying you can move your max and still jump.

**Comment by BuildAndDie** [comment]
So, to rein it all in, since my posts were so disjointed.

The current problem I see with how Jump is worded has to be with brand new people. Both of you and myself have been looking at and playing with the OL rules and mechanics, so the way it is worded make sense already to us.

However, when someone looks at the wording right now: "at least 10 feet". This means they can move more, but it isn't clear how much more. It wouldn't make sense that you can move 30 feet and then jump, but how much of that extra 20 can I do? All it mentions is before the jump, and nothing about after the jump.

I think what would make the most sense is saying that Jumping takes half of your movement. That solves all those issues and questions. If half your movement is used to Jump, that means you still have the other half to move before or after, since you can break up your movement. If you use 10' of half your movement before jumping, then you don't have disadvantage on the jump.

Only a line stating that the Jump uses half your movement is needed then.

**Comment by brianfeister** [comment]
I think jumping should be a normal "Move Action", not half. We do too much of "dividing things up into smaller parts" which in turn creates confusion. Here's my proposal:

> ### TAKE SPECIAL MOVEMENT
> Special movement includes climbing, jumping, swimming, and other movement that is typically more restricted than just running across the battlefield.
> **Jump**. Make a Might roll. You can move up to 10’ as part of this action to get a running start. If you don't, you have disadvantage 1.
> For a long jump, you cover a number of feet equal to your roll.
> For a high jump, you cover a number of feet equal to your roll divided by 2.

**Comment by infernodemon2005** [comment]
I think making a jump should be a full movement action that may include a 10 ft running start as the landing usually leaves someone a bit slow and clumbsy unless they are trained in propper landing techniques.

**Comment by brianfeister** [comment]
So you're agreeing with my proposal then @infernodemon2005 ?

**Comment by infernodemon2005** [comment]
yep... but I would say that the 10 ft running start is required instead of the "up to 10 ft" as they could then circumvent that disadvantage by just taking a 5 foot step before the jump.

**Comment by BuildAndDie** [comment]
I read it as:

you can move up to 10 feet (between 0 to 10 feet), but if you don't move 10 feet, you have disadvantage. So 5 feet would still be disadvantage.

**Comment by BuildAndDie** [comment]
Though I will say.. I think making the jump be half a move action seems simpler and less confusing overall.

We still have the problem of if you can move 10 feet before your jump, why can't you do so after your jump? The 10' of movement clearly states "running start before".

Having it as a half move, you then don't have to worry about saying "up to 10 feet", you just saying "if you having a running start of at least 10 feet"

@infernodemon2005 I don't think worry about "slow and clumsy landing unless they are trained" applies here, we are suppose to be talking about legendary characters aren't we? If you have the clumsy Flaw, sure.

**Comment by brianfeister** [comment]
@BuildAndDie If you say that "jump takes half your movement" that means it's more complex than my proposal, because my proposal just adds the requirement about the running start. Your proposal would still need to have the same bit added that I'm proposing.

"Jump uses half your movement, making it a super-complicated sub-movement, movement, a "half-action" because we decided that Major / Minor / Move needed to be divided up. But make sure you get a 10' running start or you'll take a penalty"

**Comment by BuildAndDie** [comment]
I think it is just a matter of perspective on this. As long as something is decided. I figured half-movement would make it far easier for other things to interact with it.

Right now with Climb & Swim it is easy since those are half your normal speed, so this way interaction with Feats or boons that increase your movement are easy.

Fleet of Foot (5/10/15) increased movement
or
Haste (10/15/20/30) increased movement

Both of these lose a ton with attempting to Jump. It makes since that neither would affect the actual jump, but to only have the jump + maybe 10 feet seems a loss since another character without the feat or boon could get the exact same as you easily. Or the fact that someone who is Slowed could make the exact same jump as you without any penalty.

**Comment by istabosz** [comment]
Here we go. I think this should fix the issue:

**Jump.** Make a Might roll. If you can’t get at least a 10’ running start, you have disadvantage 1.
For a long jump, you cover a number of feet equal to your roll.
For a high jump, you cover a number of feet equal to your roll divided by 2.
Distance covered by a jump is considered part of your normal movement, and thus limited by your speed.

While we're at it, I say we get rid of the running start stuff altogether. It only adds realism, not fun. And it's an unnecessary micro rule that a GM could ad hoc if they wanted to anyway.

**Comment by brianfeister** [comment]
LOL, this is a trainwreck. I actually think that it takes away from fun to limit it to your speed. You should be able to exceed your speed that's the whole point of exploding dice and "every roll matters".

My 10' optional running start included in the movement is actually a concession to make it more fun because if you roll low, you at least cover some ground, unlike if you roll a total of 4 and don't even move one square. 

Having jump take up half your movement is just unnecessarily complex if people have _haste_ or _fleet of foot_. 

**FINAL DECISION**

> **Jump**. Make a Might roll. You can move up to 10’ for free as a running start before to jumping, if you do,  you get advantage 1 for every 10' by which your speed exceeds 30'.
