### ISSUE TITLE
Mount and Vehicle rules?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#418]
There are no rules for Mount/Vehicle creation or for the Wealth Levels of the various Mount/Vehicle properties. I expect these rules would be similar to normal or extraordinary item creation, but with a few tweaks based on travel speed or damage levels, etc.

Should there also be rules/suggestions for how to damage the occupants of Mounts/Vehicles depending on what kind it is?

**Comment by brianfeister** [comment]
We're not going to do these in core rules. Perhaps a later rules release
