### ISSUE TITLE
Range Clarification 

### ISSUE THREAD

**Issue by Meerling** [openlegend/core-rules#42]
I have not completed the document but there is an inconsistency dealing with range. 
It is not stated what the numbers for range indicate. It could be assumed to be squares on the battlemap, centimeters on the battlemap, yards, feet, etc. 

In the Combat section, the table for Supernatural Attack Range seems to be the only place where it is clearly defined, as each entry is a number followed by the word feet. 

I would suggest that you perhaps use a commonly recognized mark for that. Most people use an apostrophe, such as in 20' away, though that's more of a keyboard cheat than the correct prime mark. I did find a page that clarifies the correct characters for ease of reference. I had not been previously aware it was properly called a prime mark. (http://practicaltypography.com/foot-and-inch-marks.html ) 

I believe using that format consistently throughout the documents will look better and reduce initial confusion, even among those in countries that employ the metric system.

**Comment by istabosz** [comment]
Thanks, @Meerling . To clarify, are you just talking about the ranged weapon table in Chapter 4? I just skimmed the combat chapter and it seems that we do indicate feet in most places using an apostrophe.

**Comment by Meerling** [comment]
Yes, I glanced at combat for something early on, but haven't actually read it yet. I'm just slowly going through it while getting distracted by other people/things here, and posting the stuff that seems odd or inconsistent as I encounter them. Sorry if I wasn't clear about that. :)

**Comment by istabosz** [comment]
K. Well, I think I caught all the instances in the equipment chapter, so I'll mark this as resolved for now. Thanks for all your help!
