### ISSUE TITLE
Chapter 7 : make a bane attack refers to a boon's effect instead of a bane's effect.

### ISSUE THREAD

**Issue by patgauvingeek** [openlegend/core-rules#420]
That is, a target cannot be inflicted with a bane it is currently suffering from, unless specified in the ~~boon~~bane’s effect (e.g. fatigued).

**Comment by brianfeister** [comment]
Merged, closing. https://github.com/openlegend/core-rules/pull/417

**Comment by ucffool** [comment]
@brianfeister  forgot to close
