### ISSUE TITLE
Attack Specialization Prerequisite Inconsistency

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#421]
Noticed this while updating the SRD.

According to feats.yml, the prereq is attribute score 1 from Tier 1 - 3, then it increases by 1 with each new tier.

On the website, this is rendering as "Tier 1 - 9: Agility 1, Might 1, or Any Extraordinary 1"

On the old SRD, the attribute requirement is equal to the tier.

Which should it be?

**Comment by brianfeister** [comment]
I liked the simplification I introduced so we didn't need 9 different bullet entires, but just 3.

**Comment by brianfeister** [comment]
Although I think there are 3 bullets and the website is rendering wrong.

**Comment by brianfeister** [comment]
Fixed in the PDF. Not fixed on the website.
