### ISSUE TITLE
Too many mad scientists

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#426]
@istabosz used "mad scientist" about 20 times in the core rules. Which is arguably 20 times too many, but unequivocally 17 times too many

**Comment by SamWilby** [comment]
As a mad scientist I appreciate the representation, but perhaps other kinds of scientists should be mentioned as well?
For example:

- insane scientists
- unhinged scientists
- crazy scientists
- biologists
- psychotic scientists

**Comment by istabosz** [comment]
*teacher voice* I'll let you know that the mad scientist was a core archetype of the original Deadlands. I've never played in a weird west game without a mad scientist. I don't think 20 is enough!

Okay. I'll get rid of them.

**Comment by brianfeister** [comment]
@istabosz hopefully you didn't start making changes on the `master` branch, I've committed the changes to `print-edition` just now. This is now in "massive edit for print production" mode, so everyone please be on the lookout for typos from me as I massively slice and dice and fit the text to the best print format.

https://github.com/openlegend/core-rules/tree/print-edition

**Comment by brianfeister** [comment]
Also, I do love how you've given so much homage to Deadlands, which I've always loved the idea of and still not played much. Can we make up a new name for them that we own instead of borrowing from Deadlands? Personally, when I read "Mad Scientist" I always picture Doc Brown from Back to the Future. If we make them feel less corny and more of the awesome Deadlands feel, I think I would have never objected. Obviously we can keep a few "Mad Scientist" references just as a Deadlands "Hat Tip", but maybe a name recognizable by those who aren't familiar with Deadlands.

**Comment by istabosz** [comment]
Haven't made any changes yet. When I do, where do you want me to make them?

I'll try to come up with a new name, but I imagine a lot of the references can probably just be removed without too much issue. Our engineer is pretty much a mad scientist, mechanically speaking.

**Comment by MarkVelthuis** [comment]
Aren't most "Mad Scientists" realy "Mad Engineers" anyway ? 
http://static.neatorama.com/images/2008-12/mad-scientist-mad-engineers.jpg
