### ISSUE TITLE
Natural Defense

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#428]
Currently Natural defense is worded in the Effect only mentioning Guard. The part that is there is clearly to help negate stacking with other feats, however it might could use an additional line about Toughness?

Current:

> When you are not wearing armor, you gain an armor bonus to your Guard defense. Your armor bonus is determined by your tier in this feat:

A suggestion (if it is even needed, which maybe it isn't?):

> When you are not wearing armor, you gain an armor bonus to your Guard defense. Your armor bonus **as well as your Toughness bonus** is determined by your tier in this feat

Or maybe "your bonus to armor and Toughness is determined"

**Comment by istabosz** [comment]
Good catch. I think the appropriate text should be as follows:

> When you are not wearing armor, you gain a bonus to your Guard and Toughness defenses.

That's assuming that the feat only functions unarmored, correct @brianfeister ?
