### ISSUE TITLE
Armor - Shield Advantage

### ISSUE THREAD

**Issue by Meerling** [openlegend/core-rules#43]
The footnote for Shields from the Armor table in the section Armor says: 

^ Grants advantage when using the defend or deflect actions.

This seems to not be consistent with the other mentions of Advantage where it is capitalized and has a value, though in this case I am guessing it's 1. 
I'd suggest it be changed to something like the following: 

^ Grants Advantage 1 when using the defend or deflect actions.

**Comment by istabosz** [comment]
Thanks. You also reminded me that we have combined defend and deflect actions.
