### ISSUE TITLE
Combat Momentum special?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#431]
Currently Combat Momentum says:

> If you have the Movement attribute, you can use the Teleport boon instead of a normal move.

Given Boon Access would it make sense to reword that to:

> If you have access to the Teleport boon, you may use it instead of a normal move.

**Comment by oconnor0** [comment]
I recognize that also allows for extraordinary items and other mechanisms that give Teleport access.

**Comment by brianfeister** [comment]
Seems reasonable. I'll do that
