### ISSUE TITLE
Companion across Alt form

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#433]
When we originally had the discussion way back when, and ended up including this line:

>  If you have spent feat points this way and would gain feat points from any other effect, those feat points are reduced by the number of feat points you have granted to your companion.

It was to help clarify things like Alt form, to make sure the Feat points were taken from both, and any other things that were similar to it, at least as I remember.

However, that line is only under Companion III. Should this line be moved out of Tier 3, and just part of the Companion feat as a whole, or did we intend that if you spent feat points on Companion it didn't cross over?

Some reason I remember that was part of the discussion as a whole, to make sure if you had a Companion + Alt form, then the feat points spent into Companion should be taken out of both forms, since the Companion should stay.

But we might have left that vague so it would be decided by the GM, for instances where the flavor of the companion might be that it doesn't exist across alt form changes.

Maybe a line like:

> If the nature of the companion would cause it to continue to exist when you would gain feat points from any other effect, then those feat points are reduced by the number of feat points spent on the Companion.

**Comment by JVanGo** [comment]
I think the solution is quite easy, just move the paragraph Jonathan mentioned to the special section, so people see it applies to all tiers of the companion feat.

**Comment by istabosz** [comment]
The reason it's only listed under tier 3 is because that is the only tier in which you are spending your own feat points. Tier 1 gets no feats. Tier 2 gets 3 feat points of their own. Tier 3 gives you the option to spend your own feat points to give the companion even more feats.

**Comment by brianfeister** [comment]
Indeed. It is correct as is. If we changed it, that would add confusion to Tier 2, which does NOT use your main character's feat points.

**Comment by BuildAndDie** [comment]
So, that didn't answer the original question, but it might have been worded poorly.

>Some reason I remember that was part of the discussion as a whole, to make sure if you had a Companion + Alt form, then the feat points spent into Companion should be taken out of both forms, since the Companion should stay.
But we might have left that vague so it would be decided by the GM, for instances where the flavor of the companion might be that it doesn't exist across alt form changes.

I have a character with Alt form & Companion on the Primary.

does the alt form lose the initial point investment into Companion from the Primary since the companion would still exist?

Stan the Man (Primary Form Level 2 = 9 Feat Points)
Alt form Tier 2 (4 feat points
Companion Tier 2 (4 feat points)

Stan the Machine (Secondary Form Level 2 = 6 Feat points)

OR, b/c of companion

Stan the Machine (Secondary Form Level 2 = 2 Feat points)

Again, the 2nd paragraph of my original statement might apply, that leaving it up to the GM is fine in this case. Was just wanted to double check the intention as well though.

**Comment by BuildAndDie** [comment]
For further Clarification:

Level 5 Stan the Man (18 feat points)
Alt form Tier 2 (6 feat points)
Companion Tier 3 (6 Feat Points)
Companion Tier 3 (6 Feat Points)

Secondary Form Stan the Machine (15 feat points)
Lethal Strike III (9 Feat points)
Death Blow II (6 feat points)

Stan the Machine uses the campanions from Stan the Man to activate Lethal Strike and potentially to gain additional advantage from flanking. Plus the Bolster Boon Focus from Companion 1, and Life Drain Boon Focus from Companion 2.
