### ISSUE TITLE
Fatigue > Restoration

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#434]
I might be wrong in my interpretation of this, so wanted to check, and maybe provide some clarification in the Fatigue bane itself.

> Unlike other banes, canceling this bane takes time and rest. [...] If the restoration boon is invoked, the character invoking it can remove one level of Fatigue (in addition to that removed by natural rest) if their attribute used to invoke restoration is between 1 and 6.

So since it already works differently than other banes for canceling, the way I read it you just need to succeed on the restoration, which would be a CR 12. [the way I look at it]

However, if you take it as restoration works, then Fatigued is a PL 5, so that means for Attribute 1-4, you would have a CR of 30, and for Attribute 5+ a CR of 20 to succeed.

**Comment by brianfeister** [comment]
Adding language to cover this would be not be worth it. You're right in that it might be ambiguously interpretted as "permanent" but we don't say that in **fatigued**. The only place a "permanent" bane is mentioned is in **Heightened Invocation**

**Comment by BuildAndDie** [comment]
Wait, what? Permanent wasn't even on the radar for me with this? 

What is the CR for an attribute 1 to use restoration successfully on fatigue? 

12 or 30?

**Comment by brianfeister** [comment]
Ok, wow what in the world is this?!

> if their attribute used to invoke restoration is between 1 and 6.

I didn't write this. @istabosz?

**Comment by brianfeister** [comment]
I hope this is an artifact of a time when things were less solidified because if it was added recently I'm really confused. Fatigues is PL 5 so removing it should be as well. Otherwise you just cheapen the value of the defensive attributes which you should have to have a high score for in order to cancel such a powerful bane

**Comment by BuildAndDie** [comment]
Well, no power level of done via battle trance or environment via GM, just straight given with no targeted defense.

 Plus there are no resist rolls for it. 

Plus restoration only works to remove 1 level of fatigue. 

Plus restoration  can only be used on a character one in a 24 hour period to remove fatigue. 

Plus, only other way to remove it is by spending a Full 24 hour period doing nothing. 

So lots of steep stuff to remove fatigue as is unless PL 7

**Comment by istabosz** [comment]
@brianfeister I've got no clue about that text in fatigued. Definitely not something I added.

**Comment by brianfeister** [comment]
@BuildAndDie While all of that is true, I've also run into a situation where the players had access to Creation to remove that 1 level of fatigue per day and it was **very** powerful. Made it very difficult for the GM to slow down the players. And in a system where we mostly use status effects to slow the players down since there is "unlimited healing", I think this should stay PL 5. 

Keep in mind that it confuses people when it says "PL 5" at the top and then later in the description it gives weird exceptions. I don't see a strong enough case to keep a very unusual exception.

**Comment by JVanGo** [comment]
@brianfeister This stems from a discussion over at the Discord server and I think this comes to a RAW versus RAI reading of the rules. Someone was upset that using, especially multiple times in one day, battletrance grinds adventuring to a halt as: 

> Unlike other banes, canceling this bane takes time and rest. Each 24 hour period of rest with little or no exertion removes one level of fatigue.

So a RAW interpretation would suggest that you can't adventure for the day after, while I think that RAI meant to say that you can only remove 1 level of fatigue per day after a long rest. As long rests are not a thing in OL and are not defined. So this has been my personal interpretation and if I'm wrong feel free to correct me, but here is a proposed rewording:

> Unlike other banes, cancelling _(I took the freedom the fix this typo)_ this bane takes time and rest. Resting for a prolonged amount of time, for how long is to be decided by the GM, with little or no exertion removes one level of fatigue per 24 hour period.

This is also more in line with the train of thought laid out later for the interaction between Restoration and Fatigue:

> A target cannot benefit from another invocation of the restoration boon until 24 hours have passed.

**Comment by ucffool** [comment]
> cancelling

Actually, **both** canceling and cancelling are correct, but it must be **_consistent_** through the text.

**Comment by JVanGo** [comment]
I stand corrected.
