### ISSUE TITLE
Destructive Trance prerequisite?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#435]
I get why Destructive Trance includes Might 7 as a prerequisite. Why doesn't it have Energy 7, Entropy 7, etc. as prerequisites? I can see a sorcerer going into this crazy battle trance and casting lots of spells and ending up fatigued. And doing that in a way that is more destructive than usual.

**Comment by brianfeister** [comment]
Alright, I'm good with that proposal. Will add it

**Comment by oconnor0** [comment]
As I read the feat text, I see there are no mentions of attacks or boon invocations or anything like that, but simply: "While you are in a battle trance, in addition to dice exploding on any maximum die roll (as normal)...". Does that influence this?

**Comment by brianfeister** [comment]
LOL, I actually already had that on my list and noticed it too, after re-reading it in response to this.

**Comment by oconnor0** [comment]
Or just let characters be destructively observant! 🤣

**Comment by oconnor0** [comment]
I assume you know this was not included in the PDF preview?

**Comment by brianfeister** [comment]
Indeed I do. Second pass i suppose

**Comment by brianfeister** [comment]
@istabosz @oconnor0 -- really weird story! I was just writing up an Amaurea's Dawn NPC and for a few moments before I remembered this conversation I was thinking "Man, this should really work with more than just MIght!" (in my case, it was an Agility based character a bit like Rurouni Kenshin). 

So... really cool to have that confirmation where I didn't even remember for a moment that we already did it  👏👏👏

**Comment by brianfeister** [comment]
This is currently fixed.
