### ISSUE TITLE
Open legend alpha gap in the middle of a sentence 

### ISSUE THREAD

**Issue by patgauvingeek** [openlegend/core-rules#440]
I'm not sure if I should post issue about the layout here, but I don't know if there is a more appropriate place. Anyway, I found a odd line change in the middle of a sentence on page 11:

"They have exceptionally high defences, so Berserkers are always willing to call out <line change> foes with the provoke babe."

**Comment by patgauvingeek** [comment]
It didn't render well...

"They have exceptionally high defences, so Berserkers are always willing to call out [line change] foes with the provoke babe."

**Comment by patgauvingeek** [comment]
On page 14, there is a line with only the word "twice".

**Comment by brianfeister** [comment]
@patrick can you submit these on the error submission form? They are supposed to be reported here:

https://goo.gl/forms/HPcGn6vq7ye6TGDh2

**Comment by brianfeister** [comment]
Actually nevermind, I did the first and there's only one more

**Comment by patgauvingeek** [comment]
I just submitted... We are working so hard! ;-P

Especially you! :-)
