### ISSUE TITLE
Knockdown & Multi-target issue undone?

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#443]
So, currently the core here on github is showing the Advantage/Disadvantage instead of the +/- 2 for Guard. Also it is like that in the Alpha PDF.

https://github.com/openlegend/core-rules/issues/419

Maybe it is just updated on another branch?

Also, thinking about this, would it be better to just put a disclaimer in the Multi-Targeting section of the core rules instead of continuing to update issues like this where they might pop up?

For example, in the Multi-Targeting section in the combat chapter:

"When Multi-Targeting and targets have different amounts of Advantage/Disadvantage, the GM may elect to assign a +/- 2 to their Guard instead."

I know that is horribly worded at the moment.

**Comment by brianfeister** [comment]
Mmm... I think it belongs in the feat, not in multi-targeting. 

The current state of the Core Rules text is in the `print-edition` branch:

https://github.com/openlegend/core-rules/tree/print-edition

**Comment by BuildAndDie** [comment]
Roger Doger.

Looks like it is referencing Advantage/Disadvantage on the print branch as well.

**Comment by istabosz** [comment]
Hmm... I had fixed it in print here: https://github.com/openlegend/core-rules/commit/03c9a86b0edeb4308ab5d6304405a32112a400d9
