### ISSUE TITLE
Attack Specialization mentions Creation

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#444]
Was going to post this to the google forms submission thing for the Alpha PDF, but wanted to post here first @brianfeister 
---------------
As pointed out be Arisu in discord chat:

In the attack specialization feat : 

> Examples of attack types you can choose to specialize in include fire, cold, lightning, acid, poison, entropy, creation, and force - though this list is not exhaustive.

yet in the section "using attributes to inflict damage" : 

> Without a very good explanation, the following cannot be used for damaging attacks: fortitude, learning, perception, will, deception, persuasion, presence, creation, prescience.

A bit odd that creation is listed in both of them.

------------

Perhaps in Attack Spec, it was suppose to be Alteration instead of Creation? That or it was from back when you could use attack spec for banes.

**Comment by brianfeister** [comment]
I agree. I was biting my tongue in not changing this, but really I should have asked @istabosz what his reasoning was for this.

Can you explain @istabosz ?

**Comment by istabosz** [comment]
I think it's just a carryover from a time when we weren't sure where Creation fit in the spectrum of damaging attacks. The "Using Attributes to Inflict Damage" section was written long after the feats were drafted, so Attack Specialization just needs to be updated to remove Creation.

**Comment by brianfeister** [comment]
Addressed. 👍  @BuildAndDie
