### ISSUE TITLE
Feat > Natural Defense (Description needs Toughness wording added)

### ISSUE THREAD

**Issue by ucffool** [openlegend/core-rules#445]
> When you are not wearing armor, you gain an armor bonus to your Guard defense. Your armor bonus is determined by your tier in this feat: 

_This should be revised as follows:_

**When you are not wearing armor, you gain an armor bonus to your Guard and Toughness defenses. Your armor bonus is determined by your tier in this feat:**

**Comment by brianfeister** [comment]
Thanks @ucffool. Fixed.
