### ISSUE TITLE
Martial Focus attacks language?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#446]
"When making attacks" would seem to mean that both damaging attacks and bane attacks are made with the "1 greater" "attribute dice".

The last sentence says that "damaging attacks you make without your martial focus suffer disadvantage 1." This doesn't refer to "bane attacks". This feels kind of kludge-y and unnecessary. 

Standardize on either "attacks" or "damaging attacks"?

**Comment by istabosz** [comment]
Yea. I think it should apply to all damaging and bane attacks in both cases

**Comment by brianfeister** [comment]
Sure, agreed it should apply to both damaging and bane attacks

**Comment by BuildAndDie** [comment]
@brianfeister I can't remember from our Mod discussions, but is it intended that Martial Focus can't be used for the Defend Interrupt Action?

Extraordinary Focus allows this.
