### ISSUE TITLE
Skill Specialization clarification?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#447]
Rules as written, Skill Specialization (Agility) applies to initiative rolls (pg 87: "each combatant makes an Agility action roll. The total of a combatant's Agility roll is their initiative score."). This allows for overlap with Lightning Reflexes and makes Skill Specialization (Agility) more valuable than other Skill Specializations.

Also Skill Specialization only specifies "non-attack, non-invocation rolls" allowing the granted advantage to be used when making defend actions. This provides overlap with Defensive Reflexes and allows a low Agility character to buy advantage on their defend actions. In conjunction with Battlefield Reflexes, this allows Skill Specialization to deal damage. 

Are these intended? Do they need to be clarified?

**Comment by brianfeister** [comment]
That's a valid point. Thoughts on fixing this @istabosz ?

**Comment by istabosz** [comment]
I think all of these have been addressed in #448 and fixed in the commits referenced in there. Closing this.
