### ISSUE TITLE
Craft time (extraordinary)

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#449]
Craft Extraordinary Item only shortens the craft time for *consumable* items but not for *expendable*. This seems inconsistent since they are both single use items. Does it make sense to change:

"Creating an item with the *consumable* property requires one full 8-hour day of uninterrupted work."

to:

"Creating an item with the *consumable* or *expendable* property requires one full 8-hour day of uninterrupted work."

**Comment by BuildAndDie** [comment]
I've been ruling this way for my games, as it made sense to me. I'd concur with this as an idea.

**Comment by brianfeister** [comment]
sounds good, hopefully all of these tweaks don't mess with layout 😬

**Comment by istabosz** [comment]
Fixed via https://github.com/openlegend/core-rules/commit/c6abfcc1674b797b0267b8124718156cf63841e1

**Comment by istabosz** [comment]
Accidentally edited in the .yml

Just updated the .md with https://github.com/openlegend/core-rules/commit/e27ae5833ae3fbb975030b359bda64085995f4cf
