### ISSUE TITLE
Longshot Question

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#450]
So this is a pretty minor thing, but thought I would point it out after John's question in discord about it.

It would only affect 1 range, which is Long Range. But changing the wording slightly to say:

"You may choose to increase the range by 1 increment. Close becomes Short. Short becomes ....."

Right now if you choose it for a long range weapon, you get extreme, but now have the penalty of not being able to use the long range weapon from 0-50 ft.

Narrative it makes sense you could choose, however balance might be an argument to keep it how it is (as well as layout of PDF before printing).

**Comment by oconnor0** [comment]
That feat also doesn't deal with Extreme to 500' - like how does that change the "dead zone" of the weapon?

**Comment by ucffool** [comment]
> You may choose to increase the range by 1 increment. Close becomes Short. Short becomes ...

Since it's a choice, it automatically gets the benefit of being the original _OR_ longer. The word _choose_ essentially already solves it.

Suggestion (though unnecessary as written):

** If you choose a weapon, the weapon's range _gains the benefits of the_ next greater range increment.**

**Comment by brianfeister** [comment]
> You may choose to increase the range by 1 increment for purposes of distance only. Close becomes Short. Short becomes...

**Comment by brianfeister** [comment]
@oconnor0 it doesn't change it, thus it's correctly omitted.

**Comment by BuildAndDie** [comment]
The you may choose was my suggested wording, it is NOT currently worded that way.

> the weapon's range is increased to the next greater range increment.

Currently it IS INCREASED.

**Comment by istabosz** [comment]
So, I think that the only thing that is meant to get affected is the actual distance. Taking Longshot in a long ranged weapon just increases the distance to 300'; it doesn't add the dead zone penalty. Similarly, taking the feat for a Short ranged weapon increases the distance to 75' but doesn't make it require 2 hands.

@brianfeister Am I correct?

If so, then I say we just super-simplify it and say "Your range is doubled for the chosen attack type or weapon."

For weapons, this doesn't really change too much and what little is changed is worth the value of simplifying.

**Comment by BuildAndDie** [comment]
I like that, simplifies and makes it all the same across the board between weapons and extraordinary

**Comment by brianfeister** [comment]
Can't believe I'm saying this but I'm totally on board, but the problem is that it's going to hugely cut down the text, causing a cascade of changes... 🤕

**Comment by brianfeister** [comment]
Was brave and did it anyway :/

```
Effect: When you take this feat, select one weapon or attack type. Examples of attack types you include fire, cold, lightning, acid, poison, entropy, creation, and force - though this list is not exhaustive.
With the chosen weapon or attack type, your range with that weapon or attribute is doubled.
Special: You may take this feat multiple times. If you do, select a new weapon or attack type each time.
```

**Comment by istabosz** [comment]
Fortune favors the bold!
