### ISSUE TITLE
Phantasm Resist Question

### ISSUE THREAD

**Issue by JVanGo** [openlegend/core-rules#451]
I have a question regarding Phantasm and when to resist it. Here are the passages, which I think don't interact too well:

> Instead, your Influence roll for invoking it is compared with the Resolve defense of each character that would perceive the created effect if it were real.

and

> Characters convinced by the phantasm can roll Resist as normal in order to attempt to shake off the bane.

In my opinion, these two sentences are in conflict with each other, provided "Resist as normal" means spending a move action to do so. Why are these two at odds? Because spending a move action means a character is actively trying to resist the bane. But if a character perceives the phantasm as if it was real and convinced by it, how can they be acting actively against it. There are certainly situations where this ruling makes sense (other party members pointing out a character's strange behaviour, something being out of place, etc.), but what if neither of these conditions set in? Don't the subjects never get to roll a resist roll? Wouldn't it better to handle Phantasm's resist rolls similarly to other "mind-affecting" banes like charm, fear, etc?

This problem gets even more enhanced when you factor in Hallucination and Mass Hallucination, as they add the following rules to phantasm:

> When you invoke the phantasm bane, you may choose to create a hallucination within a single target's mind instead of an illusion that is perceptible to everyone. **You gain complete control over the target's senses** (as granted by the power level of your bane)...

So how can a target subject to a Phantasm actively try to resist the bane, if they don't know that they are under the influence of it? @brianfeister @istabosz

**Comment by istabosz** [comment]
I think this is a situation when the GM is needed. The point is that mechanically speaking, resisting phantasm is the same as resisting any other bane, but the GM can determine when a character would actually be reasonably allowed to attempt to resist it. If the GM doesn't want players resisting until they have some reason to suspect it, then he can just not tell them it's a phantasm bane.

In cases where the players do know but the characters don't, I think that's just a matter of the mechanics informing the narrative. Something like this...

Player: "I roll to resist the phantasm. (rolls) Success!"

GM: "Okay, but your character didn't necessarily know that the goblin was an illusion. What happens to change that?"

Player: "Well, when it was moving closer to me, I noticed it walked over some rubble, but the rocks didn't shift at all. That made me suspicious, so I focused my mind more and realized I could see THROUGH the goblins if I tried hard enough."

**Comment by JVanGo** [comment]
To me Phantasm is much more in line with banes like dominate or fear, but I guess I'm alone with that opinion then. I still feel this doesn't acknowledge the existence of the hallucination feat and the interactions caused by it, but I think we can close this thread as there won't be any changes.

**Comment by brianfeister** [comment]
@JVanGo I see your point and I agree there's a problem. But making it an auto (passive) resist roll each round would for the most part make Hallucination weaker than Phantasm, which is kind of defeats the point of it being a feat that's more powerful. 

As a way of being BOTH simple and reflecting the depth of immersion and confusion this feat causes, I've added the following to the Hallucination I feat effect: 

> In addition, unless the target is damaged, they suffer disadvantage on resist rolls against the bane.

**Comment by brianfeister** [comment]
Also, if we did something like "Roll Logic first to figure it out" then we're in trouble because now it needs a CR assigned. Hopefully this takes care of it.
