### ISSUE TITLE
Multi-Target Attack Specialist references projectile?

### ISSUE THREAD

**Issue by oconnor0** [openlegend/core-rules#452]
The feat text for Multi-Target Attack Specialist mentions choosing one of melee, projectile, or area to specialize in. The combat rules reference "Melee Multi-Targeting", "Ranged Multi-Targeting", and "Area Multi-Targeting".

Is the reference to "projectile" in Multi-Target Attack Specialist supposed to be ranged instead?

**Comment by BuildAndDie** [comment]
Also, in the combat section, under

## Choose Your Target

it references Projectile there as well, instead of Ranged.

**Comment by istabosz** [comment]
Fixed in print-edition via https://github.com/openlegend/core-rules/commit/f667d1c96a57ceb158f4fae43d3f8c24469da02a and https://github.com/openlegend/core-rules/commit/c81f266775ea635d863282db6b49eeb05b2cb93c
