### ISSUE TITLE
Defensive Reflexes and Mystic

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#453]
@brianfeister wasn't sure where we were on using the google form submission for the Alpha PDF. Are we still using it?

And you might have already addressed this somewhere else, but when I looked at the print edition tree, it was still worded the same.

Right now Defensive Reflexes requires Agility to be able to get it. The Mystic on Page 21 says it has Defensive Reflexes feat, yet has no Agility.

Is Defensive Reflexes suppose to open up to more than just Agility?

**Comment by brianfeister** [comment]
Not sure what happened, but it's correct in `print-edition` for me:

https://github.com/openlegend/core-rules/blob/print-edition/core/src/04-feats/01-chapter-four.md#battlefield-retribution

lists 

```Battlefield Retribution

Cost: 2 points
Prerequisites:
Tier 1: Agility 4, Might 4, or any Extraordinary 4```

**Comment by BuildAndDie** [comment]
Not battlefield-retribution

Defensive Reflexes, which the print edition still says requires agility.

**Comment by BuildAndDie** [comment]
The issue isn't hte feat, but that Mystic has it listed as the feat, but has no Agility to be able to get the feat.

**Comment by brianfeister** [comment]
Gotcha, thanks. Fixed Mystic to meet the pre-requisite. 🥇
