### ISSUE TITLE
Barrier obscuring property requires 15' depth to do anything

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#455]
Just make it so that the barrier blocks line of sight like, even with 5' depth

**Comment by istabosz** [comment]
Fixed in print-edition via https://github.com/openlegend/core-rules/commit/1c178f2f9ad7cb4f1c9131e54f2cea03b80fa8bf

**Comment by brianfeister** [comment]
this fix seems a bit off. I've changed from 

> Creatures cannot see anything that falls within the barrier's area of effect.

to

> Creatures cannot see through any part of the barrier.

**Comment by istabosz** [comment]
Good fix.
