### ISSUE TITLE
Star Once Fallen

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#458]
I know this isn't really on the github, but thought I would post it here as a reminder of a thing to do?

Star Once Fallen on DriveThruRPG lists the community site as the mightybell link, figured that should be updated.

Also Evasion needs to be changed to Guard.

Some of the Feats need a bit of updating (Battlefield Sentinel to Battlefield Oppurtunist)

Banes updated (Blinded, Dispel to Nullify, Intimidated to Provoked, Scrying to Spying, Stunned)

Boons updated (Augury to Reading, Possibly Heal [though i know a few things different for the learn to play], Levitation to Flight, Resistance, Restoration [unless that way for learn to play], Shapeshift)

Realize not a priority as getting stuff to publish naturally.

**Comment by brianfeister** [comment]
Ok, where should we put bug reports for other content? We can't have it live in this repository.

**Comment by BuildAndDie** [comment]
Also, I figured the Feat Tactical Inspiration was something just for Star Once Fallen, or else it might should be removed as well?

No idea on where it could go to live though O.o;

**Comment by ucffool** [comment]
Resurrect the Trello board?

**Comment by oconnor0** [comment]
You could create a bug report repo in the openlegend project.
