### ISSUE TITLE
Ferocious Minion Feat

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#468]
So, taking a look at the feat, it states:

> Creatures under the effects of your charmed or dominated banes, or those created by your invocation of the summon creature boon, gain advantage 1 on all attack rolls to protect you or act in your favor for each tier of this feat you possess.

Is that suppose to be "action rolls" instead of "attack rolls"? It would make more sense given the "protect you or act in your favor" as those things might not always be "attacks" (perception check, defend interrupt, etc).

**Comment by brianfeister** [comment]
I'm fine with it. Also, we're not accepting further changes. :)
