### ISSUE TITLE
Ferocious minions

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#470]
Print edition and main github don't match

Main github needs updated to say Invoking Attribute 4/5/7 for the prerequisites.

**Comment by jcte02** [comment]
Please see ufctool's review of the feats.yml file in PR #460. Invoking
attribute is print only, in the site are listed the effective attributes.

Il 6 ott 2017 00:23, "Great Mustache Jonathan" <notifications@github.com>
ha scritto:

**Comment by jcte02** [comment]
Il 6 ott 2017 00:27, "Fabio Endrizzi" <fabioendrizzibz@gmail.com> ha
scritto:

**Comment by BuildAndDie** [comment]
Where is this review, it isn't readily obvious to me going to #460

**Comment by jcte02** [comment]
@BuildAndDie tldr:
![1](https://user-images.githubusercontent.com/1504687/31269824-2c1c0f1a-aa82-11e7-809c-dbb1cf7a962d.PNG)
![2](https://user-images.githubusercontent.com/1504687/31269827-30086a74-aa82-11e7-9fde-c27df47c54f7.PNG)
![3](https://user-images.githubusercontent.com/1504687/31269829-3294dc0a-aa82-11e7-8014-2cd5de40e92c.PNG)

**Comment by BuildAndDie** [comment]
Energy and Alteration (as well as Creation and Entropy already listed) are for the Summon Boon, which Ferocious Minion benefits from. So in this case, it should include both of those.

**Comment by jcte02** [comment]
@BuildAndDie I am a doofus. I confused `Animation` with `Summon Creature` (idk how) and this is why `Logic` is listed istead of `Alteration` and `Energy`. Gonna fix this one immediatly.

**Comment by jcte02** [comment]
Fixed in #471. Thanks for the clarification in your last answer. If you wouldn't have pointed that out to me, I would have never spotted my mistake.

**Comment by BuildAndDie** [comment]
Personally, I like Logic being involved with it. And actually, technically, Logic makes sense to be in it.

When you animate a creature, it starts out with Charm on it, so in theory the attribute you used to do animate could also be what could trigger Ferocious Minions. Some might think that a stretch though I suppose.

But like I said, that could be a bit of a stretch. Glad to help, that's what I'm here for when I'm not being a headache to Brian!!! ;)
