### ISSUE TITLE
Knockdown

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#473]
Knockdown is incorrect on the github, but correct on the website.

Here:

https://github.com/openlegend/core-rules/blob/master/banes/banes.yml

it shows it as the old, incorrect way of giving advantage or disadvantage. However the website is currently displaying the information correct by adjusting the guard score.

**Comment by jcte02** [comment]
I don't know what you're hinting to, but this is knockdown's effect in the link you pointed:

>The target falls prone. Prone targets have disadvantage 1 on all attacks they make. Characters that are prone due to the *knockdown* bane (or any other reason) get +2 to Guard versus Ranged attacks and -2 Guard versus Melee attacks. Standing up from prone requires a move action and costs a character half (round down) of their speed for the round.

and this is directly from the site:

>The target falls prone. Prone targets have disadvantage 1 on all attacks they make. Characters that are prone due to the *knockdown* bane (or any other reason) get +2 to Guard versus Ranged attacks and -2 Guard versus Melee attacks. Standing up from prone requires a move action and costs a character half (round down) of their speed for the round.

I see no differences. Were you maybe referencing an outdated version of the banes.yml file?

**Comment by BuildAndDie** [comment]
Strange.... I guess someone else was referencing an outdated version.... Yeah it is the same.

**Comment by jcte02** [comment]
They were referencing the `print-edition` branch:
> The target falls prone. Prone targets have disadvantage 1 on all attacks they make. Melee and area attacks against prone characters gain advantage 1. Projectile attacks against prone targets suffer disadvantage 1. Standing up from prone requires a move action and costs a character half (round down) of their speed for the round.

This is strange, as the `master` branch is the default branch for this Github repository. This means that whoever reported this issue had to manually switch to the `print-edition` branch.

**Comment by BuildAndDie** [comment]
actually they weren't referencing the print-edition branch, they were apparently referencing their own version of github that hadn't forked/pulled from this github in 4 months and  use a bot to read out the info to them in discord or some such.

**Comment by jcte02** [comment]
lol top tier git magiks
