### ISSUE TITLE
Truesight

### ISSUE THREAD

**Issue by BuildAndDie** [openlegend/core-rules#475]
both github yml and the website are missing:

Power Level 6 - The target's extraordinary sight
pierces natural and magical darkness.

This is in the final print edition PDF and in the print edition tree:

https://github.com/openlegend/core-rules/blob/print-edition/core/src/03-banes-boons/01-chapter-three.md#truesight

**Comment by BuildAndDie** [comment]
@jcte02

**Comment by jcte02** [comment]
Added to #472
