### ISSUE TITLE
Attribute and Feat Order Layout

### ISSUE THREAD

**Issue by rtemple1203** [openlegend/core-rules#48]
I noticed a couple of things.  First of all, the descriptions in Character Creation for the Social and Mental attributes are in the opposite order on the character sheet.  I would like them flipped around to match up easier.  Additionally, Master Tracker and Heavy Weapon Master are not alphabetized on the Feats listing.

**Comment by rtemple1203** [comment]
Also, on the Boons page, in the Reading A Boon Description section, it says Bane in both Power Level and Attributes.

**Comment by brianfeister** [comment]
Thanks 👍

**Comment by istabosz** [comment]
Fixed bane typo and out of order feats.
