### ISSUE TITLE
Universal Access Implant Attribute

### ISSUE THREAD

**Issue by frankieali** [openlegend/core-rules#483]
In the [Extraordinary Item Descriptions Table](https://github.com/openlegend/core-rules/blob/master/core/src/09-special-equipment/01-chapter-nine.md#extraordinary-item-descriptions) the `Universal Access Implant` has an Attribute of `Presence 7`, but in the [detail block](https://github.com/openlegend/core-rules/blob/master/core/src/09-special-equipment/01-chapter-nine.md#universal-access-implant) the Attribute is `Persuasion 7`. Not sure which one is correct. Probably Presence?

**Comment by BuildAndDie** [comment]
Persuasion is what I'm going with, as the text below the table tends to be more correct. And it mentions being persuasive specifically.

Devil's Advocate: It mentions persuasive b/c of rank, so Presence *could* make sense. But I don't think it's intended to work for doing boons (heal) or banes (demoralize), so leaned to Persuasion.
