### ISSUE TITLE
Fear and Opportunity

### ISSUE THREAD

**Issue by romst** [openlegend/core-rules#486]
As the rules state it, running away under the effect of "Fear" is not a voluntary movement, and therefore doesn't trigger an opportunity attack. But gameplay wise, that seems really stupid, since that implies, the guy running away through a line of opponents can't be stopped.

At least, the rules should clarify if or if not it is affected, but in my oppinion, it should definitly provoke attacks of opportunity.

**Comment by bheads** [comment]
The target of fear is only forced to retreat, thus its normal movement.  They get to pick the path (as long as its not towards the source of the fear). As I read it, they are a target for attacks of opportunity.

Fear:
"On its turn, the afflicted target must use its entire turn to get as far away as possible from you. It cannot use its actions to do anything other than retreat, and it cannot willingly move closer to you while the bane persists."

Unlike Forced Move:
"**The target is moved a distance against their will**, as determined by the bane's power level. The ending location is chosen by the attacker."

Hope that helps
