### ISSUE TITLE
Finishing blow rules don't match between Core rules and free adventure A Star Once Fallen

### ISSUE THREAD

**Issue by jjnich** [openlegend/core-rules#50]
In the free adventure "A Star Once Fallen" under "Making a damaging attack" on page 10 it says "If an unconscious creature takes damage, it must make a Fortitude action roll greater than or equal to the damage or else it dies." but in the Core rules under "Finishing Blow" it says "When you suffer an attack while unconscious, incapacitated, or otherwise unable to defend yourself, you must make a Fortitude roll with a Challenge Rating equal to half the damage dealt. If you fail this roll, you are dead."

Is the final rule "CR = half damage" or "CR = full damage"? or is CR full damage for NPCs and half for PCs?

**Comment by istabosz** [comment]
Nice catch. There have been a few iterations of the core rules since the adventure was published, so there might be some variation, but that seems like a typo. Whatever the rule should be, it would apply the same to PCs and NPCs.

@brianfeister Do you want to weigh in here? I'm thinking that the CR should be equal to damage dealt. Half damage seems like it would be exceptionally hard to kill someone.

**Comment by jjnich** [comment]
Well the CR being based on fort and using full damage on an attack against fort defense is going to really adversely punish anyone not buying into fort at all (i.e. caster types and ranged guys).

This would mean for an example a Barbarian comes up and does a finishing blow on my 0 fort Ranger -> 2 handed weapon gives him advantage and he has a 5 might (1d20+3d6 dropping the lowest) gives him an average of about 20.5 (counting for exploding dice) on his attack -> my toughness of 12 with leather armor means I have to roll a 8.5 or better on 1d20 (Averaging just over 11) to not die.

A Barbarian on the other hand taking the same finishing blow with a 4 fort and a scale shirt (all available at lvl 1) would have 18 toughness and would therefore have to roll a 2.5 on 1d20+1d10 (which would average about 17 counting exploding dice).

I'm not sure a better way to do it, but at this rate it'd be near impossible to kill a barbarian and a pretty good chance of killing the ranger. Seems like there should be a better way to balance it so all the ranged/casters aren't total glass cannons unless they bulk up fort.

My idea would be something like one of these:
-Use your second highest stat on rolls against finishing blows (using your highest stat would make it too trivially easy to only use one stat IMO, this is probably too complicated anyway)
-Everyone simply rolls 1d20 against half the damage dealt
   ^-Using this it would be easy to make a feat for "Hard to Kill" or something similar that lets you add another die to this roll
-Something else that is a little more balanced

**Comment by jjnich** [comment]
Another option could be when you're the target of a final blow you don't get to take your toughness into effect. You're unconscious and easy to hit, so both the ranger and barbarian would take the same amount of damage. Then the CR should be the damage -10 or half the damage? Still gives the barbarian a benefit for being tough because he has more dice to roll, but doesn't give him too much benefit.

The only change would need to be the following:
Changing this under Finishing blows - "When you suffer an attack while unconscious, incapacitated, or otherwise unable to defend yourself, you must make a Fortitude roll with a Challenge Rating equal to half the damage dealt. If you fail this roll, you are dead."

Change "...half the damage dealt." to "...half the damage rolled."

This makes thematic sense as you're "unable to defend yourself" so they do a lot more damage, and makes the death mechanic slightly more balanced among different builds.

**Comment by DMsShadow** [comment]
While I get that it seems harsh on those with fewer points in fortitude. Doesn't it make sense that someone with a low fortitude is easier to kill?

Plus, if you let your wizard get into such a situation, you need to protect your weaker party members better.

**Comment by DukeAnax** [comment]
Also almost anyone should put some points in Fort, it's like then Con in DnD

**Comment by jjnich** [comment]
6 of the 12 archetypes in the character creation chapter have nothing in fort. IMHO it'd be better to not have anything be totally mandatory and that's what it seems like this system is going for. I agree that lower fort makes you easier to kill, that's why all my proposed solutions still have that effect.

**Comment by DMsShadow** [comment]
Or you could be really off the wall and say instead that you do a bane attack vs toughness to inflict the "dying" bane on a target. 3xfailed resist rolls = death

**Comment by DMsShadow** [comment]
Though if you did that, only 9% of those targeted in that way would actually die. Though if you say it's at disadvantage 1, then 1 in 3 die.

**Comment by jjnich** [comment]
My suggestion of changing it to damage rolled instead of damage dealt would result in slightly higher than 50% chance to survive for the ranger in my original example, and more than 70% chance for the barbarian.

**Comment by jjnich** [comment]
Maybe since Fort Will and Presence all factor into HP you could pick the highest of those to roll to avoid death?

**Comment by istabosz** [comment]
Ok. So I did a little digging into some older documents. It looks like the rule got mis-translated (by me) from some old wording we were using. The actual rule is supposed to be that you make a Fortitude roll with a CR equal to 10 + (2 x damage suffered). So, if you take 2 damage, it's CR 14. If you take 10 damage, it's CR 30.

It seems rough, true. But this is a last ditch effort to survive. So it shouldn't be easy. Especially when you consider the fact that the enemy (and, thus, the GM) has to make an active decision to attack an unconscious or otherwise neutralized combatant instead of one who is still a threat. That's not the type of attack that should be easily wasted.

**Comment by brianfeister** [comment]
I'm open to changing this because we should probably remove character's attributes to defense if they're not conscious. Just doesn't make sense otherwise. So, a full-plate wearing character would be hard to Death Blow.

Soooo... how about CR = Damage dealt (attribute bonuses to defenses don't apply)

**Comment by jjnich** [comment]
@istabosz if that's the rules, the ranger in my previous example would be looking for a CR 27 which is nearly impossible for him with 0 fort. I agree they should be hard, but surely they should be better than ~2%. I think "hard" would mean at least a 5% chance of success for someone who isn't good at fort. I also agree that with a decent GM this shouldn't come up all too often. (arrest them instead of killing them or something like that)

@brianfeister I think it makes more thematic sense for the attribute bonus to remain but the armor bonus to be removed - if someone is laying unconscious on the ground it's easy to find a weak spot in the armor or lift up a plate to get at flesh beneath it, but a tough guy is always tough. CR being half the damage rolled removes both armor and attribute from the equation and simplifies it a little. Or since all the defenses start at 10 make CR = 2x(damage rolled - 10). This is a little more complicated but would make it pretty hard to make the roll if you have 0 fort, but still (in my example above) a ~5% chance for the ranger and (not counting exploding) a 27.5% chance for the barbarian.

**Comment by brianfeister** [comment]
@jjnich Well, in my imagination, a majority of these attacks would be delivered without the ability to get right next to the person. Often a ranged supernatural or projectile attack would deliver the Finishing Blow.

**Comment by jjnich** [comment]
@brianfeister That's a fair point. The 2x(damage rolled-10) removes the question of whether defense should be used regardless of range/damage type. It also gives it a good/harsh difficulty curve based on fort (which still kinda makes fort almost a mandatory stat). I also still think it makes thematic sense, easier to hit the eye of a person unconscious with an arrow than one that's up moving around, easier to pull the life force from someone not actively resisting you, easier to light them on fire if they don't actively roll to put it out . . .

**Comment by istabosz** [comment]
I think we should go with @brianfeister 's formula just for simplicity's sake. The attribute bonus removed seems more generalizable than removing the armor bonus. You definitely can't dodge if you're unconscious, but your chain mail might still help you out. Especially because in the heat of combat, you wouldn't always have time to go searching for chinks in the armor. Also, that stuff can be covered by advantage granted by attacking prone targets and using a focus action.

**Comment by jjnich** [comment]
so in my example using the proposed formula by @brianfeister it'll be average CR 18.5 against the ranger who  will roll an average of 11ish and have about a 10% chance of surviving
the barbarian would have to roll a 12.5 and would average a 17ish and have a 68% chance of surviving.

Seemed like @istabosz wanted it to be more lethal than that.

**Comment by jjnich** [comment]
In the end it's up to you guys as the authors. I think the 2x(damage rolled - 10) is simpler, thematic, and general enough. It takes away the "which defense is included against final blows?" question because it's none of them. It removes the need to figure out what your defense is without your attribute bonus. It makes final blows around (all numbers are very approximate) twice as lethal.

Personally I'll probably house rule it to what I think will fit the difficulty I want in my game anyway. Honestly I'll probably never attack an unconscious PC.

**Comment by raihje** [comment]
I like @brianfeister's comment regarding the armour factoring but not the attribute. It seems easier to balance overall, and if they want to pick apart the armour- as someone else said - they're already attacking a prone target most likely, and/or they can focus for advantages.

**Comment by istabosz** [comment]
I have updated these rules reflecting @brianfeister 's suggestion, so I'm closing this issue.
