### ISSUE TITLE
Suggestion: Core PDF

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#53]
The site is excellent, and handy for people with either an internet connection or a laptop at the table. I was recently considering making a sort of "DM Screen" or "Quick Reference" sheets sort of like what's pictured here: http://crobi.github.io/dnd5e-quickref/preview/quickref.html for 5E.

Are there any plans to condense the information in the site to a searchable PDF that can be downloaded? Anything I make isn't going to be particularly fancy, or distributable. But this would be great for people with either a fair bit of ink in their printers and a stapler - or a tablet handy to pass around at a table. I'm sure I saw a better place for suggestions at one point, it's a shame I can't find the link atm.

**Comment by brianfeister** [comment]
Good news, @raihje - we'll be releasing a reference SRD with a new open license that allows for creation of commercial Open Legend content without a permission / grant process as we have now. It'll be like the MIT / BSD license for tabletop RPGs.

As part of this, we will be releasing a new SRD pdf that is both usable for reference and also serves as the open-source core of the game that can be used by others who wish to create and distribute Open Legend content.

**Comment by raihje** [comment]
That is excellent, glad to hear it.

**Comment by brianfeister** [comment]
Will be part of the SRD PDF, no reason to hold this ticket open for it's release. It's in the works and certainly won't be forgotten.
