### ISSUE TITLE
Martial Focus / Ritual Magic / Attribute Raising

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#54]
So there are a few feats that say "treat your attribute as though it were one higher" Is it intended that these don't scale to 10 (if your attribute was 9, for example) to represent your specialized focus on one type of attack, spell focus, or casting as a ritual?

I would like to suggest a new attribute level (10) that is only obtainable by having one of these such feats, as currently if a player uses this feat they lose the return on their investment after level 9 onwards.

This way, when they get to lv 9 they aren't just suffering disadvantage on other types, or incapable of casting without a focus without still getting something in return.

**Comment by istabosz** [comment]
Yea. I've been thinking the same thing based on a few other people's comments. Attribute 10 would be 4d8, but only attainable through feats, etc. What do you think @brianfeister ?

**Comment by brianfeister** [comment]
Yeah, was mentioned on the community site. Obviously an oversight on our part for not including it since we've clearly already given a path to needing attribute 10 for dice

**Comment by brianfeister** [comment]
Make it so

**Comment by brianfeister** [comment]
Issues remain open until the rules text has been updated.

**Comment by istabosz** [comment]
Oh. I've fixed this one. Forgot to close the issue.
