### ISSUE TITLE
Bad regex on website leads to "Light" boon single page showing "Flight" content

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#57]
Go here: http://www.openlegendrpg.com/boons/light

And fix the single routing regex

**Comment by ucffool** [comment]
Don't let this one die Brian... it'll take you like 15 seconds to fix the regex ;-)

**Comment by brianfeister** [comment]
escaping this regex in javascript is pretty gross, took more than 15 seconds ;P
```
const regex = new RegExp( `\\b${ name.toLowerCase().replace(/_/gi,' ')}`, 'gi');
```
