### ISSUE TITLE
Boon Focus III (Shapeshift) makes Master Shifter obsolete

### ISSUE THREAD

**Issue by DukeAnax** [openlegend/core-rules#58]
Right now the only effect master shifter gives is boon sustain, but you can also get that effect from Boon Focus, which is cheaper too (9 vs 10, 6 when you consider that you likely have Boon Focus I anyway)

The only reason to get Master Shifter is to have the boon sustain before level 2, but when you invest further in Boon Focus, that becomes wasted.

I suggest changing Master Shifter this way:
When the Shapeshift boon is targetting yourself it succeeds without making an action roll and you do not need to use the sustain a boon action to sustain it...

That Way the Master Shifter compeats with Boon Focus (Shapeshift) in a different way (transforming yourself vs others) and the Druid Archetype would appreciate being able to spend points on something other than Shifting, Bane Focus (Immobile) for those entangling roots for example.

**Comment by brianfeister** [comment]
Good catch, I had planned to remove Master Shifter altogether, but we'll entertain your suggestion as an alternative

**Comment by raihje** [comment]
Boon Focus has widespread applicable effects (ie, targeting your allies, multi-targeting advantages) master shifter would be a 3 point weaker boon focus targeting yourself with only the following.

You can sustain any shapeshift boon yourself without a minor action.
You automatically succeed at transforming yourself, and can do one action increment faster (ie you can transform and move/attack) However these benefits only apply while targeting you, and you cannot multi-target the boon and benefit from this feat.

**Comment by DukeAnax** [comment]
Es it is, the main point was, that without the automatic successit wouldn't be cheeper, but more restrictive.

**Comment by istabosz** [comment]
I kinda think Master Shifter should get the boot. We could theoretically have a feat like that for every boon out there. But we have chosen to generalize the feats. Since a druid could already take Superior Concentration to maintain shifting without an action, I think we've got this covered.

**Comment by raihje** [comment]
Yea, it makes sense tbh.

**Comment by brianfeister** [comment]
A "Master Shifter" druid archetype should just invest 6 feat points to get `Boon Focus II (Shapeshift)`.

Closing as fixed: https://github.com/openlegend/core-rules/commit/b35a582644220a6912a200a4830c03e7f6cc937f
