### ISSUE TITLE
Bane: Immobile - Creation as a source? Also: Creative Uses?

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#59]
Creation is toted as the "Nature Domain" supernatural ability. Genesis is all about creating various natural things from nothing. The description even reads: Whether through grappling, a precise nerve strike, _entangling vines_, exerting mental control, or a bone-numbing blast of cold, you render your foe incapable of movement.

So perhaps add Creation to the list for such occasions?

This also brings up an interesting question about DM Fiat and Creative uses.
For example, if I strike some one with an arrow, and then later use Creation sustain a bane of thorns/spikes growing within the enemy from the shaft of the arrow could that not be a Creation source of persistent damage? Is there a line that needs to be drawn to keep the rules/mechanics relevant?

**Comment by thefailking** [comment]
I think you can make an argument for using any attribute for any bane or boon 
if you ask your GM when you want to use it if its ok it is really up to them but the attribute on the list are there for a balance reason and if they weren't like I said you can make an argument for any attribute for any boon or bane.

**Comment by brianfeister** [comment]
Sure, you both can make an argument for any bane via any attribute and you also need to justify the story, even if you are operating within the normal boundaries of what's allowed. @istabosz I suppose we should be explicit about this in the core rules, I kind of assumed it was a given but yeah, it helps to be deliberate.

And yes, I agree we should add `Creation` as an attribute for the Immobile bane.

**Comment by DukeAnax** [comment]
Well some attributes would be really hard to justify, Prescience for example, Protection only against demons and undead. None of the mental attributes could immobilize. Presence maybe. Movement definitely.

Also Incapacitate is missing a whole list of possible attributes: Might, Creation, Entropy, Presence

We could probably go through the entire list and add an attributes every second bane or boon.

**Comment by raihje** [comment]
Creation has been added to Immobile in the source, whenever the site grabs from github again (nightly?) it'll update.
