### ISSUE TITLE
Clarifying a few rules

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#63]
How long is a turn/round? How many rounds in a minute (for effects that last for a minute if the resist fails, etc)

How heavy is your unconcious friend should you decide to drag or carry them after a hard-fought battle to somewhere safer?

Range - for range, is the area of effect you can choose to inflict (ie 25' for ranged attacks to multi-target, 25' range on a supernatural attribnute) is the area within that range, or spread "from a point within range"

**Comment by jjnich** [comment]
1 round is 6 seconds so 10 rounds in a minute.

I'd just consider an ally "bulky" meaning you can't carry more than one. There isn't really weight in this system.

For ranged multi-target attack all targets must be within a 25' square. Meaning a square where each side is no larger than 25', as opposed to a 25' radius which would be "25' from a central point".

**Comment by raihje** [comment]
Thanks, and one other thing.
Currently Movement has the least amount of boons/banes, with each attribute having around 2 unique boons (Prescience has 6 unique boons, 2 unique banes) This might end up being it's own issue but is there any plan to balance these (ie have a roughly equal number of banes/boons between each attribute, uniques or otherwise?

**Comment by brianfeister** [comment]
Adding `Slowed` to `Movement` is definitely reasonable. But no, there's no plan to balance them out.

**Comment by DMsShadow** [comment]
I did a spreadsheet a while back, though it was before the change to Influence, and there is a fairly good spread across the bane/boon spectrum. I feel that though it's not perfectly balanced, to do so would likely add meaningless ones, or those of limited use just for the purpose of 'balance' which defeats the whole keeping it simple brief.

**Comment by raihje** [comment]
Once we have something standard for moving unconscious entities I'll close the issue. Bulky makes sense, but if you have a backpack slinging them over your shoulder puts you at 5' movement.
I was thinking something like:

Carrying or Moving an unconscious entity reduces your movement by an amount equal to half it's base. You can move 5' extra up to your base speed for every level of Might.

Using the above, anyone can drag people, but the larger stronger characters are better at it, as someone mighty would naturally be better at such menial tasks such as lifting.

**Comment by istabosz** [comment]
One of the guiding principles behind OL was simplifying the sorts of rules that don't impact the fun of the game much. Hence, simplified wealth and encumberance. I think adding too many nuanced micro rules might just bulk the game up without really adding to the fun at the table. 

I think the ruling is to just count an unconscious body as bulky and heavy and to apply a pinch of common sense from there when it comes to larger creatures.

**Comment by brianfeister** [comment]
I agree with @istabosz. We have a lot of discussion happening and need to be decisive so I'm closing just for the sake of time spent discussing.
