### ISSUE TITLE
Typos & Clarity

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#64]
Energy Resistance - perhaps Tier 2 is 10, not 5?
Tier 1 - Your defense scores are increased by 5 against the chosen attack type.
Tier 2 - Your defense scores are increased by 5 against the chosen attack type.
Tier 3 - You are immune to damage from the chosen attack type.

Different mentions of distance (such as when speed is mentioned for slowed, or the feet is mentioned instead for silenced) use feet or integers. It might be wise to just define a square as 5 feet, and use integers everywhere else - or consistently use feet as a measurement. Either way, this would reduce confusion.

There was another typo that was an instance of "fo" instead of for but firefox doesn't have a find whole word only option and sifting through the three pages is starting to burn my eyes lol.

**Comment by brianfeister** [comment]
good catch

**Comment by LordRyst** [comment]
For issues like these, its pretty easy to make an edit, branch it, and make a pull request. Its usually easy for brian to accept a pull request, then to read an issue, make a judgement, and then make the change. On the other hand, many people are not used to GitHub who are excellent editors, in which case, welcome. Many of these kinds of projects are made by people without the right kinds of background and experience to catch all of the possible errors, and its a huge help.

**Comment by raihje** [comment]
Oh, thought you had to be a contributor to do that sort of stuff. Thanks for the heads up.

**Comment by LordRyst** [comment]
Everybody who makes a pull request that is excepted is a contributor! Don't worry, I'm already in process or making these changes. Hitting a sticky issue with 5 vs. 10 at the moment.

**Comment by raihje** [comment]
I need to fork this, make the changes, and have him pull them? I'm okay with that but is there any check to make sure my fork I edited is up to date with the working version? Sounds like a recipe for disaster if I keep a fork active for a while fixing whatever I come across and then request a pull..

**Comment by LordRyst** [comment]
I'm doing it right in GitHub and only making small edits to keep turn around time short. There are some general processes that work, but my recommendation is to follow http://nvie.com/posts/a-successful-git-branching-model/ if you are doing command line, or just edit a single file per pull request if you just use the file edit function through your browser. If there is an issue, it will be a merge conflict, but not too bad. Remember this isn't CVS, its Git. Thanks for your efforts, btw, editors are super important, because it gives credibility to projects.

**Comment by raihje** [comment]
I'm doing it through the command line, with gvim (syntax highlighting and spell checking) then I'll commit it to my fork, and issue a pull request. (I'll read up more on this process before I do this though.)

**Comment by beauseverson** [comment]
I had a clarification to put forth about invoking banes with 10+ damage, but I submitted it as separate commits. Would it be better to do it as a pull request from my own fork since the wording was in multiple places?

**Comment by LordRyst** [comment]
You should check about whether they want you to squash commits, but generally related commits should be submitted together as a branch from your fork. Look at http://nvie.com/posts/a-successful-git-branching-model/ for a good way to handle building your branch. The main difference is that you won't get to do the final merge, instead you will to a pull request.

**Comment by beauseverson** [comment]
Perfect. I'll look over the article. I'm working on running a one-shot with the system so hopefully that should shake loose some more fixes or clarifications. Looking forward to contributing.

**Comment by raihje** [comment]
I've already submitted a pull request, my fork fixes ~34 typos between boons, banes, and feats.
As for consistent use of speed and other stuff I'll wait for confirmation before forking and changing a bunch of stuff.

**Comment by jerenda** [comment]
As a person who has no idea what she's doing, I found a plain-English intro to Git: http://blog.scottlowe.org/2015/01/14/non-programmer-git-intro/ . Maybe the rest of you know what you're talking about, but I'm going cross-eyed. @LordRyst , you could include this in your list of useful references to link people to. :)

**Comment by beauseverson** [comment]
I'm a web dev by day but haven't done much open source work with Git repos.
