### ISSUE TITLE
Intimidated bane seems non-standard regarding number of targets.

### ISSUE THREAD

**Issue by istabosz** [openlegend/core-rules#8]
As is, the intimidated bane increases number of targets based on power level, but isn't that what multi-targeting is for?

What if higher power levels just increased the level of disadvantage. I'm thinking that disadvantage 1 isn't as strong of an effect at higher levels anyway so it won't really redirect attacks the way this bane is meant to.

**Comment by brianfeister** [comment]
Sounds good. Yeah, you're totally right, I was on a different wavelength when I willingly made this non-standard. Good catch!

**Comment by istabosz** [comment]
https://github.com/openlegend/core-rules/blob/master/banes/banes.yml#L373

Done. Let me know if it looks good. Started the disadvantage at 1 and just increased it by one per power level.

**Comment by brianfeister** [comment]
looks good 👍
