### ISSUE TITLE
Immobile Bane Prereq 0

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#80]
It was brought up on mightybell that a Might 0 or Agility 0 might make sense. But that the supernatural prerequisites be raised to at least 1 or 2. This might come across as a bit pedantic but a character with 0 agility is merely slow/not agile. A character with 0 creation or entropy or energy however, hasn't manifested those abilities effectively (yet, OL is particularly open.)

That being said, any attribute of 0 is just a d20, so while as written they can attempt supernatural feats without having any experience in those abilities, it's a d20 vs their defense which means the chances aren't necessarily very high. (50% with defense of 10, 25% with defense of 15, and so on.)

**Comment by istabosz** [comment]
I'm kinda thinking we should just raise the prereq. to 1 all around. I mean, a zero is just a bit odd.

**Comment by raihje** [comment]
Makes sense to me, I think most if not all banes should be min 1 of their attributes, otherwise they wouldn't really have any prereqs.

**Comment by raihje** [comment]
Derp, vim lied to me. I'm going through manually and so far Surprised is 0 but it makes sense since it's N/A for everything else.

**Comment by brianfeister** [comment]
Agreed, let's make the prerequisite 1, it actually creates a good excuse to have even some low level attribute in order to use this. So `Might 0` means you're so weak you can't even "grapple"

**Comment by raihje** [comment]
Alright I'm issuing a PR right now with the fix.
