### ISSUE TITLE
Slight grammar issue

### ISSUE THREAD

**Issue by YokoAhava** [openlegend/core-rules#84]
In chapter 6: Combat under the header "determine targeted defense," you didn't include a space between "precise" and "property"

**Comment by raihje** [comment]
@istabosz recently committed an overhaul to combat, I checked out the header:
3. Determine Targeted Defense

It seems to look fine. I'm not sure how often the site builds from the source of this project but when it does this issue will be resolved.

**Comment by brianfeister** [comment]
@raihje is correct. Closing.
