### ISSUE TITLE
Should unarmed attacks have the Two-handed property?

### ISSUE THREAD

**Issue by Odog4ever** [openlegend/core-rules#89]
Unless we are imaging characters literally punching with one arm tied behind their back it's logical they would be using both hands (or even feet) when attacking.

I think the mechanical bump, 1 advantage, would help to make the unarmed option not objectively worse than taking even the weakest weapon which is important when considering most unarmed character concepts assume years of experience and/or training.

And this is definitely an active choice by the PC and not something that activates if anybody loses their regular weapons.
 
Perhaps it can be tied to brass knuckles/bracers if it helps clarify it as a "weapon" choice.

**Comment by brianfeister** [comment]
I'm ok with the imbalance. Unarmed Strike having the `Two-Handed` property would be more unbalanced than the reverse. 

Instead I've added `Stunned` as an associated bane for `Unarmed Strike`:
https://github.com/openlegend/core-rules/commit/577a5cf1b5b98196a1989f131bc2d282faaed5cb

**Comment by Odog4ever** [comment]
OK any thoughts on adding fist weapons like gauntlet or brass knuckles?

**Comment by brianfeister** [comment]
I think they should be treated as `Unarmed Strike`
