### ISSUE TITLE
Unlimited Minor Actions Concern

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#91]
Was just rereading some of the rules when one of my players asked me about minor actions. According to the latest update, you get "1 Major, 1 Move, and Unlimited Minor Actions". My concern is that this means that a player, according to this rule, could "Sustain: Minor Action" any number of boons, thus invalidating the Boon Focus feat. 

Are we incorrectly reading this rule? I imagine this is not the spirit of the rule, but the wording of the rule seems to imply that you could effectively sustain any number of boons. 

Perhaps we should quantify "Free Actions" vs. "Minor Actions" and only allow 1 Minor Action per round. I realize that this means a lot of headache defining what makes an action "Free" or "Minor", but I feel like it might be worth the clarification. 

EDIT: I see now in the "Boon: Duration" explanation it says that the Sustain action can only be taken once per round. Maybe that should be in the explanation for "On your turn you can take..." section as well, just to simplify it. Also, I still think maybe there needs to be a distinction between "Free" and "Minor" actions, just for clarity's sake.

**Comment by brianfeister** [comment]
@istabosz is this not clear in the rules? The rules specifically say `You can take any number of minor actions but only one of a given type`

**Comment by Odog4ever** [comment]
@Hassurunous opportunity attacks gives a free attack and that occurs outside of a player's turn but what other "free" actions are there? I'm not seeing it in the combat section of the rules...

**Comment by DukeAnax** [comment]
I think it is very clear, In this case it is probably more an issue with reading comprehension.

Some people only scan a text and imagine the rest. When they reread it, they always read what they thought it read.

**Comment by istabosz** [comment]
@brianfeister Yep. It's stated in the rules: 

> When your turn in the initiative order comes, you are allowed one major action, one move action, and any number of minor actions (though you may not take more than one minor action of the same type). In lieu of taking any of these actions, you may choose to take one focus action on your turn.

I say we just keep this on our radar. If we get more reports that the rule is unclear, we can try to clarify the wording.

**Comment by Hassurunous** [comment]
Yeah, sorry, I found that section shortly after the player asked me about it. Forgot to update before heading to bed. I think I'm going to put together a quick reference, sort of like they were talking about in another thread for my players.

**Comment by thefailking** [comment]
@Hassurunous no need there is one already made

**Comment by thefailking** [comment]
https://docs.google.com/document/d/1fI3xFrhIlVyrECPfflgmSboSE2PdOqNESf08U7OiK5w/edit

**Comment by istabosz** [comment]
K. This issue looks resolved, so I'm gonna close it.
