### ISSUE TITLE
Sanctity of Feats?

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#95]
So in WoD there's this thing called Sanctity of Merits, which means if your 4 dot retainer dies, you get those 4 merit dots back. If the campaign removes your 3 or 4 dots of resources (essentially wealth/living standards) you get those dots back to spend on other merits.

For feats that could potentially be lost (ala Companion, Spellcasting Focus Familiar?) perhaps there should be a sanctity rule so that players could spend those points either on replacing their companion or on another feat.

**Comment by Hassurunous** [comment]
I had a similar thought about this. I was planning on just allowing players to find another companion, but that isn't exactly satisfying if they've built a strong relationship with that character. I like the idea of being able to re-spend those feat points. If the companion or familiar is supernatural, perhaps it could be resummoned or something, but regular companions or familiars (one of my players has a dog, for example) couldn't simply be replaced as easily (at least from an emotional and narrative perspective).

**Comment by raihje** [comment]
That's why I said just regain the points. If they want to go get it revived or something, that'd mean they're investing into the companion again. If not, they could put those feats somewhere that serves them (maybe they train harder as grievance/penance to their companion, as a narrative example)

**Comment by brianfeister** [comment]
I already noted this with `Boon Access` that you get the points back when not relevant, we can note it for `Companion` as well.

**Comment by istabosz** [comment]
Added text to companion and supernatural focus.

Has anyone spotted any other feats that need this clarification?

**Comment by raihje** [comment]
@istabosz Pretty sure that covers it, solid.

**Comment by brianfeister** [comment]
Deploying now.
