### ISSUE TITLE
Lower Power Level for Flight via Shapeshifting

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#97]
@istabosz I think we've pretty safely bumped flight into the category of "not very difficult to attain" thanks to the new `Flying` feat, `Alternate Form`, and `Flight (Power Level 5)` boon. 

I think turning into a bird is basically the favorite thing in the whole world for @briandonahue and a huge group of other players. Our "tier bump" that happens at level 5 works for most things, but D&D and other systems don't make druids wait that long for that ability so we should probably just work flight into the `Shapeshift` boon at power level 5. Let's discuss

**Comment by briandonahue** [comment]
I actually reluctantly agree that flying at Level 2 was a bit of a luxury, though it sure was fun to frolic between three different forms so early :)  I think it does make sense to make it harder to achieve.  I don't know what the plans are for including an official table of animal forms, but I did try to translate Eli's work to a spreadsheet here: https://docs.google.com/spreadsheets/d/1JB4T85H3DHaoRAeeUMxp6v7ZJZP5WB_s2q0nkVTnoD0

Most of the levels and attributes differ pretty significantly from the early pre-gen Druid, so would be nice to have more clarity there, but for now I was thinking about starting with wolf, adding bear form around level 3, and hawk at 5 or 6.  

I can be a little over-enthusiastic (maybe OCD) about the rules - in our recent game with a new GM I had to bite my lip when some "saving throws" were rolled, but it's all in good fun and really just spurred by my enthusiasm and appreciation for what you guys are doing!

**Comment by brianfeister** [comment]
"saving throws" ... LOL

**Comment by istabosz** [comment]
Yea. I think it makes sense to reduce flight to PL 5 shapeshift.

**Comment by brianfeister** [comment]
Closed via https://github.com/openlegend/core-rules/commit/8d65386e1dbc00b6ea89de5c01580bcb2240bad1
