### ISSUE TITLE
Inconsistent Feat Formatting

### ISSUE THREAD

**Issue by raihje** [openlegend/core-rules#98]
I'll look into this and possible issue a PR but right now Fleet of Foot isn't rendering tier 2 and 3.  
Multi-Target Boon Expert isn't using an unordered list like other feats that have attribute and feat requirements.

Fleet of Foot looks fine in feats.yml
Multi-Target Boon Expert has Boon Focus or the Specialist Feat at tier 2 as a requirement. I'll fix the formatting so that they're both required.

edit: Multi-Target Boon Expert is fixed in PR #99

**Comment by brianfeister** [comment]
Merged fix PR: https://github.com/openlegend/core-rules/pull/99
